### ISSUE TITLE
UnrecognisedImageFormatError with aliyun oss storage

### ISSUE THREAD

**Issue by fordguo** [wagtail/wagtail#10120]
### Issue Summary

Change some codes with #10051 ,I can upload image,but browser the admin/images，throw the title exception.

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start oss_image_project`
2.  change storage: `DEFAULT_FILE_STORAGE = "django_oss_storage.backends.OssMediaStorage" STATICFILES_STORAGE = "django_oss_storage.backends.OssStaticStorage"`
3. migrate and runserver
4. upload a image with admin-Images,then visist `/admin/images/`
5. get `UnrecognisedImageFormatError at /admin/images/`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/images/

Django Version: 4.0.10
Python Version: 3.8.16
Installed Applications:
['home',
 'search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']


Template error:
In template /Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/templates/wagtailimages/images/results_image.html, error at line 18
   Unknown image format
   8 :  This behaviour caused a confusing error on the images listing view where it
   9 :  would go blank if one of the images was invalid.
   10 : 
   11 :  Separating the image rendering code into this file allows us to limit Django's
   12 :  crash/blanking behaviour to a single image so the listing can still be used when
   13 :  the issue occurs.
   14 : {% endcomment %}
   15 : 
   16 : {% load wagtailimages_tags %}
   17 : 
   18 : <div class="image"> {% image image max-165x165 class="show-transparency" alt="" %} </div>
   19 : 

Traceback (most recent call last):
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/models.py", line 427, in get_rendition
    rendition = self.find_existing_rendition(filter)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/models.py", line 483, in find_existing_rendition
    raise Rendition.DoesNotExist

During handling of the above exception (), another exception occurred:
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(

During handling of the above exception (Rendition matching query does not exist.), another exception occurred:
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/admin/auth.py", line 197, in overridden_render
    return render()
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/templatetags/wagtailimages_tags.py", line 113, in render
    rendition = get_rendition_or_not_found(image, self.filter)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/shortcuts.py", line 13, in get_rendition_or_not_found
    return image.get_rendition(specs)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/models.py", line 429, in get_rendition
    rendition = self.create_rendition(filter)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/models.py", line 513, in create_rendition
    rendition, created = self.renditions.get_or_create(
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 754, in get_or_create
    return super(RelatedManager, self.db_manager(db)).get_or_create(**kwargs)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/query.py", line 664, in get_or_create
    return self.create(**params), True
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/query.py", line 512, in create
    obj = self.model(**kwargs)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/base.py", line 564, in __init__
    post_init.send(sender=cls, instance=self)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/db/models/fields/files.py", line 491, in update_dimension_fields
    width = file.width
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/django/core/files/images.py", line 20, in width
    return self._get_image_dimensions()[0]
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/models.py", line 204, in _get_image_dimensions
    self._dimensions_cache = self.get_image_dimensions()
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/wagtail/images/models.py", line 216, in get_image_dimensions
    image = willow.Image.open(self)
  File "/Users/ford/venv/wagtail/lib/python3.8/site-packages/willow/image.py", line 99, in open
    raise UnrecognisedImageFormatError("Unknown image format")

Exception Type: UnrecognisedImageFormatError at /admin/images/
Exception Value: Unknown image format

```
-   Python version: 3.8
-   Django version: 4.0.10
-   Wagtail version: 4.2

**Comment by fordguo** [comment]
Maybe aws storage can reproduce,there are some codes can help:
```        
       try:
            # add this seek can fixes the image format error.
            self.seek(0)
            image = willow.Image.open(self)
            return image.get_size()
        finally:
            if close:
                self.close()
            else:
                self.seek(0)
```

**Comment by fordguo** [comment]
sorry ,the #10051 has fixes this.
