### ISSUE TITLE
Clean up Status template tag adoption

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10129]
### Is your proposal related to a problem?

As a follow up from #9721 & #8656 it would be good to finalise the status tag adoption 100% and also adopt BEM classes for the status tag now that most classes are in one place.

<img width="865" alt="Status tag examples" src="https://user-images.githubusercontent.com/1396140/220348762-80270d23-35e8-45bf-8842-41e21dd0094e.png">

### Describe the solution you'd like

Note: These parts should be done as separate PRs to make it easier to review.

#### Part 1 - Update leftover `status-tag` usage

Review additional `status-tag` usage and migrate to the template tag `{% status ... `

* `wagtail/admin/templates/wagtailadmin/reports/workflow.html`
* `wagtail/admin/templates/wagtailadmin/shared/workflow_history/detail.html`
* `wagtail/admin/templates/wagtailadmin/tables/status_flag_cell.html`
* `wagtail/contrib/redirects/templates/wagtailredirects/list.html`
* `wagtail/admin/templates/wagtailadmin/tables/status_flag_cell.html`
* `wagtail/admin/templates/wagtailadmin/collections/_privacy_switch.html` (NOT this one - see https://github.com/wagtail/wagtail/issues/10128 )

#### Part 2 - Use BEM `w-status` classes

* Update classes to be `w-status` and use BEM prefixes
* For example `status-tag` would be `w-status` and `primary` would be `w-status w-status--primary`
* We will 
* Note: We may want to adjust the overuse of `classname` on the status template tag and provide a shortcut `variant='primary'` which would generate the class `w-status--primary`.

Full classes list

* `status-tag` -> `w-status`
* `status-tag--label` -> `w-status--label`
* `primary` -> `w-status--primary`
* `disabled` -> `w-status--disabled`

### Describe alternatives you've considered

* Leave as is, these clean up items are not critical but would be nice to solve.

### Additional context

* See https://getbem.com/naming/ for classes
* See HTML in `wagtail/admin/templates/wagtailadmin/shared/status_tag.html`
* See template tag implementation in `wagtail/admin/templatetags/wagtailadmin_tags.py`
* Ensure scss is updated in `client/scss/components/_listing.scss` & `client/scss/components/_status-tag.scss` (main file) & `client/scss/layouts/_report.scss`
* _Originally posted by @lb- in https://github.com/wagtail/wagtail/issues/9721#issuecomment-1438356041_

**Comment by riyanrathore26** [comment]
I want to contribute
And can you explain me about this issue

**Comment by riyanrathore26** [comment]
I want to contribute
But can you explain more about it

**Comment by lb-** [comment]
@riyanrathore26 what kind of questions do you have?

**Comment by riyanrathore26** [comment]
I want to understand that what changes i could do.
And only replace status to w-status
And more tags

**Comment by lb-** [comment]
@riyanrathore26 maybe just start with part 1, also I recommend you read the linked PR and issue that got split to this issue. It should help with context.

**Comment by sande265** [comment]
Hi @lb-  is this issue still open, if yes I would like to work on this issue.

**Comment by HimanshuGarg47** [comment]
Hi! I want to try out this issue. 
I have few doubts

- In Part 1, only mentioned files are to be updated or these are only sample files. 
- Html files not mentioned which have either status-tag in button or status-tag comes along with status-tag--label. So No need to update it. Like below
![image](https://user-images.githubusercontent.com/78200614/221350349-58a708e2-136b-4631-952b-4ed124358c3f.png)


- In Part 2, all scss files, html and py file needs to update to use BEM classes style. Am I right?
- What are PO files? Are they need to change ?

**Comment by salty-ivy** [comment]
> Hi! I want to try out this issue. I have few doubts
> 
>     * In Part 1, only mentioned files are to be updated or these are only sample files.
> 
>     * Html files not mentioned which have either status-tag in button or status-tag comes along with status-tag--label. So they no need to update it ? Like below
>       ![image](https://user-images.githubusercontent.com/78200614/221350349-58a708e2-136b-4631-952b-4ed124358c3f.png)
> 
>     * In Part 2, all scss files, html and py file needs to update to use BEM classes style. Am I right?
> 
>     * What are PO files? Are they need to change ?

No you don't need to change any PO files.

**Comment by HimanshuGarg47** [comment]
I have made a PR [#10154 ](https://github.com/wagtail/wagtail/pull/10154). Some checks are failing. I am not able to indentify cause of failing. How to identify errors from CircleCI test.

**Comment by deepampriyadarshi** [comment]
Hi @HimanshuGarg47 you can view you CI results by clicking on details
![image](https://user-images.githubusercontent.com/65447610/221370374-3124996e-1b1b-4a6a-a486-fa18c7b99883.png)

As per the error message, your test fails because of this:- 

![image](https://user-images.githubusercontent.com/65447610/221372101-51d71147-e642-492b-ad09-26119cbffc1d.png)

As far as I know nesting of template tags this way are not allowed in django..

**Comment by lb-** [comment]
Answers to the above questions, great questions everyone!

* In Part 1, only mentioned files are to be updated or these are only sample files.
  * These files are my quick search for what we need to change, but please do you own search
  * Remember that anything already using `{% status ...` may also have a classname added, but these do not need to change as part of part 1 as they are already using the template tag.
  * Be sure you are on the latest `main` as https://github.com/wagtail/wagtail/issues/10128 has been merged which covers one of the HTML cases that now has a different approach.
* What are PO files
  * PO files are translation files - see https://docs.djangoproject.com/en/4.1/topics/i18n/translation/
  * These do not need to change, for the most part, these never need to change in PRs, they are updated when a Release Candidate is prepared.
* In Part 2, all scss files, html and py file needs to update to use BEM classes style. Am I right?
  * Yes, all classes in use, including those passed into template tags, will need to be updated to ensure they use the correct new CSS classes
* Failing CI - @HimanshuGarg47  - yes the answer above is correct, you will need to pass in the prepared HTML as a fragment to the translation block (search for `fragment` in HTML files).

**Comment by rickturner2001** [comment]
Hi @HimanshuGarg47! I see that you're still working on the detail.html template. Are you trying to figure out how to get the raw HTML output of the status tag? If so, do you have a plan for how to fix this issue? Let me know if there's anything I can do to help

**Comment by HimanshuGarg47** [comment]
@rickturner2001 Yes, I figure it out. Just running pre-commit install is left. Installing and running pre-commit is not working in my docker-wagtail-develop env. Do you have any idea, how to do it in docker-wagtail-develop setup.

**Comment by rickturner2001** [comment]
@HimanshuGarg47  I'm not entirely sure about how to install and run pre-commit in a docker-wagtail-develop environment, but I can try to help you troubleshoot the issue. Did you have any issues while following the [docs](https://github.com/wagtail/docker-wagtail-develop)?

Also, are you encountering any specific errors or issues when trying to install and run pre-commit? If so, providing more information about those errors could be helpful in identifying the root cause of the problem.

Let me know if there's anything else I can do to help!

**Comment by HimanshuGarg47** [comment]
> @HimanshuGarg47 I'm not entirely sure about how to install and run pre-commit in a docker-wagtail-develop environment, but I can try to help you troubleshoot the issue. Did you have any issues while following the [docs](https://github.com/wagtail/docker-wagtail-develop)?
> 
> Also, are you encountering any specific errors or issues when trying to install and run pre-commit? If so, providing more information about those errors could be helpful in identifying the root cause of the problem.
> 
> Let me know if there's anything else I can do to help!

No issues while following the [docs](https://github.com/wagtail/docker-wagtail-develop)
**Error log**
`### version information

```
pre-commit version: 3.1.0
git --version: git version 2.37.0.windows.1
sys.version:
    3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
sys.executable: C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\Himanshu Garg\\.cache\\pre-commit\\repolz3_4a0e\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\himanshu garg\.cache\pre-commit\repolz3_4a0e
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
      
      [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\factory.py", line 57, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
      
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    Encountered error while generating package metadata.
    
    See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```

```
Traceback (most recent call last):
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\main.py", line 366, in main
    return hook_impl(
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\commands\hook_impl.py", line 254, in hook_impl
    return retv | run(config, store, ns)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\commands\run.py", line 437, in run
    install_hook_envs(to_install, store)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\languages\python.py", line 214, in install_environment
    lang_base.setup_cmd(prefix, install_cmd)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\lang_base.py", line 87, in setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "C:\Users\Himanshu Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\pre_commit\util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('C:\\Users\\Himanshu Garg\\.cache\\pre-commit\\repolz3_4a0e\\py_env-python3\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing c:\users\himanshu garg\.cache\pre-commit\repolz3_4a0e
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      Preparing metadata (pyproject.toml) did not run successfully.
      exit code: 1
      
      [14 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Himanshu Garg\.cache\pre-commit\repolz3_4a0e\py_env-python3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 40, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
        File "C:\Users\Himanshu Garg\AppData\Local\Temp\pip-build-env-uw5eaxlq\overlay\Lib\site-packages\poetry\core\factory.py", line 57, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
      
      [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    Encountered error while generating package metadata.
    
    See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
```
`

**Comment by rickturner2001** [comment]
@HimanshuGarg47 Interesting error. I was able to reproduce it on my machine with the regular pip installation. I'll take a look at it and see if I can figure something out. In the meantime, you can try to manually format the edited files with the formatting tool that should be installed in your python environment 

You should have installed all the dependencies listed in setup.py with:

```shell
pip install .
```

at which point you can navigate to your local fork of wagtail and run 

```shell
git status
```

the listed files should all be .html files that we can edit with. You should run this command for all listed files 

```shell
djhtml -i <filepath>
```

if you get an error saying that djhtml does not exist, you can manually install it in your machine as shown [here](https://pypi.org/project/djhtml/)

This is a temporary solution, but it should allow you to pass the tests (unless there are any further syntax issues in the code)

**Comment by rickturner2001** [comment]
@HimanshuGarg47  Good news! I got it to work!

Some other people were having a similar issue [here](https://github.com/home-assistant/core/issues/86892#issuecomment-1407641288).

so I changed the isort version from

```yaml
    # isort config is in setup.cfg
    rev: 5.12.0
```

to

```yaml
    # isort config is in setup.cfg
    rev: 5.12.0
```

after this I was getting some node issues that were essentially saying that my npm version was ahead of the node version. It seems that even though we are using the version of node in our local system

```yaml
 node: system
```

it still uses node LTS 12.22

so I downgraded npm to the [latest stable](https://nodejs.org/en/blog/release/v12.22.1/) version for that node version as follows:

```bash
npm install -g npm@6.14.12
```

Don't forget to git add .pre-commit-config.yaml before running pre-commit.

@lb- If you have time, would you please look into this? Should I issue a PR to update the version of isort in pre-commit-config.yaml?

**Comment by rickturner2001** [comment]
Hey @HimanshuGarg47 were you able to set up your development environment?

**Comment by HimanshuGarg47** [comment]
I tried a lot but didn't work for me. Now I move on to vagrant setup

**Comment by rickturner2001** [comment]
@HimanshuGarg47 Hey, it looks like you're having a hard time setting up your environment. Do you mind if I take  over?

**Comment by HimanshuGarg47** [comment]
@rickturner2001 I have been busy for the past couple of weeks but am now able to devote more time to completing this task. If I do encounter any difficulties or feel that I need assistance, I will be sure to reach out to you for help.

**Comment by lb-** [comment]
Splitting the BEM classes part to #10244
