### ISSUE TITLE
Searching on specific fields does not work on SQLite FTS backend

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#10217]
### Issue Summary

Passing a `fields` attribute to `Page.objects.search(...)` or the SQLiteSearchBackend `search` method throws a `django.db.utils.OperationalError: no such column` exception when the SQLite FTS search backend is in use.

### Steps to Reproduce

From the `./manage.py shell` prompt on a bakerydemo instance:

```python
from bakerydemo.locations.models import LocationPage
LocationPage.objects.search("Laugavegur", fields=["address"])
```
fails with the exception
<details>

```
Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 544, in search
    obj_ids = [
              ^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/base.py", line 308, in __repr__
    data = list(self[:21])
           ^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/base.py", line 302, in __iter__
    return iter(self.results())
                ^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/base.py", line 268, in results
    self._results_cache = list(self._do_search())
                               ^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 623, in _do_search
    return list(self.get_queryset())
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 615, in get_queryset
    return self.query_compiler.search(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 548, in search
    raise OperationalError(
django.db.utils.OperationalError: no such column: address The original query was: SELECT "wagtailsearch_indexentry_fts"."autocomplete", "wagtailsearch_indexentry_fts"."title", "wagtailsearch_indexentry_fts"."body", "wagtailsearch_indexentry_fts"."rowid", "wagtailsearch_indexentry"."id", "wagtailsearch_indexentry"."content_type_id", "wagtailsearch_indexentry"."object_id", "wagtailsearch_indexentry"."title_norm", "wagtailsearch_indexentry"."autocomplete", "wagtailsearch_indexentry"."title", "wagtailsearch_indexentry"."body" FROM "wagtailsearch_indexentry_fts" INNER JOIN "wagtailsearch_indexentry" ON ("wagtailsearch_indexentry_fts"."rowid" = "wagtailsearch_indexentry"."id") WHERE (wagtailsearch_indexentry_fts MATCH %s AND "wagtailsearch_indexentry"."content_type_id" IN (%s)) ORDER BY bm25(wagtailsearch_indexentry_fts) DESC('{address} : ("Laugavegur")', 23)
```
</details>

Or querying the backend directly:

```python
from bakerydemo.locations.models import LocationPage
from wagtail.search.backends import get_search_backend
s = get_search_backend()
s.search("Laugavegur", LocationPage, fields=["address"])
```

fails with
<details>

```
Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 544, in search
    obj_ids = [
              ^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/query.py", line 1867, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1398, in execute_sql
    cursor.execute(sql, params)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: address

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/base.py", line 308, in __repr__
    data = list(self[:21])
           ^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/base.py", line 302, in __iter__
    return iter(self.results())
                ^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/base.py", line 268, in results
    self._results_cache = list(self._do_search())
                               ^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 623, in _do_search
    return list(self.get_queryset())
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 615, in get_queryset
    return self.query_compiler.search(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/search/backends/database/sqlite/sqlite.py", line 548, in search
    raise OperationalError(
django.db.utils.OperationalError: no such column: address The original query was: SELECT "wagtailsearch_indexentry_fts"."autocomplete", "wagtailsearch_indexentry_fts"."title", "wagtailsearch_indexentry_fts"."body", "wagtailsearch_indexentry_fts"."rowid", "wagtailsearch_indexentry"."id", "wagtailsearch_indexentry"."content_type_id", "wagtailsearch_indexentry"."object_id", "wagtailsearch_indexentry"."title_norm", "wagtailsearch_indexentry"."autocomplete", "wagtailsearch_indexentry"."title", "wagtailsearch_indexentry"."body" FROM "wagtailsearch_indexentry_fts" INNER JOIN "wagtailsearch_indexentry" ON ("wagtailsearch_indexentry_fts"."rowid" = "wagtailsearch_indexentry"."id") WHERE (wagtailsearch_indexentry_fts MATCH %s AND "wagtailsearch_indexentry"."content_type_id" IN (%s)) ORDER BY bm25(wagtailsearch_indexentry_fts) DESC('{address} : ("Laugavegur")', 23)
```
</details>

Both versions work when run against a postgres database, returning `<SearchResults [<LocationPage: Reykjavik>]>`.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11.1
-   Django version: 4.1.6
-   Wagtail version: 5.0a0 main

**Comment by laymonage** [comment]
I can confirm this while working on #10290, encountered a similar error.
