### ISSUE TITLE
Moving a page from a newly-forbidden location raises an error

### ISSUE THREAD

**Issue by nimasmi** [wagtail/wagtail#10348]
### Issue Summary

An error is raised when moving a page _from_ a location where it is not permitted.

### Steps to Reproduce

1. Create a model "IndexPage" and another "ContentPage"
2. In the admin, create an instance of ContentPage not as a child of an IndexPage.
3. Add `parent_page_types = ["myapp.IndexPage"]` to ContentPage
4. Try to move the ContentPage instance to be a child of the IndexPage instance.

See the error:

```
DoesNotExist at /admin/pages/9/move/
IndexPage matching query does not exist.
```

<details><summary>Traceback</summary>

```
[2023-04-18 14:18:01,047][50][ERROR][django.request] Internal Server Error: /admin/pages/9/move/
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/venv/lib/python3.9/site-packages/wagtail/admin/auth.py", line 199, in overridden_render
    return render()
  File "/venv/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/venv/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 38, in render
    return super().render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 90, in render
    return super().render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/pattern_library/loader_tags.py", line 90, in render
    return super().render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/venv/lib/python3.9/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/venv/lib/python3.9/site-packages/django/template/base.py", line 698, in resolve
    new_obj = func(obj, *arg_vals)
  File "/venv/lib/python3.9/site-packages/wagtail/admin/templatetags/wagtailadmin_tags.py", line 335, in render_with_errors
    return bound_field.as_widget()
  File "/venv/lib/python3.9/site-packages/django/forms/boundfield.py", line 93, in as_widget
    return widget.render(
  File "/venv/lib/python3.9/site-packages/wagtail/admin/widgets/chooser.py", line 228, in render
    value_data = self.get_value_data(value)
  File "/venv/lib/python3.9/site-packages/wagtail/admin/widgets/chooser.py", line 216, in get_value_data
    instance = self.get_instance(value)
  File "/venv/lib/python3.9/site-packages/wagtail/admin/widgets/chooser.py", line 348, in get_instance
    instance = super().get_instance(value)
  File "/venv/lib/python3.9/site-packages/wagtail/admin/widgets/chooser.py", line 189, in get_instance
    return self.model_class.objects.get(pk=value)
  File "/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
```

</details> 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: not exactly, but I have reports of it happening on three distinct Wagtail projects.

### Technical details

-   Wagtail version: 4.2.1

**Comment by zerolab** [comment]
Marking as confirmed as I experienced it on a separate project (just did not get to file the issue. Thank you for this @nimasmi )

**Comment by zerolab** [comment]
The issue stems from the fact that `AdminPageChooser` will set the `model` property to the specific page class when there is only one target model (via `parent_page_types`) - https://github.com/wagtail/wagtail/blob/main/wagtail/admin/widgets/chooser.py#L253-L256

which then comes in play in https://github.com/wagtail/wagtail/blob/main/wagtail/admin/widgets/chooser.py#L111-L121 via https://github.com/wagtail/wagtail/blob/main/wagtail/admin/widgets/chooser.py#L279-L282


Draft PR at #10362
