### ISSUE TITLE
Migrate error: Insert or update on table "wagtailcore_site" violates foreign key constraint

### ISSUE THREAD

**Issue by coredumperror** [wagtail/wagtail#1042]
I'm trying to rename a model on my under-construction wagtail site. Here's the migration that Django 1.7 created for me with `manage.py makemigrations`:

``` python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caltech', '0005_auto_20150112_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePage',
            new_name='StaticPage',
        ),
        migrations.AlterField(
            model_name='gridpage',
            name='template_name',
            field=models.CharField(default='grid_page_1', help_text='Select the Grid Layout that this page should be displayed in.', max_length=255, verbose_name='Grid Layout', choices=[/* snipped */),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='gridpage',
            name='text_color',
            field=models.CharField(default='dark', max_length=32, blank=True, choices=[('light', 'Light'), ('dark', 'Dark')]),
            preserve_default=True,
        ),
    ]
```

Unfortunately, running this migration with `manage.py migrate` triggers this traceback:

```
Running migrations:
  Applying caltech.0006_auto_20150304_1149...Traceback (most recent call last):
  File "./manage.py", line 35, in <module>
    execute_from_command_line(argv)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/migrations/executor.py", line 63, in migrate
    self.apply_migration(migration, fake=fake)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/migrations/executor.py", line 97, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/migrations/migration.py", line 107, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 174, in database_forwards
    to_field,
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/backends/schema.py", line 473, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type, old_db_params, new_db_params, strict)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/backends/schema.py", line 709, in _alter_field
    self.execute(self._create_fk_sql(model, new_field, "_fk_%(to_table)s_%(to_column)s"))
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/backends/schema.py", line 99, in execute
    cursor.execute(sql, params)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/rrollins/virtualenvs/wagtail_skunkworks/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: insert or update on table "wagtailcore_site" violates foreign key constraint "e181210f85fc0cf3e7df40df0f654de1"
DETAIL:  Key (root_page_id)=(1) is not present in table "caltech_staticpage".
```

Could this be related to the change I made to the root page setting in the non-wagtail django admin page? I changed the "localhost" Site so that its root page is "Root". I think it used to be unset (the "------" option in the dropdown). The "Root" page isn't a StaticPage, though (its a Page that came with the wagtail install), so I'm not sure why this is even coming up.

**Comment by coredumperror** [comment]
Attempting to run the migration without the "migrations.RenameModel" line works fine. I hadn't realized that I had other changes besides the ArticlePage model rename in there.

Making a migration that has just the "migrations.RenameModel" action triggers the same traceback.

**Comment by gasman** [comment]
Are you using Sqlite as your database backend, by any chance? I recall hearing that Sqlite doesn't support table renaming, so Django migrations have to do a full drop/recreate of the table instead - and I can't think why else this migration would be inserting data into `wagtailcore_site`.

Incidentally (although I can't see how it would cause this problem) - setting 'Root' as the root page of your site is a bad idea. The tree root is not designed to be an editable page, and only really exists as an implementation detail so that you can navigate to the top level within the explorer.

**Comment by coredumperror** [comment]
Nope, I'm using Postgres for my DB.

I knew when I did it that setting Root as the root page wasn't really the right thing to do. I don't remember exactly why I did it, actually, but it was just a minor workaround for something. The site is still in a very early pre-alpha state, and Root will not remain the root page once I implement the homepage mechanism we're going to be using.
