### ISSUE TITLE
Inconsistent evaluation of pages as leaves

### ISSUE THREAD

**Issue by owen9825** [wagtail/wagtail#10530]
### Issue Summary
I'm unable to add a child page, under **Home**.

### Steps to Reproduce

1. I started a new project and installed Wagtail, as per <https://docs.wagtail.org/en/stable/getting_started/tutorial.html>
2. I visited <http://127.0.0.1:8000/admin/pages>
3. Upon trying to add a child page, whether that's the existing `HomePage` or another page I had been creating, there's a crash during save. I've traced it to [here](https://github.com/wagtail/wagtail/blob/82119360acf19961bf6169290995c916fdfe9bb6/wagtail/admin/views/pages/preview.py#L92):

```python
        if parent_page.is_leaf():
            # set the path as the first child of parent_page
            page.path = page._get_path(parent_page.path, page.depth, 1)
        else:
            # add the new page after the last child of parent_page
            page.path = parent_page.get_last_child()._inc_path()
```
It appears that there's a timing inconsistency − the parent is _currently_ a leaf, but will no longer be, by the end of the operation.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (**yes** / no)

### Technical details

-   Python version: `3.10.12`
-   Django version: `4.2.2`
-   Wagtail version: `5.0.1`

Trace:
```
[09/Jun/2023 11:09:52] "POST /admin/pages/add/home/homepage/3/preview/ HTTP/1.1" 500 98735
Internal Server Error: /admin/pages/add/home/homepage/3/
Traceback (most recent call last):
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 176, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/wagtail/admin/auth.py", line 184, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/wagtail/admin/views/pages/create.py", line 119, in dispatch
    return super().dispatch(request)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/wagtail/admin/views/pages/create.py", line 132, in post
    return self.form_valid(self.form)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/wagtail/admin/views/pages/create.py", line 141, in form_valid
    return self.publish_action()
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/wagtail/admin/views/pages/create.py", line 197, in publish_action
    self.parent_page.add_child(instance=self.page)
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/treebeard/mp_tree.py", line 1091, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/home/owen/underground/underground-crm/venv/lib/python3.10/site-packages/treebeard/mp_tree.py", line 383, in process
    newobj.path = self.node.get_last_child()._inc_path()
AttributeError: 'NoneType' object has no attribute '_inc_path'
```
Here are the screens, in order:
![Capture d’écran de 2023-06-09 21-13-38](https://github.com/wagtail/wagtail/assets/1582341/ece3ea7f-8c97-48d2-ae7b-602585a1f9c5)
![Capture d’écran de 2023-06-09 21-13-52](https://github.com/wagtail/wagtail/assets/1582341/fcd75281-9a5c-4c50-bed3-604d9772b0ad)
![Capture d’écran de 2023-06-09 21-14-01](https://github.com/wagtail/wagtail/assets/1582341/1dd92d37-9297-464c-89d3-8dcc4c2ebe21)
![Capture d’écran de 2023-06-09 21-13-25](https://github.com/wagtail/wagtail/assets/1582341/3590aeaa-5427-41b3-9885-af7c17355a19)

**Comment by owen9825** [comment]
I should be able to fix this quickly

**Comment by gasman** [comment]
Thanks for the report @owen9825!

The 'steps to reproduce' here do seem a bit suspicious - if that was really all it took to replicate this issue, we'd be seeing it on every Wagtail installation. Are you sure there isn't some signal handler or custom `save` method in your code that's triggering this?

**Comment by owen9825** [comment]
Hmm actually yeah, I was just double-checking with a new project and it turned out fine sorry.

I hadn't modified any signals or overridden `save`, so I'm not sure what the point of difference is. I was unable to reproduce this :crying_cat_face:

**Comment by owen9825** [comment]
In my original project, I cleared away the database, then applied the migrations again, created a superuser and I was able to create a new Page fine.

I hadn't directly accessed the database − it was all through Django / Wagtail.

**Comment by HyperUpscale** [comment]
What exactly was the solution, because I have the same problem?

**Comment by gasman** [comment]
@HyperUpscale See https://stackoverflow.com/a/75327195/1853523 - `./manage.py fixtree --full` will usually fix this on an existing project.
