### ISSUE TITLE
Upload from image chooser popup returns _pickle:PicklingError after upgrading to version 5.1.2 from version 5.0.3

### ISSUE THREAD

**Issue by xeroticikot** [wagtail/wagtail#11058]
### Issue Summary

Recently I've upgraded from v5.0.3 to v5.1.2, everything works fine except for the image chooser popup in stream fields. While uploading the image through that option gives 500 server error. I'm using django-cache database cache in development & redis in production. Below is the error log from console - 

```Internal Server Error: /admin/images/chooser/create/
Traceback (most recent call last):
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\wagtail\admin\urls\__init__.py", line 180, in wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\wagtail\admin\auth.py", line 165, in decorated_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\wagtail\admin\views\generic\chooser.py", line 530, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\wagtail\images\views\chooser.py", line 206, in post
    return self.get_chosen_response(image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\wagtail\admin\views\generic\chooser.py", line 470, in get_chosen_response  
    response_data = self.get_chosen_response_data(item)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\wagtail\images\views\chooser.py", line 40, in get_chosen_response_data     
    preview_image = image.get_rendition(preview_image_filter)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\wagtail\images\models.py", line 455, in get_rendition
    Rendition.cache_backend.set(cache_key, rendition)w
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\django\core\cache\backends\db.py", line 102, in set
    self._base_set("set", key, value, timeout)
  File "E:\WORKPLACE\ACMS\cenv\Lib\site-packages\django\core\cache\backends\db.py", line 132, in _base_set
    pickled = pickle.dumps(value, self.pickle_protocol)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <class 'wagtail.blocks.base.UserLinksMeta'>: attribute lookup UserLinksMeta on wagtail.blocks.base failed
```

### Technical details

- All versions are latest.

**Comment by gasman** [comment]
Hi @xeroticikot - thanks for the report.

Looks like this error is coming from a class called `UserLinksMeta`, which isn't something that exists in Wagtail's codebase. Is that something defined in your project? (Maybe a custom block type, or something related to a custom image model - it's hard to tell just from the error trace.) If so, please could you share the piece of code that defines it?

**Comment by gasman** [comment]
Actually, looking closer, it could be a block called `UserLinks` - could you share the code for that please?

**Comment by xeroticikot** [comment]
I've tried removing that UserLinks from the custom User model. But, now getting the following error -

**Comment by laymonage** [comment]
Looking at how the error consistently happens when trying to access `Meta` classes of StreamField blocks, and how we've never seen a similar issue before, it seems like it might have been an obscure Python bug on Windows.

Closing for now, but feel free to report back if the issue still persists with a newer version of Python, Django, and Wagtail.
