### ISSUE TITLE
500 error when moving a page to a path longer than 255 characters

### ISSUE THREAD

**Issue by BertrandBordage** [wagtail/wagtail#11053]
### Issue Summary

If you have `'wagtail.contrib.redirects'` in `INSTALLED_APPS` and `WAGTAILREDIRECTS_AUTO_CREATE` enabled (it is by default),
triggering the creation of a new `Redirect` instance by moving a page or changing its slug can lead to a 500 error.
The exact error depends on your database backend.

### Steps to Reproduce

1. Use a project with `'wagtail.contrib.redirects'` in `INSTALLED_APPS` and `WAGTAILREDIRECTS_AUTO_CREATE` set to `True` or unset
2. Go to the admin interface, prepare a new page page with the maximum slug length (255 characters) **as a child or descendant of a page that's bound to a `Site` instance** (that's important, it will not work if you create a home page under the root for example)
3. Publish that page
4. Edit that page to change its slug (the new slug length doesn’t matter)
5. Publish that page, you get the error. With psycopg, it's the error below.
6. If you refresh the page and send again the form, then the error does not occur, but the redirection was never created.

```python
Traceback (most recent call last):
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 180, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/admin/auth.py", line 165, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/admin/views/pages/edit.py", line 386, in dispatch
    return super().dispatch(request)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/admin/views/pages/edit.py", line 470, in post
    return self.form_valid(self.form)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/admin/views/pages/edit.py", line 496, in form_valid
    return self.publish_action()
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/admin/views/pages/edit.py", line 568, in publish_action
    action.execute(skip_permission_checks=True)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/actions/publish_revision.py", line 217, in execute
    return self._publish_revision(
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/actions/publish_revision.py", line 152, in _publish_revision
    object.save()
  File "/usr/lib/python3.10/contextlib.py", line 78, in inner
    with self._recreate_cm():
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/transaction.py", line 307, in __exit__
    connection.set_autocommit(True)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/backends/base/base.py", line 501, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/backends/base/base.py", line 779, in run_and_clear_commit_hooks
    func()
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/models/__init__.py", line 1454, in <lambda>
    lambda: page_slug_changed.send(
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/contrib/redirects/signal_handlers.py", line 48, in autocreate_redirects_on_slug_change
    create_redirects(page=instance, page_old=instance_before, sites=sites)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/contrib/redirects/signal_handlers.py", line 182, in create_redirects
    batch.process()
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/coreutils.py", line 475, in process
    self._do_processing()
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/wagtail/coreutils.py", line 555, in _do_processing
    self.model.objects.bulk_create(
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/models/query.py", line 803, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/models/query.py", line 1839, in _batched_insert
    self._insert(
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/bertrand/.virtualenvs/flaubert/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.DataError: value too long for type character varying(255)
```

### Technical details

-   Python version: 3.11.5
-   Django version: 4.2.5
-   Wagtail version: 5.1.1

This error could be fixed by changing the `CharField` of `Redirect.old_path` to a `TextField`, in the same way as `Page.url_path`.
The difference is that we need to make this database `TextField` render as a `CharField` form field in the admin, and add a special validation to prevent newlines in it.

**Comment by Chiemezuo** [comment]
Is there a possibility of expanding the maximum length of a CharField instead?

**Comment by BertrandBordage** [comment]
@Chiemezuo I'm afraid the only way to make redirections consistent with pages is to make make `old_path` unlimited (like `Page.url_path`, and the only way is with a `TextField`. Putting a larger limit than 255 would move the problem without fixing it.

That being said, in practice, there is a limit based on the maximum depth of Pages × slug max length. From what I know of Wagtail & django-treebeard, it should be `(Page._meta.get_field('path').max_length // Page.steplen - 1) * (Page._meta.get_field('slug').max_length + 1) + 1`, which is 15873 characters (the 2 `+ 1` are for `/` between slugs and at the end). It is lower than the largest possible `CharField.max_length` with most databases.

So in theory, one could change this max_length to fit the dynamic calculus above, but if we do that on `Redirect.old_path`, we must do the same on `Page.url_path`.

**Comment by Temidayo32** [comment]
@Chiemezuo  I think the point @BertrandBordage is trying to make is a case for consistency in the source code to avoid further problems. We could go for a quick fix by extending `CharField.max_length`. But that might be problematic later on. I think it might be left to the core team to decide whether to adopt `TextField` for `old_path` as against `CharField`. 

@thibaudcolas @lb @laymonage

**Comment by lb-** [comment]
No need to mention core team @Temidayo32 unless it's something blocking. Most of us keep an eye on issues anyway. Some team are away this week aslo.

I'm sure this will get further eyes on this in due course, your approach seems sound and Bertrand's original suggestion makes sense. It may be worth trying to contribute a fix but at first it would be good to maybe reproduce and add a comment with a stacktrace to help us further confirm this as a repeatable problem.

Additionally, a fix is good, but it will need to come with testing, have a look at how to write a test that fails due to this problem. This will also help you know a fix is suitable. 

Just a note, my username is `@lb-` (with a hyphen). 

Thanks for working to understand and try to reproduce the issue.

**Comment by Chiemezuo** [comment]
Thank you @lb- 😃

**Comment by Temidayo32** [comment]
Thanks for the correction @lb- Sorry about that. I will definitely look into reproducing the problem. Thanks

**Comment by Temidayo32** [comment]
@BertrandBordage I have tried reproducing the error as you stated and using the technical details you provided, and I didn't get the error. I started off the page with a 255 characters long slug, then published it. Then, I edited the slug (you mentioned the new length doesn't matter), then published it again, and the page was published without throwing any error.

**Comment by BertrandBordage** [comment]
@Temidayo32 Yes, as I pointed out in this other comment, SQLite does not check constraints, so this issue can only be seen on "strict" SQL databases: https://github.com/wagtail/wagtail/issues/11054#issuecomment-1768067995

For more info on this (that SQLite calls a feature, even though it misleads everybody): https://sqlite.org/flextypegood.html
There are other bits of documentation about why SQLite does not enforce other things like foreign keys etc.

**Comment by BertrandBordage** [comment]
Another piece of information to advocate in favor of setting `max_length` on both `Redirect.old_path` and `Page.url_path`:
URLs are limited by what browsers allow. So if we wanted Wagtail to be cross-browser compatible, we should limit both fields to 2000 characters (according to [this long post](https://stackoverflow.com/a/417184/1576438)).
To be confirmed too, but I suspect that this does not mean 2000 Unicode characters, because non-ASCII characters are encoded differently. So either we should make a validation based on the length of `urllib.parse.quote(value)`.

Here is an example of difference of length, for just a single non-ASCII character:
![image](https://github.com/wagtail/wagtail/assets/1119169/b8261e4c-9084-4cf1-a927-914eef6c6c3a)

All this means we should ideally raise an error when setting the slug of a deeply nested page to prevent impossible-to-access pages. Something like:
```python
max_slug_length = (
    page.__class__._meta.get_field('url_path').max_length
    - 1  # Separating slash.
    - len(page.get_parent().url_path)  # Or deduce from `page.url_path`.
)
if max_slug_length <= 0:
    # Ideally, this should be done upstream, even at the permission level.
    # Probably in `Page.can_exist_under` or `Page.can_create_at`.
    raise ValidationError(_('Impossible to create this page, it is too nested.'))
if len(urllib.parse.quote(page.slug)) > max_slug_length:
    raise ValidationError({
        'slug': _(
            '“slug” cannot have more than %s URL encoded characters at this depth.'
        ) % (max_slug_length,),
    })
```

**Comment by Temidayo32** [comment]
@BertrandBordage You're right about the error. Just plugged in postgres.
![msedge_PYbCZtxdPW](https://github.com/wagtail/wagtail/assets/87539866/be25e600-c639-463d-ad7a-39af8d328a39)

**Comment by Temidayo32** [comment]
> max_slug_length = (
    page.__class__._meta.get_field('url_path').max_length
    - 1  # Separating slash.
    - len(page.get_parent().url_path)  # Or deduce from `page.url_path`.
)
if max_slug_length <= 0:
    # Ideally, this should be done upstream, even at the permission level.
    # Probably in `Page.can_exist_under` or `Page.can_create_at`.
    raise ValidationError(_('Impossible to create this page, it is too nested.'))
if len(urllib.parse.quote(page.slug)) > max_slug_length:
    raise ValidationError({
        'slug': _(
            '“slug” cannot have more than %s URL encoded characters at this depth.'
        ) % (max_slug_length,),
    })

@BertrandBordage I think this a good fix for the issue.

**Comment by Temidayo32** [comment]
> 
> ```python
> max_slug_length = (
>     page.__class__._meta.get_field('url_path').max_length
>     - 1  # Separating slash.
>     - len(page.get_parent().url_path)  # Or deduce from `page.url_path`.
> )
> if max_slug_length <= 0:
>     # Ideally, this should be done upstream, even at the permission level.
>     # Probably in `Page.can_exist_under` or `Page.can_create_at`.
>     raise ValidationError(_('Impossible to create this page, it is too nested.'))
> if len(urllib.parse.quote(page.slug)) > max_slug_length:
>     raise ValidationError({
>         'slug': _(
>             '“slug” cannot have more than %s URL encoded characters at this depth.'
>         ) % (max_slug_length,),
>     })
> ```

@BertrandBordage I think  your suggestion this a good fix for the issue.

**Comment by BertrandBordage** [comment]
@Temidayo32 You mean combined with setting `max_length` to 2000 for both `Page.url_path` and `Redirect.old_path`?

**Comment by Temidayo32** [comment]
@BertrandBordage Yeah, that should technically follow. 2000 is just the highest character supported by search engines. But it is not very likely to find URLs that long, so we might set `Page.url_path` and `Redirect.old_path` to a lower number, say 1000. Not super sure about that though. But I think I won't be wrong to say it might not make a lot sense to have a too nested page site. I mean developers work with UX designers and  marketers ( who are concerned about SEO) who might build out pages to ensure search engines can crawl all, so maybe an extremely nested website is unlikely to be a reality.

**Comment by BertrandBordage** [comment]
@Temidayo32 I don't have a strong opinion about it. Some editors really have a tendency to write very long article titles and nest so much categories in their tree structure. While it's probably not great for SEO, there can be valid reasons for these choices, especially in the world of science research. Yes, 1000 characters is very long and I probably never saw a case like that in my clients, but at the same time: is it Wagtail's job to define arbitrarily a limit lower than what it could be? :confused:

The fact that we are discussing this ~10 years of Wagtail proves that it probably doesn't matter much. We just have to pick a limit: 1000 or 2000 characters should not make much of a difference.

**Comment by thibaudcolas** [comment]
@lb- I don’t understand how this can be an enhancement considering the report from Bertrand. If default Wagtail functionality can lead to a 500, isn’t that the definition of a bug?

**Comment by lb-** [comment]
@thibaudcolas my thinking is that the introduction of a character length on a field that doesn't support that length (CharField) would constitute a developer change that's always going to break. The 500 error stacktrace is clear. 

Even if we introduces our own messaging, we would still throw an error. 

However, I'm not set on this being a bug or not. Just trying to support progress on a solution. I understand at this time we simply don't support anything beyond a standard CharField, and the error would be expected.

I think there should be some consideration of support for longer slugs, but this would be a new level of functionality. 

I might be missing something though.

**Comment by BertrandBordage** [comment]
@lb- The issue is not related to the length of the slugs. It is related to the length of URLs that are longer than 255 characters.

You can face the error with a page with a slug of 100 characters contained in 2 pages of 100 characters.
So to me it's not an enhancement for maybe increasing the size of slugs, it's a bug due to the inconsistency between the lengths of page URLs and redirection URLs.

**Comment by lb-** [comment]
Sorry for the runaround all. And yes, we may find a simpler solution to fix this instead of having to change the way slug field's max length works.

**Comment by Temidayo32** [comment]
@BertrandBordage this is all good that it is now clear a simple solution is the way forward with this issue.
