### ISSUE TITLE
get_rendition does not support the preserve-svg argument

### ISSUE THREAD

**Issue by jlchilders11** [wagtail/wagtail#11439]
### Issue Summary

When using image `image.get_rendition` and using a `format-` argument, the `preserve-svg` argument is not accepted and throws an uhandled error instead.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py to contain a page with a page with a ForeignKey to a WagtailImage
3. Create and run Migrations
4. In the django shell, import your model and get the instance, then try to run `page.image.get_rendition('fill-256x256|format-webp|preserve-svg')` and see that an unhandled `InvalidFilterSpecError` is thrown.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes
- I believe this is a bug, as the get_rendition documentation claims to accept any arguments that could be passed to the image TemplateTag

### Technical details

-   Python version: 3.11.7
-   Django version: 4.2.9
-   Wagtail version: 5.2.2
-   Browser version: Firefox 121

**Comment by gasman** [comment]
@jlchilders11 Thanks for the report! Confirmed on current main branch - the error I'm getting is:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/images/models.py", line 455, in get_rendition
    rendition = self.find_existing_rendition(filter)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/images/models.py", line 483, in find_existing_rendition
    return self.find_existing_renditions(filter)[filter]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/images/models.py", line 598, in find_existing_renditions
    Rendition.construct_cache_key(self, filter.get_cache_key(self), spec)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/images/models.py", line 1038, in get_cache_key
    for operation in self.operations:
                     ^^^^^^^^^^^^^^^
  File "/Users/matthew/.virtualenvs/wagtailpy312/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/images/models.py", line 890, in operations
    raise InvalidFilterSpecError(
wagtail.images.exceptions.InvalidFilterSpecError: Unrecognised operation: preserve
```

This is happening because the `{% image %}` tag [handles `preserve-svg` as a special case flag](https://github.com/wagtail/wagtail/blob/f0a67975db817a54a7c685ec618ee146b89ee839/wagtail/images/templatetags/wagtailimages_tags.py#L45-L46) to tell it to validate the list of filters that ultimately gets passed to `get_rendition`, rather than it being a filter in its own right.

**Comment by DevilsAutumn** [comment]
I would like to give it a try !

**Comment by jams2** [comment]
I don't think the reported issue is a bug — `preserve-svg` is not an image filter, as gasman pointed out, and the [docs clearly indicate this](https://docs.wagtail.org/en/stable/topics/images.html#svg-images).

In wagtail-grapple we do a bit of [extra handling](https://github.com/torchbox/wagtail-grapple/blob/166e78ae5a5634dc3dc0d01b98b0574ffe3350cf/grapple/types/images.py#L146) in the implementation of `preserve_svg`. If `preserve_svg` were exposed as a parameter of `get_rendition` we would be able to simplify that.

**Comment by thibaudcolas** [comment]
Just reviewing this, the [Generating renditions in Python](https://docs.wagtail.org/en/stable/advanced_topics/images/renditions.html#generating-renditions-in-python) `get_rendition` docs also clearly state:

> Argument options are identical to the {% image %} template tag’s filter spec, and should be separated with |.

So it does seem we should either change `get_rendition`, or if not at least update the documentation.

**Comment by thibaudcolas** [comment]
I see we have a PR #12011 adding `preserve-svg` support to `get_rendition`. Could people take a look and decide if that’s appropriate?
