### ISSUE TITLE
Bug in the tutor section "Images" in InlinePanel

### ISSUE THREAD

**Issue by p-p-a-83** [wagtail/wagtail#11562]
### Bug in the tutor section "Images" in InlinePanel

I reproduced the tutorial from https://docs.wagtail.org/en/stable/getting_started/tutorial.html. After adding the code for the image gallery, an error appeared. _AttributeError: 'InlinePanel' object has no attribute 'field_name'_ . 

```
(kuzovsibir) PS C:\Users\79232\my_sites\kuzovsibir_ru\kuzovsibir_ru> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\79232\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\79232\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\django\core\checks\model_checks.py", line 36, in check_all_models
    errors.extend(model.check(**kwargs))
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\models\__init__.py", line 1517, in check
    errors = super().check(**kwargs)
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\models\__init__.py", line 906, in check
    *super().check(**kwargs),
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\models\__init__.py", line 483, in check
    *super().check(**kwargs),
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\models\__init__.py", line 850, in check
    *super().check(**kwargs),
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\models\i18n.py", line 190, in check
    errors = super().check(**kwargs)
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\search\index.py", line 108, in check
    errors.extend(cls._check_search_fields(**kwargs))
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\search\index.py", line 114, in _check_search_fields
    for field in cls.get_search_fields():
  File "C:\Users\79232\my_sites\kuzovsibir_ru\env\kuzovsibir\lib\site-packages\wagtail\search\index.py", line 55, in get_search_fields
    search_fields[(type(field), field.field_name)] = field
AttributeError: 'InlinePanel' object has no attribute 'field_name'
```

### Steps to Reproduce

1. All steps from tutor befor "Images"
2. Edit blog\models.py as follows: Add 

```python
from modelcluster.fields import ParentalKey

from wagtail.models import Page, Orderable
from wagtail.fields import RichTextField
from wagtail.admin.panels import FieldPanel, InlinePanel
from wagtail.search import index

class BlogPage(Page):
    date = models.DateField("Post date")
    intro = models.CharField(max_length=250)
    body = RichTextField(blank=True)

    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        FieldPanel('date'),
        FieldPanel('intro'),
        FieldPanel('body'),

        # Add this:
        InlinePanel('gallery_images', label="Gallery images"),
    ]


class BlogPageGalleryImage(Orderable):
    page = ParentalKey(BlogPage, on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        FieldPanel('image'),
        FieldPanel('caption'),
    ]
```
4. Run server (also at makemigrations)
5. ANd received the following error: AttributeError: 'InlinePanel' object has no attribute 'field_name'

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes. The problem is reproduced on the latest version of wagtail.

### Technical details

-   Python version: Python 3.9.5
-   Django version: Django>=4.2,<5.1
-   Wagtail version: Wagtail v5.2.3
-   Browser version: Google Chrome 121.0.6167.85, (64 bit)

### Working on this

I just started learning Wagtail, I don't have enough knowledge yet to fix this error. 
But it seems to me that you just need to add the lost field_name attribute to the class InlinePanel

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by Jaivignesh-afk** [comment]
I am working on this

**Comment by gasman** [comment]
@p-p-a-83 Are you sure you added the `InlinePanel` line to the `content_panels` list? From the stack trace, it looks like you might have added it to `search_fields` instead.

**Comment by gasman** [comment]
Closing due to lack of response - I'm assuming the problem was indeed due to adding the panel to `search_fields`.
