### ISSUE TITLE
Wagtail build/install issue

### ISSUE THREAD

**Issue by eliasfinn251** [wagtail/wagtail#11845]
### Issue Summary
I'd like to build and install wagtail from source. When I do ./setup.py I get error message :
Traceback (most recent call last):
  File "/mnt/d_drive/var_docs_complements/open-source-contribs/wagtail/./mysetup.py", line 81, in <module>
    setup(
  File "/home/ainaf/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 102, in setup
    _install_setup_requires(attrs)
  File "/home/ainaf/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 70, in _install_setup_requires
    dist = MinimalDistribution(attrs)
  File "/home/ainaf/.local/lib/python3.10/site-packages/setuptools/__init__.py", line 52, in __init__
    super().__init__(filtered)
  File "/home/ainaf/.local/lib/python3.10/site-packages/setuptools/dist.py", line 297, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1021, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 459, in load
    ordered = sorted(eps, key=by_group)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 1018, in <genexpr>
    eps = itertools.chain.from_iterable(
  File "/usr/lib/python3.10/importlib/metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 943, in _normalized_name
    or super()._normalized_name
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 622, in _normalized_name
    return Prepared.normalize(self.name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 871, in normalize
    return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
You do not need to run setup.py to install Wagtail from source - please see the instructions at https://docs.wagtail.org/en/stable/contributing/developing.html.
