### ISSUE TITLE
Saving a page draft or publishing raises `django.utils.datastructures.MultiValueDictKeyError: 'body-count' error

### ISSUE THREAD

**Issue by Grustamli** [wagtail/wagtail#11920]
### Issue Summary

When I save any page by clicking "save draft" or "publish"  `django.utils.datastructures.MultiValueDictKeyError: 'body-count` error is raised. This happened after I upgraded from 6.0 to 6.1. Below is the stack trace

```bash
Internal Server Error: /en/admin/pages/148/edit/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/utils/datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'body-count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wagtail/admin/urls/__init__.py", line 178, in wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wagtail/admin/auth.py", line 151, in decorated_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wagtail/admin/views/pages/edit.py", line 393, in dispatch
    return super().dispatch(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wagtail/admin/views/pages/edit.py", line 475, in post
    if self.form.is_valid() and not self.locked_for_user:
       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wagtail/admin/forms/pages.py", line 192, in is_valid
    return super().is_valid()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/modelcluster/forms.py", line 343, in is_valid
    form_is_valid = super().is_valid()
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 192, in errors
    self.full_clean()
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 327, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 334, in _clean_fields
    value = bf.initial if field.disabled else bf.data
                                              ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/boundfield.py", line 136, in data
    return self.form._widget_data_value(self.field.widget, self.html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 216, in _widget_data_value
    return widget.value_from_datadict(self.data, self.files, html_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wagtail/blocks/base.py", line 613, in value_from_datadict
    return self.block_def.value_from_datadict(data, files, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wagtail/blocks/stream_block.py", line 112, in value_from_datadict
    count = int(data["%s-count" % prefix])
                ~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/utils/datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'body-count'
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
    No

### Technical details

-   Python version: Run `python --version`.
    `3.11.1`

-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
    `5.0.4`
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
    `6.1`
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
    Chrome 123

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by laymonage** [comment]
Hey, thanks for the report! This sounds like an error that happens when the client-side code fails to load a StreamField. Have you run `python manage.py collectstatic` after upgrading? Did you see any errors in the browser console?

**Comment by Grustamli** [comment]
Thanks @laymonage  and @gasman . This was it. `python manage.py collectstatic` resolved it. Sorry for the false alarm.
