### ISSUE TITLE
Wagtail 6.2rc1 - Migration issue

### ISSUE THREAD

**Issue by cyface** [wagtail/wagtail#12164]
### Issue Summary

Wagtail 6.2rc1, `python manage.py migrate`.  Looks like while doing something with users in the migrations, something is breaking.
 
Here is the stack trace:

```
(.venv) % python manage.py migrate   
Operations to perform:
  Apply all migrations: accounts, admin, ai, articles, auth, authors, awards, banking, brokerages, calculators, contenttypes, conversions, creditcards, cryptocurrency, db, django_rq, ecap, insurance, loans, marketing, mortgages, pages, personalfinance, press, quizzes, research, sessions, shopping, sites, smallbusiness, snippetfinder, student_loans, taggit, taxes, wagtail_ai, wagtail_content_import, wagtail_transfer, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailusers
Traceback (most recent call last):
  File "/Users/twhite/PycharmProjects/the-ascent/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 302, in handle
    pre_migrate_apps = pre_migrate_state.apps
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 566, in apps
    return StateApps(self.real_apps, self.models)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 627, in __init__
    self.render_multiple([*models.values(), *self.real_models])
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 665, in render_multiple
    model.render(self)
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 949, in render
    body = {name: field.clone() for name, field in self.fields.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/db/migrations/state.py", line 949, in <dictcomp>
    body = {name: field.clone() for name, field in self.fields.items()}
                  ^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 665, in clone
    name, path, args, kwargs = self.deconstruct()
                               ^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/wagtail/fields.py", line 169, in deconstruct
    block_types = [
                  ^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/wagtail/fields.py", line 170, in <listcomp>
    (name, lookup.add_block(block))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/wagtail/blocks/definition_lookup.py", line 70, in add_block
    deconstructed = block.deconstruct_with_lookup(self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/wagtail/blocks/struct_block.py", line 326, in deconstruct_with_lookup
    [
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/wagtail/blocks/struct_block.py", line 327, in <listcomp>
    (name, lookup.add_block(block))
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/wagtail/blocks/definition_lookup.py", line 70, in add_block
    deconstructed = block.deconstruct_with_lookup(self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/twhite/PycharmProjects/the-ascent/.venv/lib/python3.11/site-packages/wagtail/blocks/list_block.py", line 407, in deconstruct_with_lookup
    if isinstance(args[0], Block):
                  ~~~~^^^
IndexError: tuple index out of range
```

**Comment by cyface** [comment]
@gasman Not that I can find.  Here's the ListBlock extensions we are doing:

```
class ActionTileListBlock(ListBlock):
    """
    NO LONGER USED
    """

    def __init__(self, **kwargs):
        # ListBlock wants to be passed in a block type to make a list of
        super().__init__(ActionTileBlock, **kwargs)

    class Meta:
        icon = "list-ul"

class BioListBlock(ListBlock):
    """
    List of Team Bios
    """

    def __init__(self, **kwargs):
        # ListBlock wants to be passed in a block type to make a list of
        super().__init__(BioBlock, **kwargs)
        
        
class QAListBlock(ListBlock):
    """
    Block for a list of question/answer blocks
    """

    def __init__(self, **kwargs):
        # ListBlock wants to be passed in a block type to make a list of
        super().__init__(QABlock, **kwargs)

    class Meta:
        icon = "list-ul"
        admin_text = mark_safe("<b>QA List</b>")
        help_text = "List of Questions and Answers (Also generates Google FAQ schema)"
        label = "QA List"
        template = "pages/blocks/qa_list.html"

class AccordionBlock(ListBlock):
    """
    Block for a list of question/answer blocks
    """

    def __init__(self, **kwargs):
        # ListBlock wants to be passed in a block type to make a list of
        super().__init__(AccordionItemBlock, **kwargs)

    class Meta:
        icon = "list-ul"
        admin_text = mark_safe("<b>Accordion</b>")
        help_text = "Choose what to show on page, vs hide"
        label = "Accordion"
        template = "pages/blocks/accordion_list.html"

```

**Comment by gasman** [comment]
Ah yep, I see the problem - your `__init__` methods change the signature of the block away from what the base `ListBlock` is expecting. This wasn't a problem with the old migration logic, because (unlike StructBlock and StreamBlock) ListBlock didn't have any special handling of subclasses and just kept hold of the args/kwargs to return them unchanged when writing the migration - but the new logic expects to see the child block definition in there.

ListBlock isn't designed with subclassing in mind, but there's no fundamental reason why it shouldn't be valid, so I'll try and come up with a fix for this. For now, you should be able to work around this by adding the following methods to each class:

    @classmethod
    def construct_from_lookup(cls, lookup, *args, **kwargs):
        return cls(*args, **kwargs)

    def deconstruct_with_lookup(self, lookup):
        return self.deconstruct()

**Comment by cyface** [comment]
Thanks! Migrations ran fine with those new methods added. No worries on my part if adding those is just part of the release notes upgrade process.

**Comment by dkirkham** [comment]
FYI @gasman, I tripped into this problem too while trying out 6.2rc1, as I have two subclassed `ListBlock`s. I substituted the new `list_block.py` from #12168 and the migration worked fine.
