### ISSUE TITLE
Search broken on page listing

### ISSUE THREAD

**Issue by tandrieuxx** [wagtail/wagtail#12177]
### Issue Summary

We have a custom Page-inherited model called Campaign and we're unable to perform a search on its IndexView, because of this kind of error : 

```
Internal Server Error: /admin/campaigns/results/
Traceback (most recent call last):
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = middleware_method(
  File "/home/theo/workspace/rgive/src/rgive/back/middleware.py", line 39, in process_view
    return login_required(view_func, redirect_field_name=None)(
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 178, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/admin/auth.py", line 151, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/admin/views/generic/permissions.py", line 31, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/admin/views/pages/listing.py", line 186, in get
    return super().get(request)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/django/views/generic/list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/admin/views/generic/models.py", line 202, in get_queryset
    queryset = self.search_queryset(queryset)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/admin/views/pages/listing.py", line 270, in search_queryset
    queryset = queryset.autocomplete(
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/queryset.py", line 37, in autocomplete
    return search_backend.autocomplete(
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/backends/base.py", line 498, in autocomplete
    return self._search(
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/backends/base.py", line 464, in _search
    search_query_compiler.check()
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/backends/base.py", line 262, in check
    self._get_filters_from_where_node(self.queryset.query.where, check_only=True)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/backends/base.py", line 190, in _get_filters_from_where_node
    child_filters = [
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/backends/base.py", line 191, in <listcomp>
    self._get_filters_from_where_node(child)
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/backends/base.py", line 178, in _get_filters_from_where_node
    return self._process_filter(
  File "/home/theo/workspace/rgive/venv/lib/python3.10/site-packages/wagtail/search/backends/base.py", line 80, in _process_filter
    raise FilterFieldError(
wagtail.search.backends.base.FilterFieldError: Cannot filter search results with field "depth". Please add index.FilterField('depth') to Campaign.search_fields.
[26/Jul/2024 16:00:19] "GET /admin/campaigns/results/?q=ds&status=live&status=draft&created_at_after=&created_at_before=&latest_revision_created_at_after=&latest_revision_created_at_before=&last_published_at_after=&last_published_at_before=&expire_at_after=&expire_at_before=&translation= HTTP/1.1" 500 245948
```

### Steps to Reproduce

Create a model inheriting Page with some non-string fields, then a PageListingViewSet.
Go to the IndexView, start typing in the search bar.
The server error above pops up.

Additionnaly we have a custom PageIndexView but removing it doesn't solve the issue. We also have some `search_fields` defined, at first in the ViewSet, then I tried to move them in the model, then to remove them completely, but I get the same error.

I tried to do as the error suggested, adding index.FilterField('depth') in the model's `search_fields` list, but then the same error occurs with a different field name, so I did the same with every field causing the error. I ended up with no error but a non-functional search (no results returned no matter what I type), and a list of `search_fields` that doesn't make any sense, with wagtail-native fields like `depth`, `live` or `has_unpublished_changed` and one of our own datetime field.

```
search_fields = [
        index.FilterField("uuid"),
        index.FilterField("title"),
        index.FilterField("admin_title"),
        index.FilterField("admin_description"),
        index.FilterField("code"),
        index.FilterField("depth"),
        index.FilterField("live"),
        index.FilterField("completed_at"),
        index.FilterField("expired"),
        index.FilterField("has_unpublished_changes"),
    ]
```

When debugging a bit, I could see that `wagtail.search.backends.BaseSearchQueryCompiler.check` calls `self._get_filters_from_where_node(self.queryset.query.where, check_only=True)` and I don't really understand why it does that, the 'where' node of the queryset contains indeed some conditions on those problematic fields but it should not interfere with the search.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.10
-   Django version: 4.2.14
-   Wagtail version: 6.1.3
-   Browser version: Chrome 126

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by gasman** [comment]
As per [the documentation for `search_fields`](https://docs.wagtail.org/en/stable/topics/search/indexing.html#indexing-extra-fields), it's recommended that you define `search_fields` for a Page model by appending to `Page.search_fields`:

    search_fields = Page.search_fields + [
        ...
    ]

The search bar in the admin is an autocompletion search, so `search_fields` must include at least one `AutocompleteField` for it to return results. The base Page model includes one for the `title` field, so defining `search_fields` as above should fix this (although you may need to re-run `./manage.py update_index` for it to take effect).
