### ISSUE TITLE
LookupError: App 'accounts' doesn't have a 'CustomUser' model.

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#12228]
Hi,

I am trying to upgrade wagtail from 6.1.3 to 6.2, but I got the following error:
```
Traceback (most recent call last):
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\django\apps\config.py", line 235, in get_model
    return self.models[model_name.lower()]
KeyError: 'customuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\django\contrib\auth\__init__.py", line 188, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\django\apps\registry.py", line 213, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\django\apps\config.py", line 237, in get_model
    raise LookupError(
LookupError: App 'accounts' doesn't have a 'CustomUser' model.
```

I have created a custom user model in accounts app.
```
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    salutation = models.CharField(max_length=20, blank=True, null=True)
    company_name = models.CharField(max_length=255, blank=True, null=True)
    company_id = models.PositiveIntegerField(blank=True, null=True)

```

and in base.py file:
```
INSTALLED_APPS = [
    'accounts',
    'wagtail.users',
    ....
]
AUTH_USER_MODEL = 'accounts.CustomUser'
```

It works well with wagtail 6.1.3 and django 5.0.8. Please help!

**Comment by aliceni81** [comment]
I found the reason that I used "from wagtail.admin.filters import WagtailFilterSet"

 ```
File "D:\Users\ani\Documents\cms\app\categories\models.py", line 4, in <module>
    from wagtail.admin.filters import WagtailFilterSet
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\wagtail\admin\filters.py", line 9, in <module>
    from wagtail.admin.models import popular_tags_for_model
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\wagtail\admin\models.py", line 77, in <module>
    class EditingSession(models.Model):
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\wagtail\admin\models.py", line 79, in EditingSession
    get_user_model(),
  File "D:\Users\ani\Documents\cms\venv\lib\site-packages\django\contrib\auth\__init__.py", line 194, in get_user_model
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'accounts.CustomUser' that has not been installed
```

**Comment by gasman** [comment]
I'm 99% sure #12231 will fix this, but can always reopen later if not.
