### ISSUE TITLE
Manually modifying the StreamField's data crashes with TypeError

### ISSUE THREAD

**Issue by th3hamm0r** [wagtail/wagtail#12320]
### Issue Summary

Modifying the StreamField's data of a model (like documented [here](https://docs.wagtail.org/en/stable/topics/streamfield.html#modifying-streamfield-data)), which is part of the reference index, leads to an error. E.g. in the bakerydemo, executing the following in a admin view, would result in the error below:
```
>>> l = LocationPage.objects.first()
>>> l.body.append(("heading_block", {"heading_text": "text"}))
>>> l.save(update_fields=["body"])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/models/__init__.py", line 1531, in save
    result = super().save(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/modelcluster/models.py", line 202, in save
    super().save(update_fields=real_update_fields, **kwargs)
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/signal_handlers.py", line 91, in update_reference_index_on_save
    ReferenceIndex.create_or_update_for_object(instance)
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/models/reference_index.py", line 430, in create_or_update_for_object
    references = set(cls._extract_references_from_object(object))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/models/reference_index.py", line 363, in _extract_references_from_object
    yield from (
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/models/reference_index.py", line 363, in <genexpr>
    yield from (
               ^
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/fields.py", line 249, in extract_references
    yield from self.stream_block.extract_references(value)
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/blocks/stream_block.py", line 397, in extract_references
    for child in value:
  File "<frozen _collections_abc>", line 993, in __iter__
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/blocks/stream_block.py", line 680, in __getitem__
    self._prefetch_blocks(raw_value["type"])
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/blocks/stream_block.py", line 710, in _prefetch_blocks
    raw_values = OrderedDict(
                 ^^^^^^^^^^^^
  File "/***/tmp/bakerydemo-6.2/venv/lib/python3.11/site-packages/wagtail/blocks/stream_block.py", line 713, in <genexpr>
    if raw_item["type"] == type_name and self._bound_blocks[i] is None
       ~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

The problem is, that appending the item calls `insert()`, which adds `None` to the `_raw_data` [here](https://github.com/wagtail/wagtail/blob/bd90802877921ae34d369eddc21f298349894c7d/wagtail/blocks/stream_block.py#L693).
Saving the model then triggers the [signal handler](https://github.com/wagtail/wagtail/blob/93b9c04ce75ad8581852ef1d669ce43455e83454/wagtail/signal_handlers.py#L65) to update the reference index, which leads to the call of `_prefetch_blocks()`, which crashes [here](https://github.com/wagtail/wagtail/blob/bd90802877921ae34d369eddc21f298349894c7d/wagtail/blocks/stream_block.py#L713), since the added item in `_raw_data` is unexpectedly `None`.

In our case finding the issue was a bit tricky, since testing it in a plain django shell did not result in the error, because the viewsets haven't been fully initialized then. In our shell we also had to call the following, to really simulate the environment similar to the admin view:
```
from wagtail.admin.viewsets import viewsets
viewsets.populate()  # after that, the reference index is populated
```
In the shell of the bakerydemo this wasn't necessary, the code crashes without that.

### Steps to Reproduce

1. Install the [bakerydemo](https://github.com/wagtail/bakerydemo)
2. Open the django shell (`./manage.py shell`)
3. Execute:
```python
from bakerydemo.locations.models import LocationPage
l = LocationPage.objects.first()
l.body.append(("heading_block", {"heading_text": "text"}))
l.save(update_fields=["body"])  # this will result in the "TypeError: 'NoneType' object is not subscriptable"
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

-   Python version: 3.11
-   Django version: 4.2, 5.0
-   Wagtail version: 5.2.6, 6.2.1

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by th3hamm0r** [comment]
Looking at Wagtail's code again, I think I know how this could be solved:
https://github.com/wagtail/wagtail/blob/bd90802877921ae34d369eddc21f298349894c7d/wagtail/blocks/stream_block.py#L710-L714

Actually we could just change the `if`-condition to `raw_item and raw_item["type"] == type_name and self._bound_blocks[i] is None`, so we would skip the manually inserted item for the prefetch-operation. I think the inserted manually inserted data must already contain "resolved" data, so no prefetching is necessary here.
