### ISSUE TITLE
Streamfield migrations fail on revisions that don't have target field

### ISSUE THREAD

**Issue by jams2** [wagtail/wagtail#12408]
### Issue Summary

`wagtail.blocks.migrations.migrate_operation.MigrateStreamData` does not gracefully handle revisions that do not contain the field that is being operated on. This may occur when running a migration on a model that has revisions from before the creation of the field on the model. We do support limiting which revisions to operate on by date, but we should also gracefully handle this scenario (by doing nothing if the field does not exist in a given revision).

### Impact

Prevents migrations from being successfully run.

### Steps to Reproduce

1. Start a new Wagtail project
2. makemigrations, migrate, createsuperuser
3. Save a revision of the homepage
4. Add a "body" StreamField to the homepage
5. makemigrations
6. Create an empty migration in the home app
7. Add a streamfield data migration operation that operates on the newly added "body" field

```python
# Generated by Django 4.2.16 on 2024-10-12 10:51

from django.db import migrations
from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import AlterBlockValueOperation

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        MigrateStreamData(
            "home",
            "homepage",
            "body",
            [
                (AlterBlockValueOperation("Hello world"), "text")
            ]
        )
    ]
```

8. Run the migrations

```sh
gitpod /workspace/wagtail-gitpod (main) $ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, home, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailusers
Running migrations:
  Applying home.0003_homepage_body... OK
  Applying home.0004_auto_20241012_1051...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/wagtail/blocks/migrations/migrate_operation.py", line 159, in migrate_stream_data_forward
    raw_data = json.loads(revision.content[self.field_name])
KeyError: 'body'
```

https://github.com/wagtail/wagtail/blob/309e47f0ccb19dba63aaa64d52914e87eef390dc/wagtail/blocks/migrations/migrate_operation.py#L159

### Technical details

-   Python version: 3.8.12
-   Django version: 4.2.16
-   Wagtail version: 6.2.2

**Comment by apokaikun** [comment]
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/src/app/manage.py", line 22, in <module>
web-1  |     main()
web-1  |     ~~~~^^
web-1  |   File "/usr/src/app/manage.py", line 18, in main
web-1  |     execute_from_command_line(sys.argv)
web-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
web-1  |     utility.execute()
web-1  |     ~~~~~~~~~~~~~~~^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/__init__.py", line 436, in execute
web-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 413, in run_from_argv
web-1  |     self.execute(*args, **cmd_options)
web-1  |     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 459, in execute
web-1  |     output = self.handle(*args, **options)
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/base.py", line 107, in wrapper
web-1  |     res = handle_func(*args, **kwargs)
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/core/management/commands/migrate.py", line 357, in handle
web-1  |     post_migrate_state = executor.migrate(
web-1  |         targets,
web-1  |     ...<3 lines>...
web-1  |         fake_initial=fake_initial,
web-1  |     )
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/migrations/executor.py", line 135, in migrate
web-1  |     state = self._migrate_all_forwards(
web-1  |         state, plan, full_plan, fake=fake, fake_initial=fake_initial
web-1  |     )
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
web-1  |     state = self.apply_migration(
web-1  |         state, migration, fake=fake, fake_initial=fake_initial
web-1  |     )
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
web-1  |     state = migration.apply(state, schema_editor)
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/migrations/migration.py", line 132, in apply
web-1  |     operation.database_forwards(
web-1  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
web-1  |         self.app_label, schema_editor, old_state, project_state
web-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |     )
web-1  |     ^
web-1  |   File "/usr/local/lib/python3.13/site-packages/django/db/migrations/operations/special.py", line 196, in database_forwards
web-1  |     self.code(from_state.apps, schema_editor)
web-1  |     ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.13/site-packages/wagtail/blocks/migrations/migrate_operation.py", line 159, in migrate_stream_data_forward
web-1  |     raw_data = json.loads(revision.content[self.field_name])
web-1  |                           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
web-1  | KeyError: 'partners'

**Comment by apokaikun** [comment]
```
MigrateStreamData(
            app_name="cms",
            model_name="PartnerPage",
            field_name="partners",
            operations_and_block_paths=[
                (
                    RenameStructChildrenOperation(
                        old_name="alt_text", new_name="image_description"
                    ),
                    "partners.logos_groups.item.logos.item",
                )
            ],
            # revisions_from=datetime.date(2024, 10, 16),
        ),
```
