### ISSUE TITLE
Avoid setting a locale as part of loaddata (Locale.DoesNotExist)

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#12469]
### Issue Summary

Originally from #8097 - When running manage.py loaddata setting locale to Locale.get_default() is wrong.

> There is no reason at all the locale is not also in the database dump and setting it to `Locale.get_default()` is completely random and more likely than not wrong.
> We get the following error because at the point this code is called, the default locale does not exist yet:

```
wagtail.core.models.i18n.Locale.DoesNotExist: Problem installing fixture '/tmp/db.json': Locale matching query does not exist.
```

Full stacktrace:

```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    sys.exit(main())
  File "main.py", line 9, in main
    execute_from_command_line(sys.argv)
  File "django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "django/core/management/commands/loaddata.py", line 163, in loaddata
    self.load_label(fixture_label)
  File "django/core/management/commands/loaddata.py", line 253, in load_label
    if self.save_obj(obj):
  File "django/core/management/commands/loaddata.py", line 209, in save_obj
    obj.save(using=self.using)
  File "django/core/serializers/base.py", line 288, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "django/db/models/base.py", line 861, in save_base
    pre_save.send(
  File "django/dispatch/dispatcher.py", line 176, in send
    return [
  File "django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "wagtail/models/i18n.py", line 485, in set_locale_on_new_instance
    instance.locale = Locale.get_default()
  File "wagtail/models/i18n.py", line 63, in get_default
    return cls.objects.get_for_language(settings.LANGUAGE_CODE)
  File "wagtail/models/i18n.py", line 36, in get_for_language
    return self.get(
  File "django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
wagtail.models.i18n.Locale.DoesNotExist: Problem installing fixture '/tmp/db.json': Locale matching query does not exist.
```

### Steps to Reproduce

Unknown

### Technical details

-   Python version: Run `python --version`.
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

### Working on this

This Django documentation describes the situation, and might be nice to have as reference: [How fixtures are saved to the database?](https://docs.djangoproject.com/en/5.1/topics/db/fixtures/#how-fixtures-are-saved-to-the-database). There may be a lot of code to reuse from #8097, which had started and stalled.

Further feedback on the PR:

> The default Locale should be created by [the migrations](https://github.com/wagtail/wagtail/blob/main/wagtail/migrations/0054_initial_locale.py) and it should pick this up when you load your fixtures.
> This may not be the case if you've changed the LANGUAGE_CODE setting after running migrations and before loading data or if you've flushed the database. Please could you confirm if you have done either of these?
> There is no reason at all the locale is not also in the database dump and setting it to Locale.get_default() is completely random and more likely than not wrong.
>  If your data does not have a locale, I think it's sensible that Wagtail picks a default for you as it's a required field. Loading fixtures is very much a developer-only feature so I think it's reasonable to expect developers to set this to the correct locale after import if needed.

The next step is – we need:

> more info and why you see the current behaviour as conflicting with Django's way of doing things.

**Comment by RealOrangeOne** [comment]
I've hit this issue myself, and opened a new PR #12649. 

The location this hit me is `TransactionTestCase`, which can optionally serialize and re-apply data using fixtures in between each test case. This is needed so models created in migrations are persisted, since `TransactionTestCase` truncates tables by default.

When that happens, the locale is often not created before a model which needs it, and so results in an error from the signal. 

Generally, I've found the solution to this to be not doing things like this during fixture loads, and assuming the fixture itself is complete.

**Comment by berry** [comment]
I am running into the same issue. Created a 'dumpdata' in production and trying to load it in development. Flushed the database first. Getting this error while loading the fixtures: `wagtail.models.i18n.Locale.DoesNotExist: Problem installing fixture '/backup/xxxxxxx.json.gz': Locale matching query does not exist.`

Is there a workaround for now?

**Comment by SebCorbin** [comment]
I also ran into this issue, I ended up disconnecting the signal in my test runner

**Comment by gasman** [comment]
Fixed in #12649
