### ISSUE TITLE
CloudFront cache invalidation fails

### ISSUE THREAD

**Issue by davidu1975** [wagtail/wagtail#12538]
### Issue Summary

Cloud Front Cache invalidation fails with error 
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter InvalidationBatch.Paths.Items, value: {'our-file'}, type: <class 'set'>, valid types: <class 'list'>, <class 'tuple'>

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
3. ...

use CF Cache Invalidation config
Publish / Unpublish page

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no) yes

### Technical details

-   Python version: Run `python --version`. 3.9.13
-   Django version: Look in your requirements.txt, or run `pip show django | grep Version`. 4.2.16
-   Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`. 6.3
-   Browser version: You can use https://www.whatsmybrowser.org/ to find this out. Chrome 130

### Working on this

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.

**Comment by RealOrangeOne** [comment]
Could you post which version of `boto3` and `botocore` you are running? It's possible there are some type restrictions we weren't aware of from testing.

**Comment by davidu1975** [comment]
Hi Jake
boto3                                    1.35.54
botocore                                 1.35.54
latest versions - i did upgrade to see if this was the issue
works if you change set to list - could be dups

**Comment by auslaner** [comment]
I'm seeing this now as well after upgrading to wagtail 6.3.

My versions:
Wagtail==6.3
boto3==1.35.58
botocore==1.35.58 

```
Traceback (most recent call last):
  File "/tmp/redbuttegarden/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/admin/urls/__init__.py", line 172, in wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/admin/auth.py", line 151, in decorated_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/admin/views/pages/edit.py", line 396, in dispatch
    return super().dispatch(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/admin/views/pages/edit.py", line 479, in post
    return self.form_valid(self.form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/admin/views/pages/edit.py", line 505, in form_valid
    return self.publish_action()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/admin/views/pages/edit.py", line 577, in publish_action
    action.execute(skip_permission_checks=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/actions/publish_revision.py", line 231, in execute
    return self._publish_revision(
          
  File "/tmp/redbuttegarden/wagtail/actions/publish_revision.py", line 171, in _publish_revision
    self._after_publish()
    ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/actions/publish_page_revision.py", line 53, in _after_publish
    page_published.send(
    ^
  File "/tmp/redbuttegarden/django/dispatch/dispatcher.py", line 177, in send
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/contrib/frontend_cache/signal_handlers.py", line 8, in page_published_signal_handler
    purge_page_from_cache(instance)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/contrib/frontend_cache/utils.py", line 144, in purge_page_from_cache
    purge_pages_from_cache([page], backend_settings=backend_settings, backends=backends)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/contrib/frontend_cache/utils.py", line 153, in purge_pages_from_cache
    purge_urls_from_cache(urls, backend_settings, backends)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/contrib/frontend_cache/utils.py", line 132, in purge_urls_from_cache
    backend.purge_batch(urls)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/contrib/frontend_cache/backends/cloudfront.py", line 75, in purge_batch
    self._create_invalidation(distribution_id, paths)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/redbuttegarden/wagtail/contrib/frontend_cache/backends/cloudfront.py", line 84, in _create_invalidation
    self.client.create_invalidation(
    ^
  File "/var/task/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/task/botocore/client.py", line 919, in _make_api_call
    request_dict = self._convert_to_request_dict(
                  
  File "/var/task/botocore/client.py", line 990, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
                  
  File "/var/task/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: ParamValidationError at /admin/pages/790/edit/
Exception Value: Parameter validation failed:
Invalid type for parameter InvalidationBatch.Paths.Items, value: {'/donate/'}, type: <class 'set'>, valid types: <class 'list'>, <class 'tuple'>
Raised during: wagtail.admin.views.pages.edit.EditView
```

**Comment by auslaner** [comment]
A workaround for this ended up being not too difficult. I created this `custom_cache_backend.py` in my 'home' app:

```python
from wagtail.contrib.frontend_cache.backends import CloudfrontBackend


class CustomCloudfrontBackend(CloudfrontBackend):
    def _create_invalidation(self, distribution_id, paths):
        paths = tuple(paths)
        super()._create_invalidation(distribution_id, paths)
```

Then updated my WAGTAILFRONTENDCACHE setting to point to it:

```
WAGTAILFRONTENDCACHE = {
    'mainsite': {
        'BACKEND': 'home.custom_cache_backend.CustomCloudfrontBackend',
        'DISTRIBUTION_ID': 'XXX',
        'HOSTNAMES': ['redbuttegarden.org']
    },
    ...
}
```
