### ISSUE TITLE
Elasticsearch, wagtail rc1, KeyError: 'fields'

### ISSUE THREAD

**Issue by ser1us** [wagtail/wagtail#1449]
Good morning everyone!

We just encountered this error on our page after it ran for a few days. Now we get this error message:

```
2015-06-27T06:18:32.959395+00:00 app[web.1]: Traceback (most recent call last):
2015-06-27T06:18:32.959396+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
2015-06-27T06:18:32.959398+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2015-06-27T06:18:32.959400+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/wagtail/wagtailcore/views.py", line 25, in serve
2015-06-27T06:18:32.959401+00:00 app[web.1]:     return page.serve(request, *args, **kwargs)
2015-06-27T06:18:32.959402+00:00 app[web.1]:   File "/app/core/models/pages/rvbw_search_page.py", line 22, in serve
2015-06-27T06:18:32.959404+00:00 app[web.1]:     'search_results': search_results,
2015-06-27T06:18:32.959405+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
2015-06-27T06:18:32.959407+00:00 app[web.1]:     template_name, context, request=request, using=using)
2015-06-27T06:18:32.959408+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader.py", line 99, in render_to_string
2015-06-27T06:18:32.959410+00:00 app[web.1]:     return template.render(context, request)
2015-06-27T06:18:32.959411+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/backends/django.py", line 74, in render
2015-06-27T06:18:32.959413+00:00 app[web.1]:     return self.template.render(context)
2015-06-27T06:18:32.959414+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 209, in render
2015-06-27T06:18:32.959415+00:00 app[web.1]:     return self._render(context)
2015-06-27T06:18:32.959417+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
2015-06-27T06:18:32.959418+00:00 app[web.1]:     return self.nodelist.render(context)
2015-06-27T06:18:32.959419+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 903, in render
2015-06-27T06:18:32.959420+00:00 app[web.1]:     bit = self.render_node(node, context)
2015-06-27T06:18:32.959422+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
2015-06-27T06:18:32.959423+00:00 app[web.1]:     return node.render(context)
2015-06-27T06:18:32.959424+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 135, in render
2015-06-27T06:18:32.959425+00:00 app[web.1]:     return compiled_parent._render(context)
2015-06-27T06:18:32.959427+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 201, in _render
2015-06-27T06:18:32.959428+00:00 app[web.1]:     return self.nodelist.render(context)
2015-06-27T06:18:32.959429+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 903, in render
2015-06-27T06:18:32.959431+00:00 app[web.1]:     bit = self.render_node(node, context)
2015-06-27T06:18:32.959432+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
2015-06-27T06:18:32.959433+00:00 app[web.1]:     return node.render(context)
2015-06-27T06:18:32.959435+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
2015-06-27T06:18:32.959436+00:00 app[web.1]:     result = block.nodelist.render(context)
2015-06-27T06:18:32.959437+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 903, in render
2015-06-27T06:18:32.959439+00:00 app[web.1]:     bit = self.render_node(node, context)
2015-06-27T06:18:32.959440+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/base.py", line 917, in render_node
2015-06-27T06:18:32.959441+00:00 app[web.1]:     return node.render(context)
2015-06-27T06:18:32.959442+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/django/template/defaulttags.py", line 162, in render
2015-06-27T06:18:32.959444+00:00 app[web.1]:     len_values = len(values)
2015-06-27T06:18:32.959445+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/wagtail/wagtailsearch/backends/base.py", line 166, in __len__
2015-06-27T06:18:32.959446+00:00 app[web.1]:     return len(self.results())
2015-06-27T06:18:32.959448+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/wagtail/wagtailsearch/backends/base.py", line 129, in results
2015-06-27T06:18:32.959449+00:00 app[web.1]:     self._results_cache = self._do_search()
2015-06-27T06:18:32.959450+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 279, in _do_search
2015-06-27T06:18:32.959452+00:00 app[web.1]:     pks = [hit['fields']['pk'][0] for hit in hits['hits']['hits']]
2015-06-27T06:18:32.959453+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.4/site-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 279, in <listcomp>
2015-06-27T06:18:32.959454+00:00 app[web.1]:     pks = [hit['fields']['pk'][0] for hit in hits['hits']['hits']]
2015-06-27T06:18:32.959456+00:00 app[web.1]: KeyError: 'fields'
```

We overwrote the serve method on the rvbw_search_page.py page.

It looks like this:

```
    def serve(self, request, *args, **kwargs):
        search_query = request.POST.get('query', None)
        if search_query:
            search_results = Page.objects.not_type(RVBWNavigationPage).live().search(search_query)
            query = Query.get(search_query)

            # Record hit
            query.add_hit()

            return render(request, self.template, {
                'self': self,
                'search_query': search_query,
                'search_results': search_results,
            })
        else:
            return super(RVBWSearchPage, self).serve(request)
```

After running `python manage.py update_index` the problem is gone. Am I missing a configuration option ?

My config looks like this:

```
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch.ElasticSearch',
        'URLS': os.environ.get('ELASTIC_BACKEND_URL').split(','),
        'INDEX': os.environ.get('ELASTIC_INDEX'),
        'TIMEOUT': 5,
    }
}
```

where ELASTIC_BACKEND_URL is configured and ELASTIC_INDEX as well.

Any help is much appreciated. Thank you!

Best regards,
Christoph

**Comment by kaedroho** [comment]
Thanks for reporting @ser1us

This is an issue I've come across before. I haven't yet found out why Elasticsearch forgets the fields but, as you said, rerunning ``update_index`` seems to fix it.

**Comment by frague59** [comment]
I've had the same issue, due to mismatched version of elasticsearch-py lib and AWS elasticsearch itself.
I"m using a 1.7.x elasticsearch, I've installed the 1.7 version of elasticsearch-py which have fixed the issue.

**Comment by ser1us** [comment]
I don't believe this issue has any relevance anymore :) We switched to the postgresql search a long time ago. Thanks for all the hard work!
