### ISSUE TITLE
RoutablePage breaks update_index for elasticsearch

### ISSUE THREAD

**Issue by nadersoliman** [wagtail/wagtail#3215]
Inheriting from `RoutablePage` breaks the command `update_index` when integrating with elastic search with the following traceback

```
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 120, in handle
    self.update_backend(backend_name, schema_only=options['schema_only'])
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 77, in update_backend
    index.add_model(model)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/backends/elasticsearch2.py", line 113, in add_model
    index=self.name, doc_type=mapping.get_document_type(), body=mapping.get_mapping(),
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 62, in get_document_type
    return self.model.indexed_get_content_type()
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/index.py", line 34, in indexed_get_content_type
    parent_content_type = parent.indexed_get_content_type()
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/index.py", line 29, in indexed_get_content_type
    content_type = (cls._meta.app_label + '_' + cls.__name__).lower()
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### Steps to Reproduce

1. Integrate elastic search as your search backend
2. Create a Page model that inherits from `RoutablePage` call it `BasePage`
3. Patch `/site-packages/wagtail/wagtailsearch/index.py:indexed_get_content_type` with 
` print('meta:{}, meta.app_label:{} name:{}'.format(cls._meta, cls._meta.app_label, cls.__name__))`
4. run `update_index`
5. you will get something like
```
meta:common.basepage, meta.app_label:common name:BasePage
meta:None.routablepage, meta.app_label:None name:RoutablePage
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 120, in handle
    self.update_backend(backend_name, schema_only=options['schema_only'])
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 77, in update_backend
    index.add_model(model)
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/backends/elasticsearch2.py", line 113, in add_model
    index=self.name, doc_type=mapping.get_document_type(), body=mapping.get_mapping(),
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 62, in get_document_type
    return self.model.indexed_get_content_type()
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/index.py", line 34, in indexed_get_content_type
    parent_content_type = parent.indexed_get_content_type()
  File "/Users/nader/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail/wagtailsearch/index.py", line 29, in indexed_get_content_type
    content_type = (cls._meta.app_label + '_' + cls.__name__).lower()
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### Technical details

* Python version: 3.5.2
* Django version: 1.10.3
* Wagtail version: 1.7

**Comment by gasman** [comment]
Hi @nadersoliman,
It looks like you need to add `wagtail.contrib.wagtailroutablepage` to `INSTALLED_APPS` - without that, the `RoutablePage` model doesn't belong to a recognised app.

(The docs for wagtailroutablepage don't mention the need to update `INSTALLED_APPS` - but actually that's correct, because the docs only cover `RoutablePageMixin`, not `RoutablePage`. `RoutablePageMixin` _does_ work without the addition to `INSTALLED_APPS`, because it's an ordinary Python class, not a Django model.)
