### ISSUE TITLE
Exception if I compare revisions which include PageChooserBlock() and pageurl

### ISSUE THREAD

**Issue by Vorlif** [wagtail/wagtail#3352]
### Issue Summary

I'm not sure if this is a bug or if I've done something wrong.

If I want to compare two revisions of a page that has a StreamField with PageChooserBlock and a template which includes a  pageurl, I get alway an exception.

Maybe the issue dependt on #3340.

### Steps to Reproduce

1. You can use the example below (wagtail start mysite)
2. Create three pages
3. Add a StreamField 'link' from page one to page two
4. Save Draft
5. Change the link from page two to page three
6. Save Draft
7. Try to comapre the revisions 

#### Minimal example

```python
# models.py
from wagtail.wagtailcore.models import Page
from wagtail.wagtailcore import blocks
from wagtail.wagtailcore.fields import StreamField
from wagtail.wagtailadmin.edit_handlers import StreamFieldPanel

class LinkBlock(blocks.StructBlock):
    link = blocks.PageChooserBlock()

    class Meta:
        template = 'home/link.html'


class HomePage(Page):
    body = StreamField([
        ('link', LinkBlock())
    ],
        blank=True
    )

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```

```jinja
{# home_page.html #}

{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block content %}

    {% for block in page.body %}
        <p>{% include_block block %}</p>
    {% endfor %}

{% endblock %}
```

```jinja
{# link.html #}
{% load wagtailcore_tags %}

<a href="{% pageurl value.link %}">{{ value.link.title }}</a>
```

#### Traceback 

```bash
Error during template rendering

In template /path/to/mysite/home/templates/home/link.html, error at line 3
1	{% load wagtailcore_tags %}
2	
3	<a href="{% pageurl value.link %}">{{ value.link.title }}</a>
```

```bash
Internal Server Error: /admin/pages/3/revisions/compare/1...3/
Traceback (most recent call last):
  File "/path/to/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/path/to/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/path/to/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/path/to/env/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 24, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailadmin/views/pages.py", line 1136, in revisions_compare
    'comparison': comparison,
  File "/path/to/env/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/path/to/env/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/path/to/env/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 1044, in render
    output = self.filter_expression.resolve(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 915, in _resolve_lookup
    current = current()
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailadmin/compare.py", line 55, in htmldiff
    BeautifulSoup(force_text(self.val_a), 'html5lib').getText(),
  File "/path/to/env/lib/python3.5/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 380, in __str__
    return self.__html__()
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 377, in __html__
    return self.stream_block.render(self)
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/blocks/base.py", line 237, in render
    return self.render_basic(value, context=context)
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 229, in render_basic
    for child in value
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/blocks/stream_block.py", line 229, in <listcomp>
    for child in value
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/blocks/base.py", line 442, in render
    return self.block.render(self.value, context=context)
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/blocks/base.py", line 258, in render
    return mark_safe(render_to_string(template, new_context))
  File "/path/to/env/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/path/to/env/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/path/to/env/lib/python3.5/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/path/to/env/lib/python3.5/site-packages/wagtail/wagtailcore/templatetags/wagtailcore_tags.py", line 21, in pageurl
    return page.relative_url(context['request'].site)
  File "/path/to/env/lib/python3.5/site-packages/django/template/context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'request'

```

The exception only occurs if I try compare revision. The Page rendering has no problems.

### Technical details

* Python version: 3.5.3
* Django version: 1.10.5
* Wagtail version: 1.9rc1

**Comment by gasman** [comment]
Thanks for the report @Vorlif! I've confirmed that this is a Wagtail bug, and now pushed a fix as #3369.
