### ISSUE TITLE
ImportError: cannot import name 'flatatt'

### ISSUE THREAD

**Issue by AtomicSpark** [wagtail/wagtail#3526]
### Issue Summary

I've discovered that Wagtail [has been importing](https://github.com/wagtail/wagtail/search?q=flatatt) `flatatt` from the wrong location. `flatatt` can be found under `django.forms.utils`. This has been the location since at least [Django 1.8](https://github.com/django/django/blob/stable/1.8.x/django/forms/utils.py#L21) (I didn't bother checking unsupported versions). The current Wagtail code seems to have only worked because `flatatt` was imported by `django.forms.widgets` until [Django 1.11](https://github.com/django/django/blob/stable/1.10.x/django/forms/widgets.py#L13). In Django 1.11, it's [no longer imported](https://github.com/django/django/blob/stable/1.11.x/django/forms/widgets.py).

### Steps to Reproduce
```
mkvirtualenv wagtail-next
pip install wagtail
pip install django
python manage.py runserver
```

```
Traceback (most recent call last):
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/username/.virtualenvs/wagtail-next/lib/python3.5/site-packages/wagtail/wagtailimages/models.py", line 17, in <module>
    from django.forms.widgets import flatatt
ImportError: cannot import name 'flatatt'
```

### Technical details

* Python version: 3.5.3
* Django version: 1.11
* Wagtail version: 1.9
* Browser version: Chrome 57 (irrelevant)

**Comment by gasman** [comment]
Thanks for the report @AtomicSpark! Django 1.11 support in Wagtail is currently being finalised, and this has already been fixed in https://github.com/wagtail/wagtail/commit/7d8a1a0d1e37f0f8c614cba55bbdb7befee12d07.
