### ISSUE TITLE
1.9 → 1.10 DB migration raises AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by Karmak23** [wagtail/wagtail#3596]
### Issue Summary

1.9 → 1.10 DB migration raises `AttributeError: 'NoneType' object has no attribute 'find'`

### Steps to Reproduce

what I did :
```
pip install -U wagtail
./manage.py migrate
```
Cannot migrate. Website is stuck down, raising migration error on gunicorn start.

### Technical details

* Python 3.5.2
* Python/Django/Wagtail packages :
```
Django==1.11.1
django-appconf==1.0.2
django-compressor==2.1.1
django-el-pagination==3.0.1
django-extensions==1.7.8
django-modelcluster==3.1
django-taggit==0.22.1
django-treebeard==4.1.0
djangorestframework==3.6.3
wagtail==1.10
wagtail-nesting-box==0.2.1
wagtail-simple-gallery==0.3.6
wagtailatomicadmin==0.1.2
wagtailmedia==0.1.3
wagtailtinymce==4.2.1.5
```

### Stack Trace

```
(cocoliv.es) cocolives@cocoliv ~/cocolives @ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtail/wagtailadmin/checks.py", line 65, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(cls), WagtailAdminPageForm):
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 318, in get_form_class
    widgets=cls.widget_overrides())
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 65, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtail/wagtailadmin/forms.py", line 274, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/modelcluster/forms.py", line 192, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/forms/models.py", line 252, in __new__
    opts.field_classes)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/forms/models.py", line 170, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtail/wagtailadmin/forms.py", line 255, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtail/wagtailcore/fields.py", line 19, in formfield
    defaults = {'widget': get_rich_text_editor_widget(self.editor)}
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtail/wagtailadmin/rich_text.py", line 60, in get_rich_text_editor_widget
    return import_string(editor['WIDGET'])()
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtailtinymce/rich_text.py", line 66, in __init__
    self.kwargs = self.getDefaultArgs()
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/wagtailtinymce/rich_text.py", line 59, in getDefaultArgs
    'language': translation.to_locale(translation.get_language()),
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/utils/translation/__init__.py", line 207, in to_locale
    return _trans.to_locale(language)
  File "/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/django/utils/translation/trans_real.py", line 68, in to_locale
    p = language.find('-')
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by SalahAdDin** [comment]
WIll be good put in a warning section.

**Comment by edwilding** [comment]
For future readers that don't want to disable tinymce to perform migrations. 

The problem in `tinymce` is that a default language is not selected for the translation module tinymce is using. This can be fixed by sub-classing the `TinyMCERichTextArea` class and adding the necessary line in there:

```
from django.utils import translation
from wagtailtinymce.rich_text import TinyMCERichTextArea
from django.conf import settings

class CustomTinyMCE(TinyMCERichTextArea):
    def __init__(self, *args, **kwargs):
        translation.trans_real.activate(settings.LANGUAGE_CODE)
        super(CustomTinyMCE, self).__init__(*args, **kwargs)
```

In the settings you then need a LANGUAGE_CODE setting, and you need to point wagtail to use the subclass you just wrote:

```
LANGUAGE_CODE = 'en-uk'

WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'default': {
        'WIDGET': 'xxx.yyy.CustomTinyMCE'
    },
}
```

where xxx.yyy is that path to your class.

Once I had performed these steps I was able to migrate normally.
