### ISSUE TITLE
PROTECT on foreign keys corrupt page tree

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#3658]
## Issue Summary

At the moment, Wagtail has a warning (`wagtailcore.W001`) for developers who use `on_delete=models.CASCADE`. The warning gives the following hint:

> Set on_delete=models.SET_NULL and make sure the field is nullable or set on_delete=models.PROTECT. Wagtail does not allow simple database CASCADE because it will corrupt its tree storage.

But `on_delete=models.PROTECT` can also corrupt page tree on some scenarios.

There is a related issue: #1602, but it's more about support of protected foreign keys in the admin UI.

For now we should probably just display a warning for developers who use `on_delete=models.PROTECT`.

## Steps to Reproduce

The steps to reproduce section is based on models from wagtaildemo.

### Prepare your page tree

1. Checkout wagtaildemo repo and switch to the [`6eedaec`](https://github.com/wagtail/wagtaildemo/tree/6eedaec543554ab51f2e3cfc1c90948cf7f3fa14) commit (the following patch is based on this commit)
2. Apply the patch:

    ```diff
    diff --git a/demo/migrations/0007_eventindexpage_featured_event.py b/demo/migrations/0007_eventindexpage_featured_event.py
    new file mode 100644
    index 0000000..9d8af2a
    --- /dev/null
    +++ b/demo/migrations/0007_eventindexpage_featured_event.py
    @@ -0,0 +1,22 @@
    +# -*- coding: utf-8 -*-
    +# Generated by Django 1.10.7 on 2017-06-14 09:19
    +from __future__ import unicode_literals
    +
    +from django.db import migrations, models
    +import django.db.models.deletion
    +
    +
    +class Migration(migrations.Migration):
    +
    +    dependencies = [
    +        ('wagtailcore', '0034_page_live_revision'),
    +        ('demo', '0006_auto_20160902_1204'),
    +    ]
    +
    +    operations = [
    +        migrations.AddField(
    +            model_name='eventindexpage',
    +            name='featured_event',
    +            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page'),
    +        ),
    +    ]
    diff --git a/demo/models.py b/demo/models.py
    index cd96525..863d206 100644
    --- a/demo/models.py
    +++ b/demo/models.py
    @@ -522,6 +522,10 @@ class EventIndexPageRelatedLink(Orderable, RelatedLink):
    
     class EventIndexPage(Page):
         intro = RichTextField(blank=True)
    +    featured_event = models.ForeignKey('wagtailcore.Page', related_name='+', on_delete=models.PROTECT, blank=True,
    +                                       null=True, )
    +
    +    subpage_types = ['EventPage']
    
         search_fields = Page.search_fields + [
             index.SearchField('intro'),
    @@ -547,6 +551,7 @@ EventIndexPage.content_panels = [
         FieldPanel('title', classname="full title"),
         FieldPanel('intro', classname="full"),
         InlinePanel('related_links', label="Related links"),
    +    PageChooserPanel('featured_event', page_type='demo.EventPage'),
     ]
    
     EventIndexPage.promote_panels = Page.promote_panels
    ```
3. Setup the wagtaildemo site (see [the instructions](https://github.com/wagtail/wagtaildemo/tree/6eedaec543554ab51f2e3cfc1c90948cf7f3fa14) and run migrations)
4. Go to the admin UI and create a standard index page underneath the home page (let's call it "Page that will be deleted")
5. Underneath the "Page that will be deleted" page create an event index page (I'll call it "The page that will be orphaned")
6. Underneath the "The page that will be orphaned" page create an event page ("Test event page")
7. Now you should be able to add the "Test event page" as featured on the "The page that will be orphaned" event index page. Add and publish the changes

After the steps above you should have the following tree:

```
Homepage
- Page that will be deleted (Standard index page)
- - The page that will be orphaned (Event index page)
- - - Test event page (Event page)
```

### Break your tree

1. Try to delete the "The page that will be orphaned".

    As result you should get the `ProtectedError` exception:

    ```
    Cannot delete some instances of model 'Page' because they are referenced through a protected foreign key: 'EventIndexPage.featured_event'", <QuerySet [<EventIndexPage: The page that will be orphaned>]>)
    ```
    Congratulations, your page tree is now corrupted. The "Page that will be deleted" will have wrong `numchild` value. Here is an example:

    ```sql
    wagtaildemo=# select id, title, numchild, path from wagtailcore_page where path like '000100020006%' order by path;
     id |             title              | numchild |         path
    ----+--------------------------------+----------+----------------------
     24 | Page that will be deleted      |        0 | 000100020006
     25 | The page that will be orphaned |        1 | 0001000200060001
     26 | Test event page                |        0 | 00010002000600010001
    (3 rows)
    ```

    **Note:** At this step it's still possible to restore your page tree by running the `fixtree` command.

2. Go back to "Page that will be deleted" and check that there is no child pages in the admin UI.

### Make everything even worse

1. Now try to delete the "Page that will be deleted". It will be deleted without any issues.

2. Try to fix page tree using the `fixtree` command.

    Result:

    ```
    ./manage.py fixtree
    Orphaned pages found:
    ID 25: The page that will be orphaned
    ID 26: Test event page

    Delete these pages? [y/N] y

    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/mikalai/.virtualenvs/wagtail_dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
        utility.execute()
      File "/Users/mikalai/.virtualenvs/wagtail_dev/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/Users/mikalai/.virtualenvs/wagtail_dev/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/Users/mikalai/.virtualenvs/wagtail_dev/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
        output = self.handle(*args, **options)
      File "/Users/mikalai/Work/wagtail_dev/wagtail/wagtail/wagtailcore/management/commands/fixtree.py", line 83, in handle
        pages_to_delete.delete()
      File "/Users/mikalai/.virtualenvs/wagtail_dev/lib/python3.6/site-packages/django/db/models/query.py", line 608, in delete
        collector.collect(del_query)
      File "/Users/mikalai/.virtualenvs/wagtail_dev/lib/python3.6/site-packages/django/db/models/deletion.py", line 227, in collect
        field.remote_field.on_delete(self, field, sub_objs, self.using)
      File "/Users/mikalai/.virtualenvs/wagtail_dev/lib/python3.6/site-packages/django/db/models/deletion.py", line 28, in PROTECT
        sub_objs
    django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Page' because they are referenced through a protected foreign key: 'EventIndexPage.featured_event'", <QuerySet [<EventIndexPage: The page that will be orphaned>]>)
    ```

So it's only possible to fix page tree manually now.

## Technical details

* Python version: 3.6.1
* Django version: 1.10.*
* Wagtail version: 1.8-1.11 (tested in master on commit ed01d58)

I'm pretty sure the issue can be reproduced on other versions of Python, Django and Wagtail.

**Comment by gasman** [comment]
If I've understood correctly, the scenarios where `on_delete=models.PROTECT` is dangerous do not match the scenarios where `on_delete=models.CASCADE` is dangerous:

* `on_delete=models.PROTECT` fails in cases where you have a foreign key *to* a page model, and delete that page
* `on_delete=models.CASCADE` fails in cases where you have a foreign key *from* a page model to a related object (image, document, snippet, or another page) and delete that related object

This means that there are still legitimate (safe) uses for `PROTECT`, such as:

    class HomePage(Page):
        # don't allow hero image to be deleted while it's in use on the homepage
        hero_image = models.ForeignKey('wagtailimages.Image', related_name='+', on_delete=models.PROTECT)

which implies:

* we can't simply copy the existing warning logic for the `CASCADE` case (and to be fully correct, we need to check non-page models that might have foreign keys to Page, such as snippets, modeladmin and wagtail.contrib.settings)
* this doesn't put #1602 on hold completely; it's still desirable for us to catch these errors when deleting images / documents etc, and output a friendly error message.

**Comment by BertrandBordage** [comment]
This would be fixed by replacing django-treebeard with a module correctly handling transactions, like [django-tree](https://github.com/BertrandBordage/django-tree).

**Comment by lb-** [comment]
OneToOne protected fields have had some improvements via this PR https://github.com/wagtail/wagtail/pull/5437
