### ISSUE TITLE
Wagtail search `update_index` fails when indexing `ParentalManyToManyField`

### ISSUE THREAD

**Issue by mixxorz** [wagtail/wagtail#3728]
`update_index` fails when it encounters a `ParentalManyToManyField`. The error is from Django

```
ValueError: '{field with ParentalManyToManyField}' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
```

I think this is caused by [get_indexed_objects](https://github.com/wagtail/wagtail/blob/1943d5a83c8a8a68345cf48bee9b739ad4001aad/wagtail/wagtailsearch/index.py#L75). Since ParentaManyToManyField is a subclass of RelatedField, this code tries to do a prefetch. That obviously doesn't work because ParentalManyToManyField does not support prefetching. (?)

Unfortunately, I don't know modelcluster well enough to suggest a solution.

### Steps to Reproduce

1. Create a model with a ParentalManyToManyField
2. Add that field to search_fields
3. Run `update_index` management command

I'm not sure if this also happens on other search backends, but it happens when using the Postgres search backend.

### Workaround

Just republish all the pages. The indexing still works that way.

### Technical details

* Python version: 3.6.0
* Django version: 1.11.3
* Wagtail version: 1.11.1
* Search backend: Postgres Search

**Comment by gasman** [comment]
Hi @mixxorz - thanks for the report.

Confirmed that this bug is still present on 2.0b1, testing on a new project with the following home/models.py:

    from __future__ import absolute_import, unicode_literals

    from django import forms
    from django.db import models
    from modelcluster.fields import ParentalManyToManyField

    from wagtail.admin.edit_handlers import FieldPanel
    from wagtail.core.models import Page
    from wagtail.snippets.models import register_snippet
    from wagtail.search import index


    @register_snippet
    class BlogCategory(models.Model):
        name = models.CharField(max_length=255)

        panels = [
            FieldPanel('name'),
        ]

        def __str__(self):
            return self.name

        class Meta:
            verbose_name_plural = 'blog categories'


    class HomePage(Page):
        categories = ParentalManyToManyField('BlogCategory', blank=True)

        content_panels = Page.content_panels + [
            FieldPanel('categories', widget=forms.CheckboxSelectMultiple),
        ]

        search_fields = Page.search_fields + [
            index.RelatedFields('categories', [
                index.SearchField('name')
            ])
        ]

**Comment by timonweb** [comment]
I confirm this bug is still present on Wagtail 2.0.1, I've just caught it.

**Comment by timonweb** [comment]
Pushed the fix.

**Comment by BertrandBordage** [comment]
There’s another related issue when we filter instead of searching. Given these models:
```python
from django.db import models
from modelcluster.fields import ParentalManyToManyField

from wagtail.core.models import Page
from wagtail.search import index


class BlogCategory(models.Model):
    name = models.CharField(max_length=255)


class Article(Page):
    categories = ParentalManyToManyField('BlogCategory', blank=True)

    search_fields = Page.search_fields + [
        index.RelatedFields('categories', [
            index.FilterField('pk')
        ])
    ]
```

If you do a search & filter like: `Article.objects.search('something').filter(categories=5)`
This error is yield:
`FieldError: Cannot filter search results with field "category_id". Please add index.FilterField('category_id') to Article.search_fields.`

So the workaround is…
```python
    search_fields = Page.search_fields + [
        index.FilterField('category_id'),
        index.RelatedFields('categories', [
            index.FilterField('pk')
        ])
    ]
```

**Which obviously doesn’t make any sense.**
The registering+check system of wagtail’s search needs some adjustments on this.

**Comment by BertrandBordage** [comment]
I meant, this second issue occurs even while using @timonweb’s fix from #4458.

**Comment by strindhaug** [comment]
@BertrandBordage I'm on wagtail wagtail 2.3 and elasticsearch 2.4.1 and have basically the same setup as in the above example, and I get the `FieldError: Cannot filter search results with field "category_id". Please add index.FilterField('category_id') to Article.search_fields.` message.
But if I try to do as your workaround, i get warnings with every migration; and when not using elastic search locally it works; but when I use elasticsearch I cannot update_index because i get the following:

```sh
$ python manage.py update_index                                ~/zeppelin/aldring-og-helse/ah-web [16:35:56]
System check identified some issues:

WARNINGS:
articles.Article: Article.search_fields contains non-existent field 'articleindexpage_id'
articles.Article: Article.search_fields contains non-existent field 'maincategory_id'
Updating backend: default
default: Rebuilding index wagtail__common_customimage
default: common.CustomImage        .
default: indexed 33 objects

default: Rebuilding index wagtail__wagtailcore_page
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/wagtail/search/management/commands/update_index.py", line 125, in handle
    schema_only=options.get('schema_only', False), chunk_size=options.get('chunk_size')
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/wagtail/search/management/commands/update_index.py", line 77, in update_backend
    index.add_model(model)
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/wagtail/search/backends/elasticsearch2.py", line 838, in add_model
    index=self.name, doc_type=mapping.get_document_type(), body=mapping.get_mapping(),
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/wagtail/search/backends/elasticsearch2.py", line 211, in get_mapping
    self.get_field_mapping(field) for field in self.model.get_search_fields()
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/wagtail/search/backends/elasticsearch2.py", line 211, in <genexpr>
    self.get_field_mapping(field) for field in self.model.get_search_fields()
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/wagtail/search/backends/elasticsearch2.py", line 193, in get_field_mapping
    return self.get_field_column_name(field), mapping
  File "/home/stein/.local/share/virtualenvs/ah-web-fU20J1OR/lib/python3.6/site-packages/wagtail/search/backends/elasticsearch2.py", line 105, in get_field_column_name
    prefix = definition_model._meta.app_label.lower() + '_' + definition_model.__name__.lower() + '__'
AttributeError: 'NoneType' object has no attribute '_meta'
```
What am I missing? Is the workaround no longer functional in 2.3, or is it wrong elasticsearch version?

**Comment by SgtPorkChops** [comment]
I can confirm that I am also seeing this problem. I tried defining my `search_fields` using the `index.RelatedFields` method as defined in the Docs [here](https://docs.wagtail.io/en/v2.7.1/topics/search/indexing.html#index-relatedfields).

I see that it is currently not possible to filter on any `index.FilterField`s inside an `index.RelatedFields`, effectively preventing filtering m2m fields. I will take a crack at fixing it but no promises XD (Never actually tried to contribute on GitHub before so #YOLO)

An abridged version of my model definitions is as follows:
```python
class Article(Page):
    m2mField = ParentalManyToMany(
        'Indiv',
        blank=True,
        related_name='articles'

    search_fields = Page.search_fields + [
        index.RelatedFields('m2mfield', [
            index.FilterField('ShortTitle')
        ])
    ]

class Indiv(index.Indexed, Orderable):
    ShortTitle = models.CharField(
        max_length = 10,
        blank = False,
        null = True,
        verbose_name = 'Short Name'
    )
```

**Comment by dellitsni** [comment]
I'm getting the original issue on Wagtail 2.8.1. Have yet to find a fix or workaround.

**Comment by aliceni81** [comment]
I still have the issue on 2.16.1..

**Comment by ssyberg** [comment]
I'm seeing this on Wagtail 5.2.3, just tried switching to OpenSearch backend and getting this on my very first attempt at `update_index`

**Comment by ssyberg** [comment]
I was also able to confirm this is happening specifically on `ParentalManyToManyField`

**Comment by ssyberg** [comment]
Sorry for the spam here, but I can also confirm this only occurs with the `elasticsearch` backend set, when I switch by the the default the issue goes away.

**Comment by ssyberg** [comment]
If anyone does know more about this, can you comment on if there is any issue with, as a workaround, just adding a helper method that returns the data from the parental relationship and using a `SearchField`? So instead of:

```
 search_fields = Page.search_fields + [
        index.RelatedFields('m2mfield', [
            index.FilterField('ShortTitle')
        ])
    ]
```

You just do:

```
 search_fields = Page.search_fields + [
        index.SearchField('get_m2m_ShortTitle'),
    ]
```

Do you lose any functionality with this?

**Comment by aliceni81** [comment]
having this issue with wagtail 7.3.1 and ES9 when doing the filtering and searching at the same time..
