### ISSUE TITLE
npm scripts don't work on windows

### ISSUE THREAD

**Issue by MarkOBrienAU** [wagtail/wagtail#3872]
npm install fails on windows. Tested the exact same version in a Linux Mint (Ubuntu) VM and it works fine.

npm 3.10.10
node 6.11.3
I'm on the origin/stable/1.12.x branch.

Here's the error on npm install

```
npm ERR! tar.unpack error reading C:\Users\Mark\AppData\Local\Temp\npm-12252-6beb8bd0\registry.npmjs.org\lodash._reescape\-\lodash._reescape-3.0.0.tgz
npm ERR! tar.unpack error reading C:\Users\Mark\AppData\Local\Temp\npm-12252-6beb8bd0\registry.npmjs.org\lodash.template\-\lodash.template-3.6.2.tgz
npm ERR! tar.unpack error reading C:\Users\Mark\AppData\Local\Temp\npm-12252-6beb8bd0\registry.npmjs.org\sparkles\-\sparkles-1.0.0.tgz
npm ERR! tar.unpack error reading C:\Users\Mark\AppData\Local\Temp\npm-12252-6beb8bd0\registry.npmjs.org\util-deprecate\-\util-deprecate-1.0.2.tgz
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\Mark\AppData\Local\Temp\npm-12252-6beb8bd0\registry.npmjs.org\util-deprecate\-\util-deprecate-1.0.2.tgz
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Mark\AppData\Local\Temp\npm-12252-6beb8bd0\registry.npmjs.org\util-deprecate\-\util-deprecate-1.0.2.tgz'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Mark\AppData\Local\Temp\npm-12252-6beb8bd0\registry.npmjs.org\util-deprecate\-\util-deprecate-1.0.2.tgz'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mark\Documents\Dev\webdev\w3\npm-debug.log
```

There is kinda a work around, If I manually install gulp and webpack and its dependencies (basically keep trying to run the commands and npm install whatever it complains about, and then modify package.json to:
from
"build": "gulp build ; webpack --config ./client/webpack/prod.config.js",
to
"build": "gulp build && webpack --config ./client/webpack/prod.config.js",

note the &&

npm run build works fine.

**Comment by jjanssen** [comment]
Hi @MarkOBrienAU thanks for reporting. This was an outstanding issue for a long time, but since last night we have merged some fixes to master (#3442) to solve this problem. So I'm closing this for now, feel free to reopen if you still encounter issues.

**Comment by MarkOBrienAU** [comment]
I'm encountering issues again on windows with the latest master. It looks like npm is recusing 

```
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail\client\node_modules\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail
> npm --prefix client install
> wagtail@1.0.0 postinstall C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail\client\node_modules\wagtail
> npm --prefix client install
```
multiple npm-debug.log are generated, i opened up the top level one at found this error at the bottom:

```
118813 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
118814 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
118814 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
118814 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
118814 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
118815 verbose stack Error: wagtail@1.0.0 postinstall: `npm --prefix client install`
118815 verbose stack Exit status 1
118815 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
118815 verbose stack     at emitTwo (events.js:106:13)
118815 verbose stack     at EventEmitter.emit (events.js:191:7)
118815 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
118815 verbose stack     at emitTwo (events.js:106:13)
118815 verbose stack     at ChildProcess.emit (events.js:191:7)
118815 verbose stack     at maybeClose (internal/child_process.js:920:16)
118815 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
118816 verbose pkgid wagtail@1.0.0
118817 verbose cwd C:\Users\Mark\Documents\Dev\webdev\tmp\wagtail
118818 error Windows_NT 10.0.14393
118819 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
118820 error node v6.11.3
118821 error npm  v3.10.10
118822 error code ELIFECYCLE
118823 error wagtail@1.0.0 postinstall: `npm --prefix client install`
118823 error Exit status 1
118824 error Failed at the wagtail@1.0.0 postinstall script 'npm --prefix client install'.
118824 error Make sure you have the latest version of node.js and npm installed.
118824 error If you do, this is most likely a problem with the wagtail package,
118824 error not with npm itself.
118824 error Tell the author that this fails on your system:
118824 error     npm --prefix client install
118824 error You can get information on how to open an issue for this project with:
118824 error     npm bugs wagtail
118824 error Or if that isn't available, you can get their info via:
118824 error     npm owner ls wagtail
118824 error There is likely additional logging output above.
118825 verbose exit [ 1, true ]
```

**Comment by MarkOBrienAU** [comment]
@jjanssen how do I reopen this issue ?

**Comment by gasman** [comment]
Hi @MarkOBrienAU - from the error message it looks like you're running Node 6.11.3. To build the current master, you need to use Node 8 (see http://docs.wagtail.io/en/latest/contributing/developing.html#setting-up-the-wagtail-codebase).
