### ISSUE TITLE
Add ability to extend exclude_fields for use when copying page

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#3920]
### Issue Summary

If your Page model contains relations that do not use `ClusterableModel` you cannot copy those pages in admin without causing an error. Adding the ability to define what fields must be excluded on copy per Page would enable working around this.

### Steps to Reproduce

Note: This is my specific use case.

1. Start a new Wagtail project
2. Install Django Activity Stream http://django-activity-stream.readthedocs.io/en/latest/ `pip install django-activity-stream`
3. In your main `apps.py` register a generic link to your Page model `registry.register(Page)` - http://django-activity-stream.readthedocs.io/en/latest/configuration.html
4. Open a Page list in Admin and click More > Copy
5. Change the Slug to something Unique
6. Click 'Copy this Page'

This results in the following Error:
**TypeError: 'GenericRelatedObjectManager' object is not iterable**

```
The trace error is:
[09/Oct/2017 09:29:35] ERROR [django.request:135] Internal Server Error: /admin/pages/233/copy/
Traceback (most recent call last):
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/wagtail/wagtailadmin/decorators.py", line 31, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/wagtail/wagtailadmin/utils.py", line 140, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/wagtail/wagtailadmin/views/pages.py", line 837, in copy
    user=request.user,
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 1116, in copy
    page_copy = self.specific_class(**specific_dict)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 376, in __init__
    super(Page, self).__init__(*args, **kwargs)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/modelcluster/models.py", line 177, in __init__
    super(ClusterableModel, self).__init__(*args, **kwargs)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 567, in __init__
    _setattr(self, prop, kwargs[prop])
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py", line 537, in __set__
    manager.set(value)
  File "/home/ifeelgoogle/venv/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py", line 613, in set
    objs = tuple(objs)
TypeError: 'GenericRelatedObjectManager' object is not iterable

```

### Proposed Solution

https://github.com/wagtail/wagtail/blob/f15a98f983b1c6b11807d90226b7b3924b0a74d1/wagtail/wagtailcore/models.py#L1055

* The line above: `exclude_fields = ['id', 'path', 'depth', 'numchild', 'url_path', 'path']`
* Could be replaced with something like: `self.excluded_fields_for_copy`
* The default would be the list above but this could be extended for a specific class like: `excluded_fields_for_copy = Page.excluded_fields_for_copy + ['action_object_actions', 'actor_actions', 'target_actions']`
* As this is different to the `exclude_fields` used in `modelAdmin` it would need to be named specifically in relation to copying.

### Technical details

* Python 2.7.12
* Django v.1.11.5
* Wagtail v.1.12.2
* Browser version: Chrome 61 on OS X 10.12.6

**Comment by gasman** [comment]
Thanks for the report @lb-! Your proposed solution sounds good to me.

**Comment by lb-** [comment]
@gasman I will give a go at implementing this for a pull request next week.

**Comment by lb-** [comment]
@gasman final implementation is slightly different.

Developers can now only add to the array of fields that will be excluded, the default fields will always be excluded. This means it is harder to make a mistake that might cause issues like overwriting an existing page for example (if id is not excluded).

Also, I named the attribute `exclude_fields_in_copy` as it seemed to better match the other page attribute conventions.

**Comment by lb-** [comment]
@gasman just thinking about the attribute name, maybe it should be 

`exclude_fields_when_copied`
instead of 
`exclude_fields_in_copy`

longer name but maybe clearer

**Comment by kaedroho** [comment]
PR: https://github.com/wagtail/wagtail/pull/3987

**Comment by kaedroho** [comment]
Just hit this issue myself, the error message given doesn't make it clear what's going on. So I wonder if it's worth excluding generic relations by default?
