### ISSUE TITLE
Problem with ATOMIC_REBUILD: elasticsearch.exceptions.RequestError: TransportError(400, '')

### ISSUE THREAD

**Issue by SalahAdDin** [wagtail/wagtail#3985]
### Issue Summary

I can't make a new index for searching in my project.

### Steps to Reproduce

1. I do `./manage.py update_index`
2. Bash show me the error.

```bash
./manage.py update_index                                                                                                                ✓  5562  17:03:22 
Updating backend: default
default: Rebuilding index xprende__wagtailcore_page
default: blog.BlogIndexPage        .
default: blog.BlogPage             .
default: core.ContactForm          
default: home.HomePage             .
default: person.PersonIndexPage    
default: person.PersonPage         
default: wagtailcore.Page          .
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 120, in handle
    self.update_backend(backend_name, schema_only=options.get('schema_only', False))
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 93, in update_backend
    rebuilder.finish()
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 655, in finish
    if self.alias.is_alias():
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 513, in is_alias
    return self.es.indices.exists_alias(self.name)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 376, in exists_alias
    name), params=params)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/salahaddin/Proyectos/Works/partnerlatam/blog.xprende/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, '')
```

This is my setting:
```python
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.wagtailsearch.backends.elasticsearch5',
        'URLS': ['http://localhost:9200'],
        'INDEX': 'xprende',
        'ATOMIC_REBUILD': True,
        'TIMEOUT': 5,
        'OPTIONS': {},
        'INDEX_SETTINGS': {},
    }
}
```
It seems a problem whit `ATOMIC_REBUILD`:
1. I did remove these setting from my settings.
2. I ran again the update comand.
```bash
./manage.py update_index                                                                                                              ✓  5570  17:11:10 
Updating backend: default
default: Rebuilding index xprende__wagtailcore_page
default: blog.BlogIndexPage        .
default: blog.BlogPage             .
default: core.ContactForm          
default: home.HomePage             .
default: person.PersonIndexPage    
default: person.PersonPage         
default: wagtailcore.Page          .
default: indexed 4 objects

default: Rebuilding index xprende__core_uzmanimage
default: core.UzmanImage           .
default: indexed 4 objects

default: Rebuilding index xprende__wagtaildocs_document
default: wagtaildocs.Document      
default: indexed 0 objects

default: Rebuilding index xprende__wagtailimages_image
default: wagtailimages.Image       
default: indexed 0 objects

default: Rebuilding index xprende__wagtail_embed_videos_embedvideo
default: wagtail_embed_videos.EmbedVideo .
default: indexed 1 objects
```

### Technical details

* Python 3.6.3
* Django Version: 1.11.6
* Wagtail Version: 1.13
* Elasticsearch PY Version: 5.4.0
License: Apache License, Version 2.0
* ElasticSearch: 
```json
{
  "name" : "BZI5Bhk",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "X8XI7t8xRBe-jTl4MldM6A",
  "version" : {
    "number" : "5.6.3",
    "build_hash" : "1a2f265",
    "build_date" : "2017-10-06T20:33:39.012Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by gasman** [comment]
Thanks for the report @SalahAdDin!
We had issues with ATOMIC_REBUILD on Elasticsearch 5.4.x due to a bug in that version (https://github.com/wagtail/wagtail/pull/3637, https://github.com/elastic/elasticsearch/issues/24644) - it's possible that they re-introduced that bug in 5.6.

**Comment by SalahAdDin** [comment]
Yes, i think so.
