### ISSUE TITLE
djangorestframework needs to be a pinned dependency: Wagtail 1.7

### ISSUE THREAD

**Issue by jamesrampton** [wagtail/wagtail#4086]
### Issue Summary

Cannot import module:

from wagtail.wagtailadmin import urls as wagtailadmin_urls

### Steps to Reproduce

```
from wagtail.wagtailadmin import urls as wagtailadmin_urls
Traceback (most recent call last):                                                                                       File "<console>", line 1, in <module>
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/wagtail/wagtailadmin/urls/__init__.py", line 8, in <module>
    from wagtail.wagtailadmin.api import urls as api_urls
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/wagtail/wagtailadmin/api/urls.py", line
8, in <module>
    from .endpoints import PagesAdminAPIEndpoint
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/wagtail/wagtailadmin/api/endpoints.py",
line 5, in <module>
    from wagtail.api.v2.endpoints import PagesAPIEndpoint
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/wagtail/api/v2/endpoints.py", line 12, i
n <module>
    from rest_framework.renderers import BrowsableAPIRenderer, JSONRenderer                                              File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/rest_framework/renderers.py", line 24, i
n <module>
    from rest_framework import VERSION, exceptions, serializers, status
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 153
4, in <module>
    ModelSerializer.serializer_field_mapping[postgres_fields.JSONField] = JSONField
AttributeError: 'module' object has no attribute 'JSONField'
```
djangorestframework 3.6.2 works but 3.7.3 does not.

DRF should either be a pinned dependency or you should have some backwards compatibility to support the changes in DRF.

Note: This is my first Github issue so please be kind. If there's any way I can improve the issue, please let me know.

**Comment by gasman** [comment]
Thanks for the report @jamesrampton! This was addressed in Wagtail 1.12.3 and 1.13 (#3912) - I'm afraid we're no longer supporting pre-1.12 versions of Wagtail with bugfix releases, so if you're not able to upgrade to 1.12 or 1.13 then I'd recommend adding `django-rest-framework<3.7` to your project's requirements file.
