### ISSUE TITLE
django.core.exceptions.ValidationError: {'path': ...} when creating a subpage

### ISSUE THREAD

**Issue by thorink** [wagtail/wagtail#4174]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Had 3 subpages and removed 2 of them. The third subpage is now also not visible in the wagtail admin. I am not able to create subpages anymore.

### Steps to Reproduce

Im not exactly sure how this happed, but here is how the wagtailcore_page tables looks like:

id |                   path | depth | numchild | title
-- | --------------- | --- | --- | ---
1 | 0001	                 | 1   |     2 | Root
2 | 00010001           | 2   |   0   | Welcome to your new Wagtail site!
3 | 00010002           | 2  | 0      | Intern
7 | 000100020001  | 3   | 0     |Beamer

It seems like the numchild counter of Intern (id 3) was set to 0 instead of 1 when removed the second subpage (sibling of Beamer). Now If I create a new subpage, it seems that wagtail want's to use the path 000100020001 and django complains, that this path already exists.

This is the exception I get:

```
Internal Server Error: /cms/pages/add/home/homepage/3/
Traceback (most recent call last):
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/wagtail/wagtailadmin/urls/__init__.py", line 96, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 31, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/wagtail/wagtailadmin/views/pages.py", line 206, in create
    parent_page.add_child(instance=page)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/treebeard/mp_tree.py", line 1013, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/treebeard/mp_tree.py", line 389, in process
    newobj.save()
  File "/usr/local/opt/python-3.5/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/wagtail/wagtailcore/models.py", line 462, in save
    self.full_clean()
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/wagtail/wagtailcore/models.py", line 452, in full_clean
    super(Page, self).full_clean(*args, **kwargs)
  File "/home/django-user/cheich/venv/lib/python3.5/site-packages/django/db/models/base.py", line 1248, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'path': ['Seite mit diesem Path existiert bereits.']}
```

Sorry, that I can not show how to reproduce this issue.

Would it be save for me to increase numchild to 1?

### Technical details

* Python version: 3.5
* Django version: Django==1.11
* Wagtail version: wagtail==1.13.1

**Comment by gasman** [comment]
Hi @thorink - thanks for the report.
Wagtail provides a management command `./manage.py fixtree` which will hopefully be able to fix the incorrect numchild value. Unfortunately, without any information on how to reproduce this, there's not much more we can do here...

**Comment by thorink** [comment]
Thanks for the hint to `fixtree`! 👍
