### ISSUE TITLE
Tutorial issue: ModuleNotFoundError: No module named 'wagtail.core'

### ISSUE THREAD

**Issue by wtluke** [wagtail/wagtail#4255]
### Issue Summary

I've tried this on two different virtual envs in the [tutorial](https://github.com/wagtail/wagtail/blob/master/docs/getting_started/tutorial.rst) and keep hitting the same error (pasted below)

### Steps to Reproduce

1. Create a new virtualenv. I'm on Python 3.6.4 on a Mac. Activate it.
2. Carry out steps 1-6 in the tutorial.
3. In the **Extend the HomePage model** bit, change models.py accordingly.
4. Run `python manage.py makemigrations`, then `python manage.py migrate`. Or go into python and try importing:

from django.db import models
from wagtail.core.models import Page

### Technical details

* Python version: 3.6.4
```beautifulsoup4 (4.6.0)
certifi (2018.1.18)
chardet (3.0.4)
Django (1.11.10)
django-modelcluster (3.1)
django-taggit (0.22.2)
django-treebeard (4.2.0)
djangorestframework (3.6.4)
html5lib (0.999999999)
idna (2.6)
Pillow (5.0.0)
pip (9.0.1)
pytz (2017.3)
requests (2.18.4)
setuptools (28.8.0)
six (1.11.0)
Unidecode (1.0.22)
urllib3 (1.22)
wagtail (1.13.1)
webencodings (0.5.1)
Willow (1.0)```

Error:

```Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/will/.virtualenvs/w/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/will/.virtualenvs/w/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/Users/will/.virtualenvs/w/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/will/.virtualenvs/w/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/will/.virtualenvs/w/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/will/Documents/Work/cricviz/repos/w/wagtail/mysite/home/models.py", line 3, in <module>
    from wagtail.core.models import Page
ModuleNotFoundError: No module named 'wagtail.core'

**Comment by BertrandBordage** [comment]
Follow [the tutorial on ReadTheDocs](http://docs.wagtail.io/en/v1.13.1/getting_started/tutorial.html).
On the repository it contains the latest Wagtail 2.0 changes, which are not compatible with the version you’re using 1.13.1.
