### ISSUE TITLE
Bug - Settings throw Exception when all pages are deleted

### ISSUE THREAD

**Issue by Speedy1991** [wagtail/wagtail#4256]
```
Internal Server Error: /admin/settings/snippets/privacy/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailadmin/urls/__init__.py", line 96, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wagtail/wagtailadmin/decorators.py", line 31, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/wagtail/contrib/settings/views.py", line 43, in edit_current_site
    return redirect('wagtailsettings:edit', app_name, model_name, site.pk)
AttributeError: 'NoneType' object has no attribute 'pk'

```

### Steps to Reproduce

1) start wagtail proj
2) create a snippet privacy.py e.g.:

```
@register_setting
class Privacy(BaseSetting):
    content = RichTextField()
```
3) Delete all existing pages (in this case only root page)
4) Visit settings->privacy

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
- No Exception?
- If at least one root page exists, the exception is not thrown

### Technical details

* Python version: Python 3.6.1
* Django version: Django>=1.11,<1.12
* Wagtail version: wagtail>=1.13,<1.14
* Browser version: Not browser depended

**Comment by gasman** [comment]
This is presumably due to the logic in `edit_current_site`:

https://github.com/wagtail/wagtail/blob/2b12c07c93efc15118561653687f87031dd3ca96/wagtail/contrib/settings/views.py#L41

If no site records exist (which will be the case if all pages are deleted - or, more directly, all records under Settings -> Sites are deleted) then clearly there can't be a current or first site - in this case, the only meaningful thing we can do is report to the user that no sites exist. (Obviously, we should do that with a friendly error message rather than throwing an exception...)

**Comment by gasman** [comment]
Completed in #4362.
