### ISSUE TITLE
Edit document page crashes with error NoneType object has no attribute size

### ISSUE THREAD

**Issue by amir-qayyum-khan** [wagtail/wagtail#4512]
### Issue Summary

Edit document for crash when user tries to replace document.

### Steps to Reproduce

1. Login as admin (super user)
2. Go to documents and add a document lets say `x.pdf`
3. After uploading document go back to document listing page
4. Select the document from list that you just added
5. On edit page upload same document (exact same document) and press save
6. You will be navigate to the document listing page
7. Click edit on header notification or click same document that you just update
8. Crashed

cc @pdpinch 
https://github.com/pdpinch

#### Steps on screens:

<img width="1175" alt="screen shot 2018-05-03 at 6 50 32 pm" src="https://user-images.githubusercontent.com/10431250/39580729-3e44be50-4f03-11e8-92bb-21e913190538.png">

<img width="1170" alt="screen shot 2018-05-03 at 6 52 10 pm" src="https://user-images.githubusercontent.com/10431250/39580730-3e7be5a6-4f03-11e8-89d4-5d77de53a5a2.png">

<img width="1152" alt="screen shot 2018-05-03 at 6 52 22 pm" src="https://user-images.githubusercontent.com/10431250/39580732-3eabbdbc-4f03-11e8-8209-a67f05a9dd76.png">

<img width="968" alt="screen shot 2018-05-03 at 6 52 31 pm" src="https://user-images.githubusercontent.com/10431250/39580734-3edd9f44-4f03-11e8-9c35-41974cee6095.png">

<img width="1158" alt="screen shot 2018-05-03 at 6 52 46 pm" src="https://user-images.githubusercontent.com/10431250/39580736-3f168070-4f03-11e8-8e7e-e54e8f20f1e7.png">

<img width="1186" alt="screen shot 2018-05-03 at 6 52 54 pm" src="https://user-images.githubusercontent.com/10431250/39580737-3f44f040-4f03-11e8-9c2d-8c1a9b224591.png">

#### Exception trace:
```python
[2018-05-03 13:52:51] ERROR 28 [django.request] exception.py:118 - [4cb73e60b696] - Internal Server Error: /cms/documents/edit/9/
Traceback (most recent call last):
        File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
        File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
        File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
        File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
        File "/usr/local/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 95, in wrapper  
    return view_func(request, *args, **kwargs)
        File "/usr/local/lib/python3.6/site-packages/wagtail/admin/decorators.py", line 28, in decorated_view
    return view_func(request, *args, **kwargs)
        File "/usr/local/lib/python3.6/site-packages/wagtail/admin/utils.py", line 139, in wrapped_view_func
    return view_func(request, *args, **kwargs)
        File "/usr/local/lib/python3.6/site-packages/wagtail/documents/views/documents.py", line 154, in edit
    filesize = doc.file.size
        File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/files.py", line 69, in size
    return self.storage.size(self.name)
        File "/usr/local/lib/python3.6/site-packages/storages/backends/s3boto.py", line 473, in size
    return self.bucket.get_key(self._encode_name(name)).size
AttributeError: 'NoneType' object has no attribute 'size'
```

### Technical details

* DEFAULT_FILE_STORAGE: 'storages.backends.s3boto.S3BotoStorage'
* Python version: 3.6
* Django version: 2.0.2
* Wagtail version: 2.0
* Browser version: ```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36```

**Comment by gasman** [comment]
Closing as per #4502
