### ISSUE TITLE
All tests fail when reusing test database

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4520]
When running ``runtests.py --postgres --keepdb`` for the second time (so it reuses the previous database) now makes all tests fail with the following error:

```
Traceback (most recent call last):
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/db/models/base.py", line 446, in __init__
    rel_obj = kwargs.pop(field.name)
KeyError: 'collection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/db/models/base.py", line 451, in __init__
    val = kwargs.pop(field.attname)
KeyError: 'collection_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karl/projects/wagtail/wagtail/documents/tests/test_admin_views.py", line 118, in test_post
    response = self.client.post(reverse('wagtaildocs:add'), post_data)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/test/client.py", line 525, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/test/client.py", line 341, in post
    secure=secure, **extra)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/test/client.py", line 404, in generic
    return self.request(**r)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/test/client.py", line 485, in request
    raise exc_value
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/karl/projects/wagtail/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/karl/projects/wagtail/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/karl/projects/wagtail/wagtail/admin/utils.py", line 144, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/karl/projects/wagtail/wagtail/documents/views/documents.py", line 96, in add
    doc = Document(uploaded_by_user=request.user)
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/db/models/base.py", line 453, in __init__
    val = field.get_default()
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/db/models/fields/related.py", line 925, in get_default
    field_default = super().get_default()
  File "/home/karl/projects/wagtail/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 775, in get_default
    return self._get_default()
  File "/home/karl/projects/wagtail/wagtail/core/models.py", line 1989, in get_root_collection_id
    return Collection.get_first_root_node().id
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by kaedroho** [comment]
Tracked down using git-bisect to this commit: https://github.com/wagtail/wagtail/commit/e867b862dfa02befc937586b7dfc770275598ae3

**Comment by kaedroho** [comment]
I've tracked the issue down to this file https://github.com/wagtail/wagtail/blob/8b420b9abcfd7c4ede23f0b52fa60d81e640eb82/wagtail/images/tests/test_signal_handlers.py which had some major changes to it in the above commit. Removing this file solves the issue for me.

To track it down further, it appears that just having a class that inherits from ``TransactionTestCase`` with an empty body causes the issue.

**Comment by kaedroho** [comment]
I had a go at diffing the databases that are left behind when ``test_signal_handlers.py`` is/isn't present.

When this file is present, none of the initial data (permissions, root page, root collection, etc) are left in the database, but all this data is included when this file is removed. I checked if this was because ``test_signal_handlers.py`` was the last test file to run (as I was only testing ``wagtail.images``) but order doesn't seem to matter.

**Comment by kaedroho** [comment]
Found a blog post, so must be a common issue: http://5minutes.youkidea.com/transactiontestcase-keepdb-django-issues.html

**Comment by lb-** [comment]
@kaedroho  - looks like this is now fixed in Django 2.1.3
https://docs.djangoproject.com/en/2.1/releases/2.1.3/

>   Fixed a regression in Django 2.0 where test databases aren’t reused with manage.py test --keepdb on MySQL (#29827).

**Comment by gasman** [comment]
Still failing for me on Wagtail 2.7 and Django 2.2.6.

**Comment by laymonage** [comment]
It does not fail for me with latest `main` and Django 4.2, but I'm using SQLite.

**Comment by Guilouf** [comment]
I also have this problem with wagtail 6.3.1 and django 5.4.1, using postgresql.

`Page.get_first_root_node()` is returning `None` the second time my tests are laucned, with the `--keepdb` option.

Really annoying as wagtail migrations are heavy to run each time.

**Comment by laymonage** [comment]
This is a Django issue that affects all databases: https://code.djangoproject.com/ticket/26822

**Comment by Guilouf** [comment]
There is also this ticket https://code.djangoproject.com/ticket/25251 that is almost 10 years old, i tried to open a ticket to at least have a warning in the docs but it was closed 10 minutes after. https://code.djangoproject.com/ticket/36043

So for people having that issue, having `TransactionTestCase` or `LiveServerTestCase` in your tests erases all the data contained in your test database. Wagtails rely heavily on data created during their migrations, so you can't really test your app using `--keepdb` if you have any  `TransactionTestCase` or `LiveServerTestCase`.

The only workaround i found is maybe to add [tags](https://docs.djangoproject.com/en/5.1/topics/testing/tools/#tagging-tests) to tests that inherit `TransactionTestCase` and exclude them if you want to use `--keepdb`
