### ISSUE TITLE
manage.py update_index gives stacktrace with elasticsearch

### ISSUE THREAD

**Issue by jorenham** [wagtail/wagtail#4733]
When I run `manage.py update_index` I get the following error. I am able to use the search correctly  (it gives no results of course).

```
Updating backend: default
default: Rebuilding index wagtail__wagtailcore_page
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 120, in handle
    self.update_backend(backend_name, schema_only=options.get('schema_only', False))
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 77, in update_backend
    index.add_model(model)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/backends/elasticsearch2.py", line 113, in add_model
    index=self.name, doc_type=mapping.get_document_type(), body=mapping.get_mapping(),
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 137, in get_mapping
    self.get_field_mapping(field) for field in self.model.get_search_fields()
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 137, in <genexpr>
    self.get_field_mapping(field) for field in self.model.get_search_fields()
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 85, in get_field_mapping
    sub_field_name, sub_field_mapping = nested_mapping.get_field_mapping(sub_field)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/backends/elasticsearch.py", line 119, in get_field_mapping
    return self.get_field_column_name(field), mapping
  File "/usr/local/lib/python3.5/dist-packages/wagtail/wagtailsearch/backends/elasticsearch2.py", line 49, in get_field_column_name
    prefix = definition_model._meta.app_label.lower() + '_' + definition_model.__name__.lower() + '__'
AttributeError: 'NoneType' object has no attribute '_meta'
```

* Python version: 3.5.
* Django version: 1.11.
* Wagtail version: 1.13.4
* Elasticsearch version: 5.6.10

Am I missing something?

**Comment by gasman** [comment]
Hi @jorenham - thanks for the report.
Could you try commenting out `search_fields` definitions on your page models, to see if there's a particular one causing the issue?

**Comment by jorenham** [comment]
I found the culprit, a typo of the field name within `SearchField`.

**Comment by kaedroho** [comment]
This should definitely give a better error. We should add a system check so the field names are checked when running any management command.

**Comment by gasman** [comment]
There is a check - not sure why it didn't show up in this case:
https://github.com/wagtail/wagtail/commit/1dad100695060435b597545cd61c3ee420afee9f

(@jorenham, do you have anything in your settings that would cause warnings to be hidden...?)

**Comment by jorenham** [comment]
@gasman No nothing specific

**Comment by jorenham** [comment]
@gasman The typo was `desciption`, so nothing strange.
But apparently I have just missed the warning completely, as my server is configured to ignore all warnings :sweat_smile:.

**Comment by gasman** [comment]
Ah, OK - mystery solved then :-)

**Comment by ssyberg** [comment]
I'm experiencing this now on 5.2.3 just adding OpenSearch backend for the first time, any hints on how to debug? We have over 40 `search_fields` declarations so commenting out each one would be quite time consuming. 

```
Updating backend: default
default: Rebuilding index wagtail__wagtailcore_page
Traceback (most recent call last):
  File "/code/./manage.py", line 22, in <module>
    main()
  File "/code/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/wagtail/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/wagtail/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/wagtail/.local/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/wagtail/.local/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/management/commands/update_index.py", line 158, in handle
    self.update_backend(
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/management/commands/update_index.py", line 88, in update_backend
    index.add_model(model)
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch7.py", line 46, in add_model
    self.es.indices.put_mapping(index=self.name, body=mapping.get_mapping())
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch7.py", line 22, in get_mapping
    mapping = super().get_mapping()
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch6.py", line 43, in get_mapping
    mapping = super().get_mapping()
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch5.py", line 230, in get_mapping
    {
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch5.py", line 231, in <dictcomp>
    self.get_field_mapping(field)[0]: self.get_field_mapping(field)[1]
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch5.py", line 171, in get_field_mapping
    sub_field_name, sub_field_mapping = nested_mapping.get_field_mapping(
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/backends/elasticsearch5.py", line 178, in get_field_mapping
    mapping = {"type": self.type_map.get(field.get_type(self.model), "string")}
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/index.py", line 247, in get_type
    field = self.get_field(cls)
  File "/home/wagtail/.local/lib/python3.9/site-packages/wagtail/search/index.py", line 223, in get_field
    return cls._meta.get_field(self.field_name)
AttributeError: 'NoneType' object has no attribute '_meta'
```

**Comment by ssyberg** [comment]
Figured out my issue appears to be a duplicate of this: https://github.com/wagtail/wagtail/issues/3728
