### ISSUE TITLE
Inheriting from a custom page model called Page leads to problems

### ISSUE THREAD

**Issue by fpoulain** [wagtail/wagtail#4799]
### Issue Summary

Inheriting from a custom page model called Page leads to problems:
- An error occurs when I try to create a child-of-root page using the inherited model.
- A migration, from "when I inherit from wagtail Page model" to "when I inherit from my custom Page model" removes the page_ptr field and break many things ;
- it seems that page_ptr is lost/added when migrated from one to another, causing migration issues.

If such a Page model definition isn't supported, the documentation should precise it. It says "All page models must inherit from the wagtail.core.models.Page class." but it remains unclear for me if it have to *directly* inherit or if sub-inheritance is supported too...

Also, if the "Page" model name should be reserved, the documentation should mention it.

### Steps to Reproduce

With Wagtail 

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows:
```python
from django.db import models

from wagtail.core.models import Page as WagtailPage
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel


class Page(WagtailPage):
    body = RichTextField(blank=True)

    content_panels = WagtailPage.content_panels + [
        FieldPanel('body', classname="full"),
    ]


class BugyHomePage(Page):
    body2 = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body2', classname="full"),
    ]
```
3. Create/apply migrations and create a super user
4. go to admin panel
5. Create a page of type BugyHomePage, below the root.
6. You should get this error:
```
Internal Server Error: /admin/pages/add/base/bugyhomepage/1/
Traceback (most recent call last):
  File "venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "venv/lib/python3.5/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.5/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.5/site-packages/wagtail/admin/views/pages.py", line 221, in create
    parent_page.add_child(instance=page)
  File "venv/lib/python3.5/site-packages/treebeard/mp_tree.py", line 1013, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "venv/lib/python3.5/site-packages/treebeard/mp_tree.py", line 367, in process
    if newobj.pk:
  File "venv/lib/python3.5/site-packages/django/db/models/base.py", line 564, in _get_pk_val
    return getattr(self, meta.pk.attname)
AttributeError: 'OneToOneField' object has no attribute 'attname'
```

> Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Because the bug isn't reproducible (i.e. it works fine) using the same logic with different names:
```python
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel


class MyPage(Page):
    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
    ]


class BugyHomePage(MyPage):
    body2 = RichTextField(blank=True)

    content_panels = MyPage.content_panels + [
        FieldPanel('body2', classname="full"),
    ]
```

Last but least (and probably related), changing inheritance from Wagtail's Page model to custom Page model break page_ptr:

```diff
diff --git a/bug/base/models.py.old b/bug/base/models.py
index 804e009..4b56968 100644
--- a/bug/base/models.py.old
+++ b/bug/base/models.py
@@ -13,9 +13,9 @@ class Page(WagtailPage):
     ]
 
 
-class BugyHomePage(WagtailPage):
+class BugyHomePage(Page):
     body2 = RichTextField(blank=True)
 
-    content_panels = WagtailPage.content_panels + [
+    content_panels = Page.content_panels + [
         FieldPanel('body2', classname="full"),
     ]
```

```
$ ./venv/bin/python manage.py makemigrations base
Migrations for 'base':
  bug/base/migrations/0002_remove_bugyhomepage_page_ptr.py
    - Remove field page_ptr from bugyhomepage
```

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project.

### Technical details
```
$ ./venv/bin/python -m pip show wagtail
Name: wagtail
Version: 2.2.2
Summary: A Django content management system.
Home-page: http://wagtail.io/
Author: Wagtail core team + contributors
Author-email: hello@wagtail.io
License: BSD
Location: venv/lib/python3.5/site-packages
Requires: beautifulsoup4, html5lib, draftjs-exporter, Unidecode, django-modelcluster, django-treebeard, djangorestframework, Willow, Django, Pillow, django-taggit, requests, six, pytz
Required-by: 
$ ./venv/bin/python -m pip show django
Name: Django
Version: 2.0.9
Summary: A high-level Python Web framework that encourages rapid development and clean, pragmatic design.
Home-page: https://www.djangoproject.com/
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: venv/lib/python3.5/site-packages
Requires: pytz
Required-by: wagtail, django-treebeard, django-taggit, django-debug-toolbar, django-cuser
$ ./venv/bin/python -m pip show django-treebeard
Name: django-treebeard
Version: 4.3
Summary: Efficient tree implementations for Django
Home-page: https://github.com/django-treebeard/django-treebeard/
Author: Gustavo Picon
Author-email: tabo@tabo.pe
License: Apache License 2.0
Location: venv/lib/python3.5/site-packages
Requires: Django
Required-by: wagtail
$ ./venv/bin/python --version
Python 3.5.3
```

**Comment by jmfederico** [comment]
I just ran into this same issue.

Maybe suggesting users not to use `Page` as a class name for any models?

**Comment by gasman** [comment]
I suspect this is due to Django auto-generating the field name `page_ptr_id` for the one-to-one relation from the specific page class to the base `Page` model - in this case the name `page` is not qualified with the app name, so there's nothing to distinguish it from other models named `Page`. If so, the fix would be to [define an explicit `parent_link` relation](https://docs.djangoproject.com/en/2.2/topics/db/models/#specifying-the-parent-link-field) on one or both models:

    class Page(WagtailPage):
        wagtailpage_ptr = models.OneToOneField(WagtailPage, on_delete=models.CASCADE, parent_link=True)
        body = RichTextField(blank=True)

This is working as designed at the Django level, so I think this counts as a documentation issue rather than a bug. #5366 is a similar issue, where the reverse relation (from `Page` to the specific model) is liable to clash with foreign keys if the developer hasn't followed the convention of naming page models `FooPage` - it probably makes sense to document these two gotchas together.
