### ISSUE TITLE
Wagtail admin failure after upgrade to 2.3

### ISSUE THREAD

**Issue by fpoulain** [wagtail/wagtail#4861]
### Issue Summary

Wagtail admin fails after upgrading to 2.3.

The trace:
```
Performing system checks...

System check identified no issues (0 silenced).
October 27, 2018 - 16:38:21
Django version 2.0.9, using settings 'test-wagtail.settings.development'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /admin/pages/3/edit/
Traceback (most recent call last):
  File "venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "venv/lib/python3.5/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.5/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File "venv/lib/python3.5/site-packages/wagtail/admin/views/pages.py", line 537, in edit
    'has_unsaved_changes': has_unsaved_changes,
  File "venv/lib/python3.5/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "venv/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 993, in render
    output = self.filter_expression.resolve(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 676, in resolve
    obj = self.var.resolve(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 802, in resolve
    value = self._resolve_lookup(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 864, in _resolve_lookup
    current = current()
  File "venv/lib/python3.5/site-packages/wagtail/admin/edit_handlers.py", line 230, in render_form_content
    return mark_safe(self.render_as_object() + self.render_missing_fields())
  File "venv/lib/python3.5/site-packages/wagtail/admin/edit_handlers.py", line 198, in render_as_object
    return self.render()
  File "venv/lib/python3.5/site-packages/wagtail/admin/edit_handlers.py", line 299, in render
    'self': self
  File "venv/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 993, in render
    output = self.filter_expression.resolve(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 676, in resolve
    obj = self.var.resolve(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 802, in resolve
    value = self._resolve_lookup(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 864, in _resolve_lookup
    current = current()
  File "venv/lib/python3.5/site-packages/wagtail/admin/edit_handlers.py", line 198, in render_as_object
    return self.render()
  File "venv/lib/python3.5/site-packages/wagtail/admin/edit_handlers.py", line 299, in render
    'self': self
  File "venv/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 993, in render
    output = self.filter_expression.resolve(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 676, in resolve
    obj = self.var.resolve(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 802, in resolve
    value = self._resolve_lookup(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 864, in _resolve_lookup
    current = current()
  File "venv/lib/python3.5/site-packages/wagtail/admin/edit_handlers.py", line 457, in render_as_object
    'field': self.bound_field,
  File "venv/lib/python3.5/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "venv/lib/python3.5/site-packages/django/test/utils.py", line 98, in instrumented_test_render
    return self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 58, in render
    result = self.nodelist.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 993, in render
    output = self.filter_expression.resolve(context)
  File "venv/lib/python3.5/site-packages/django/template/base.py", line 703, in resolve
    new_obj = func(obj, *arg_vals)
  File "venv/lib/python3.5/site-packages/wagtail/admin/templatetags/wagtailadmin_tags.py", line 244, in render_with_errors
    return bound_field.as_widget()
  File "venv/lib/python3.5/site-packages/django/forms/boundfield.py", line 118, in as_widget
    **kwargs
  File "venv/lib/python3.5/site-packages/wagtail/core/blocks/base.py", line 505, in render
    return self.render_with_errors(name, value, attrs=attrs, errors=None, renderer=renderer)
TypeError: render_with_errors() got an unexpected keyword argument 'renderer'
```

### Steps to Reproduce

> Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

It works well after downgrading to Wagtail 2.2.2.

> I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:

No. It might due to some nesting in StreamBlocks. I wasn't able to provide a minimal example reproducing the bug.

### Technical details

* Python version: Run `python --version`.
```
$ ./venv/bin/python --version
Python 3.5.3
```

* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.

```
$ ./venv/bin/pip show django
Name: Django
Version: 2.0.9
```
* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.

wagtail-2.3

**Comment by gasman** [comment]
Hi @fpoulain,
Are you using `wagtail-react-streamfield` on your project? It seems there's a compatibility issue which would cause this error: https://github.com/noripyt/wagtail-react-streamfield/issues/17

**Comment by fpoulain** [comment]
Yes I am. Sorry I missed it in the report.

It seems to be the same bug.

**Comment by gasman** [comment]
Thanks for the confirmation - closing as this is a wagtail-react-streamfield bug.
