### ISSUE TITLE
Confusing error when forgotten to install elasticsearch-py

### ISSUE THREAD

**Issue by kaedroho** [wagtail/wagtail#4947]
If ``elasticsearch-py`` is not installed, the developer is given the following error:

``wagtail.search.backends.InvalidSearchBackendError: Could not find backend 'wagtail.search.backends.elasticsearch5':``

This is confusing as it implies that the backend name is mispelt, which it's not.

Instead, the underlying error should be raised:

``ModuleNotFoundError: No module named 'elasticsearch'```

Which makes it obvious to the developer that they need to install something.

**Comment by thibaudcolas** [comment]
Been there :) It’s not that confusing because the `ModuleNotFoundError` is there further up the chain of exceptions, but I suppose there is some room for improvement. It looks like we could simply `raise e` the existing ImportError to get the intended:

> Could not find backend 'wagtail.search.backends.elasticsearch8': No module named 'elasticsearch'

Stack traces as-is (truncated)

```
Internal Server Error: /api/v2/pages/
Traceback (most recent call last):
  File "wagtaill/search/backends/__init__.py", line 43, in import_backend
    backend_module = import_module(dotted_path)
[…]
  File "wagtaill/search/backends/elasticsearch8.py", line 2, in <module>
    from elasticsearch import NotFoundError
ModuleNotFoundError: No module named 'elasticsearch'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "wagtaill/search/backends/__init__.py", line 75, in get_search_backend
    backend_cls = import_backend(backend)
                  ^^^^^^^^^^^^^^^^^^^^^^^
[…]                  
  File "wagtaill/search/backends/__init__.py", line 50, in import_backend
    raise ImportError from e
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wagtaill/api/v2/filters.py", line 148, in filter_queryset
    sb = get_search_backend()
         ^^^^^^^^^^^^^^^^^^^^
  File "wagtaill/search/backends/__init__.py", line 77, in get_search_backend
    raise InvalidSearchBackendError(f"Could not find backend '{backend}': {e}")
wagtail.search.backends.InvalidSearchBackendError: Could not find backend 'wagtail.search.backends.elasticsearch8': 
```

**Comment by laymonage** [comment]
Could be worth raising a more descriptive error message. Django does it for some database backends:

- https://github.com/django/django/blob/41239fe34d64e801212dccaa4585e4802d0fac68/django/db/backends/postgresql/base.py#L23-L44
- https://github.com/django/django/blob/41239fe34d64e801212dccaa4585e4802d0fac68/django/db/backends/mysql/base.py#L15-L38
- https://github.com/django/django/blob/41239fe34d64e801212dccaa4585e4802d0fac68/django/db/backends/oracle/base.py#L23-L26

I agree with the original report. The backend _is_ there, it just cannot be loaded because the module that powers it is missing. Rather than `"Could not find backend 'wagtail.search.backends.elasticsearch8'"` it should probably be something like `Could not load backend 'wagtail.search.backends.elasticsearch8'`, with the original `ImportError` appended after.
