### ISSUE TITLE
OneToOneField on Page causes subclasses to fail validation

### ISSUE THREAD

**Issue by therefromhere** [wagtail/wagtail#4960]
### Issue Summary

A OneToOneField on a Page causes subclasses of the page to fail to publish with a `django.core.exceptions.ValidationError: {'foo': ['Home page with this Foo already exists.']}`

I'm guessing this is because the parent page is being found when it's doing unique validation.  If I exclude this field from unique validation then I don't hit the bug (but that renders the OneToOneField slightly pointless of course).

Is this expected to work?

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows...

```
import logging

from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from wagtail.core.models import Page

logger = logging.getLogger(__name__)


class Foo(models.Model):
    pass


class HomePage(Page):
    foo = models.OneToOneField(Foo, on_delete=models.SET_NULL, null=True, blank=True)

    def validate_unique(self, exclude=None, *args, **kwargs):
       exclude = exclude or []
       # uncomment this line to avoid the bug
       # exclude.append("foo")
       super().validate_unique(exclude=exclude, *args, **kwargs)

class ChildPage(HomePage):
    pass


@receiver(pre_save, sender=ChildPage)
def attach_foo(sender, instance, *args, **kwargs):
    if not instance.foo:
        logger.warning("creating OneToOne")
        foo = Foo()
        foo.save()
        instance.foo = foo
```

3. makemigrations, migrate, login to wagtail
4. Create a new ChildPage in wagtail and publish

Expected:

ChildPage to be published

Actual Result:

Publish fails with Validation error:  {'foo': ['Home page with this Foo already exists.']}

Exception trace:

```
Internal Server Error: /admin/pages/add/home/childpage/3/
Traceback (most recent call last):
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/wagtail/admin/views/pages.py", line 233, in create
    revision.publish()
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/wagtail/core/models.py", line 1518, in publish
    page.save()
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/wagtail/core/models.py", line 443, in save
    self.full_clean()
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/wagtail/core/models.py", line 433, in full_clean
    super().full_clean(*args, **kwargs)
  File "/home/johnc/.virtualenvs/scratch_wagtail/lib/python3.6/site-packages/django/db/models/base.py", line 1152, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'foo': ['Home page with this Foo already exists.']}
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)
yes

### Technical details

* Python version: Run `python --version`.
Python 3.6.7

* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
2.1.4

* Wagtail version: Hover over the Wagtail bird in the admin, or run `pip show wagtail | grep Version:`.
2.3

* Browser version: You can use http://www.whatsmybrowser.org/ to find this out.
Chrome on Ubuntu

**Comment by therefromhere** [comment]
Some debug on this, the unique check fails because this returns null:  

```model_class_pk = self._get_pk_val(model_class._meta)```

django/db/models/base.py:1030  (Django 2.1.4)

during page.save() in PageRevision.publish() because page_ptr_id is null, so the "foo" unique validation doesn't exclude itself.

I think this is because the model is in a weird state when converting from a PageRevision to a Page.

**Comment by KalobTaulien** [comment]
Hey @therefromhere 

I ran into this today. Thank you for opening this issue! 

I wasn't able to find a proper solution, so I ended up converting my OneToOneField to a ForeignKey and it worked the way I expected it to.

**Comment by lingster** [comment]
> Hey @therefromhere
> 
> I ran into this today. Thank you for opening this issue!
> 
> I wasn't able to find a proper solution, so I ended up converting my OneToOneField to a ForeignKey and it worked the way I expected it to.

I had faced a similar issue and indeed using a foreign key works, but actually if you wanted to keep the OneToOneField() overriding the validate_unique() function seems to be the right way to go:
`
    def validate_unique(self, exclude=None, *args, **kwargs):
        exclude = exclude or []
        exclude.append("user")  # insert the name of your OneToOneField here.
        super().validate_unique(exclude=exclude, *args, **kwargs)
`
