### ISSUE TITLE
makemigrations fails on a database that has not yet run Wagtail 2.3->2.4 migrations

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#4961]
### Issue Summary

Running `./manage.py makemigrations` immediately after upgrading a site from Wagtail 2.3 to 2.4rc1 fails with the error:

    django.db.migrations.exceptions.InconsistentMigrationHistory: Migration wagtaildocs.0005_document_collection is applied before its dependency wagtailcore.0001_squashed_0041 on database 'default'.

This new squashed migration was introduced in #4916; a pre-2.4 installation would have run the now-deleted migration `wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field` instead.

Running `./manage.py migrate` then `./manage.py makemigrations` succeeds; however, [our upgrade instructions specify `makemigrations` first](http://docs.wagtail.io/en/v2.3/releases/upgrading.html#upgrade-process), and so if this is unfixable we need to at least update those instructions.

### Steps to Reproduce

    mkvirtualenv squashedmigration --python=python3.6
    pip install "wagtail>=2.3,<2.4"
    wagtail start squashedmigration
    cd squashedmigration
    ./manage.py migrate
    pip install wagtail==2.4rc1
    ./manage.py makemigrations

Fails with:

    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/Users/matthew/.virtualenvs/squashedmigration/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
        utility.execute()
      File "/Users/matthew/.virtualenvs/squashedmigration/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/Users/matthew/.virtualenvs/squashedmigration/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/Users/matthew/.virtualenvs/squashedmigration/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
        output = self.handle(*args, **options)
      File "/Users/matthew/.virtualenvs/squashedmigration/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
        res = handle_func(*args, **kwargs)
      File "/Users/matthew/.virtualenvs/squashedmigration/lib/python3.6/site-packages/django/core/management/commands/makemigrations.py", line 103, in handle
        loader.check_consistent_history(connection)
      File "/Users/matthew/.virtualenvs/squashedmigration/lib/python3.6/site-packages/django/db/migrations/loader.py", line 297, in check_consistent_history
        connection.alias,
    django.db.migrations.exceptions.InconsistentMigrationHistory: Migration wagtaildocs.0005_document_collection is applied before its dependency wagtailcore.0001_squashed_0041 on database 'default'.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.6.6
* Django version: 2.1.4
* Wagtail version: 2.4rc1

**Comment by gasman** [comment]
Addressed by #4963
