### ISSUE TITLE
Feature Detection on animated gif leads to "ValueError: cannot reshape array of size ..."

### ISSUE THREAD

**Issue by germn** [wagtail/wagtail#5239]
### Issue Summary

Subj.

### Steps to Reproduce

1. Enable [Animated GIF support](https://docs.wagtail.io/en/v2.4/advanced_topics/images/animated_gifs.html) and [Feature Detection](https://docs.wagtail.io/en/v2.4/advanced_topics/images/feature_detection.html)
2. Try to upload gif into the gallery (I used [this one](https://media.giphy.com/media/fQfu05qTEXYOI/giphy.gif))
3. See exception in console

This issue is probably related to [this one](https://github.com/wagtail/Willow/issues/68).

My traceback:

```
  File "...\site-packages\django\dispatch\dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "...\site-packages\wagtail\images\signal_handlers.py", line 18, in pre_save_image_feature_detection
    instance.set_focal_point(instance.get_suggested_focal_point())
  File "...\site-packages\wagtail\images\models.py", line 237, in get_suggested_focal_point
    faces = willow.detect_faces()
  File "...\site-packages\willow\image.py", line 60, in wrapper
    image = converter(image)
  File "...\site-packages\willow\plugins\opencv.py", line 61, in from_buffer_rgb
    image = image.reshape(image_buffer.size[1], image_buffer.size[0], 3)
ValueError: cannot reshape array of size 3510000 into shape (225,400,3)
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.3
* Django version: 2.1.8
* Wagtail version: 2.4
* Browser version: Chrome 73

Also relevant:

* Windows 10
* `Wand==0.4.2`
* `ImageMagick-6.9.0-4-Q16-x64-dll.exe` from [here](https://ftp.icm.edu.pl/packages/ImageMagick/binaries/)
* `opencv-python-headless==4.1.0.25`

**Comment by wimfeijen** [comment]
I just wanted to confirm that I ran into the same error.
Using:
Debian 5.10.136-1 (2022-08-13)
opencv-python==4.5.3.56
Wand==0.6.10
ImageMagick 6.9.11-60 Q16 x86_64

**Comment by wimfeijen** [comment]
Hi, I managed to reproduce the error in a new version of Wagtail. 

In settings.py: 
WAGTAILIMAGES_FEATURE_DETECTION_ENABLED = True

I am using:

wagtail==4.0.2
Django==4.1.2
Wand==0.6.10
Willow==1.4.1
opencv-python==4.6.0.66

Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org
Linux dev 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64

Here is the stack trace:
ERROR 2022-10-13 17:44:30,089 log 726866 139984313513792 Internal Server Error: /admin/images/multiple/add/
Traceback (most recent call last):
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 165, in wrapper
    return view_func(request, *args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/views/decorators/vary.py", line 21, in inner_func
    response = func(*args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/admin/views/generic/multiple_upload.py", line 44, in dispatch
    return super().dispatch(request)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/admin/views/generic/permissions.py", line 36, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/admin/views/generic/multiple_upload.py", line 146, in post
    self.object = self.save_object(form)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/images/views/multiple.py", line 83, in save_object
    image.save()
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/db/models/base.py", line 847, in save_base
    pre_save.send(
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 57, in wrapper
    return receiver(*args, **kwargs)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/images/signal_handlers.py", line 22, in pre_save_image_feature_detection
    instance.set_focal_point(instance.get_suggested_focal_point())
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/wagtail/images/models.py", line 328, in get_suggested_focal_point
    faces = willow.detect_faces()
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/willow/image.py", line 78, in wrapper
    image = converter(image)
  File "/var/virtualenvs/templateproject/lib/python3.9/site-packages/willow/plugins/opencv.py", line 66, in from_buffer_rgb
    image = image.reshape(image_buffer.size[1], image_buffer.size[0], 3)
Oct 13 17:44:30 dev uwsgi[726866]: ValueError: cannot reshape array of size 3390000 into shape (226,500,3)
