### ISSUE TITLE
Test failing when upgrading to 2.0.2

### ISSUE THREAD

**Issue by jossingram** [wagtail/wagtail#5259]
### Issue Summary

A test that once failed before but was fixed is now failing again. 

Test code is same as the given new code to use in this issue https://github.com/wagtail/wagtail/issues/4232

```
Traceback (most recent call last):
  File "/code/varioussite/tests/test_create_pages.py", line 64, in test_can_create_article_page
    {"type": "google_map", "value": {"map_pins": [], "map_lat": "12.3434", "map_zoom_level": "14", "map_long": "-52.34334"}}
  File "/usr/local/lib/python3.5/dist-packages/wagtail/tests/utils/page_tests.py", line 60, in assertCanCreate
    response = self.client.post(add_url, data, follow=True)
  File "/usr/local/lib/python3.5/dist-packages/django/test/client.py", line 525, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/usr/local/lib/python3.5/dist-packages/django/test/client.py", line 341, in post
    secure=secure, **extra)
  File "/usr/local/lib/python3.5/dist-packages/django/test/client.py", line 404, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.5/dist-packages/django/test/client.py", line 485, in request
    raise exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/urls/__init__.py", line 95, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/decorators.py", line 28, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/views/pages.py", line 194, in create
    if form.is_valid():
  File "/usr/local/lib/python3.5/dist-packages/modelcluster/forms.py", line 312, in is_valid
    form_is_valid = super(ClusterForm, self).is_valid()
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 179, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 174, in errors
    self.full_clean()
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 376, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 388, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python3.5/dist-packages/wagtail/core/blocks/base.py", line 512, in value_from_datadict
    return self.block_def.value_from_datadict(data, files, name)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/core/blocks/stream_block.py", line 162, in value_from_datadict
    child_block.value_from_datadict(data, files, '%s-%d-value' % (prefix, i)),
  File "/usr/local/lib/python3.5/dist-packages/wagtail/core/blocks/field_block.py", line 69, in value_from_datadict
    return self.value_from_form(self.field.widget.value_from_datadict(data, files, prefix))
  File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/rich_text/editors/draftail/__init__.py", line 63, in value_from_datadict
    return self.converter.to_database_format(original_value)
  File "/usr/local/lib/python3.5/dist-packages/wagtail/admin/rich_text/converters/contentstate.py", line 90, in to_database_format
    return self.exporter.render(json.loads(contentstate_json))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Steps to Reproduce

1. Upgraded from Wagtail 1.13.4
2. Tests were ok I think
3. Created and ran new migrations after adding things like on_delete, various other things needed after upgrade
4. Test creating a page with SF fails with error above.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: ( no)

### Technical details

* Python version: Run  Python 3.5.2
* Django version: 2.0.13
* Wagtail version: 2.0.2

**Comment by jossingram** [comment]
Sorry my bad, I'd rewritten the tests for version 2 with the helpers but left the ManagementForm data lines in from the old way, which you don't need now.
