### ISSUE TITLE
Revision history comparison breaks on streamfield after 2.5 upgrade

### ISSUE THREAD

**Issue by Adrian-Turjak** [wagtail/wagtail#5261]
### Issue Summary

An attempt to compare streamfield changes causes a 500 because of incorrect usage of `list.append()` getting passed in two values which I assume are meant to be a tuple.

### Steps to Reproduce

At least for me, I just had to create any page with a stream field, then edit it twice, and any attempt to compare the contents of a streamfield resulted in this error. Any streamfield that uses Structblocks will be hit by it.

### Technical details

* Python version: 3.7.3
* Django version: 2.2
* Wagtail version: 2.5

### Log:
```
app_1  | ACCESS: 10.203.0.194 - - [26/Apr/2019:03:48:53 +0000] "GET /admin/pages/120/revisions/compare/1137...1138/ HTTP/1.1" 500 27 "https://website.dev.catalystcloud.nz/admin/pages/120/revisions/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
app_1  | DJANGO: ERROR 2019-04-26 03:48:53,736 /usr/local/lib/python3.7/site-packages/django/utils/log.py Internal Server Error: /admin/pages/120/revisions/compare/1137...1138/
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
app_1  |     response = get_response(request)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
app_1  |     response = self.process_exception_by_middleware(e, request)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
app_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
app_1  |     response = view_func(request, *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
app_1  |     return view_func(request, *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
app_1  |     return view_func(request, *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/views/pages.py", line 1229, in revisions_compare
app_1  |     'comparison': comparison,
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
app_1  |     content = loader.render_to_string(template_name, context, request, using=using)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
app_1  |     return template.render(context, request)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
app_1  |     return self.template.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
app_1  |     return self._render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
app_1  |     return compiled_parent._render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
app_1  |     return compiled_parent._render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
app_1  |     return compiled_parent._render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
app_1  |     return self.nodelist.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
app_1  |     result = block.nodelist.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
app_1  |     result = block.nodelist.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
app_1  |     nodelist.append(node.render_annotated(context))
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
app_1  |     return nodelist.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
app_1  |     bit = node.render_annotated(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
app_1  |     return self.render(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 987, in render
app_1  |     output = self.filter_expression.resolve(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
app_1  |     obj = self.var.resolve(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
app_1  |     value = self._resolve_lookup(context)
app_1  |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
app_1  |     current = current()
app_1  |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/compare.py", line 218, in htmldiff
app_1  |     return StreamBlockComparison(self.field.stream_block, True, True, self.val_a, self.val_b).htmldiff()
app_1  |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/compare.py", line 196, in htmldiff
app_1  |     block_rendered = comparison.htmldiff()
app_1  |   File "/usr/local/lib/python3.7/site-packages/wagtail/admin/compare.py", line 129, in htmldiff
app_1  |     htmldiffs.append(label, comparison_class(block, self.exists_a, self.exists_b, self.val_a[name], self.val_b[name]).htmldiff())
app_1  | TypeError: append() takes exactly one argument (2 given)
```

**Comment by Adrian-Turjak** [comment]
I've fixed the code I think caused it, and it seems to now work. Will submit a pull request.

**Comment by robvdl** [comment]
Sounds like this would be one to include for a 2.5.1 bugfix release
