### ISSUE TITLE
get error with .add-child()

### ISSUE THREAD

**Issue by m-pasha** [wagtail/wagtail#5312]
I try create new page via wagtail admin and get error with **treebeard** pkg
`newobj.path = self.node.get_last_child()._inc_path()`

### Issue Summary

```backend_1  | 2019-05-21 08:33:27,134 [ERROR] django.request line 228: Internal Server Error: /admin/pages/new/article/articlepage/5/
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
backend_1  |     response = get_response(request)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
backend_1  |     response = self.process_exception_by_middleware(e, request)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
backend_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
backend_1  |     response = viewfunc(request, *args, **kw)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
backend_1  |     return view_func(request, *args, **kwargs)
backend_1  |   File "/opt/project/pv/apps/wagtailoverrides/views/pages.py", line 246, in create
backend_1  |     parent_page.add_child(instance=page)
backend_1  |   File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 1013, in add_child
backend_1  |     return MP_AddChildHandler(self, **kwargs).process()
backend_1  |   File "/usr/local/lib/python3.6/site-packages/treebeard/mp_tree.py", line 387, in process
backend_1  |     newobj.path = self.node.get_last_child()._inc_path()
backend_1  | AttributeError: 'NoneType' object has no attribute '_inc_path'
backend_1  | [21/May/2019 08:33:27] "POST /admin/pages/new/article/articlepage/5/ HTTP/1.1" 500 110431```

### Technical details
python 3.6
django 2.2.1
wagtail 2.5.1

**Comment by gasman** [comment]
Hi @m-pasha,
Running the command `./manage.py fixtree` may be able to fix this. Unfortunately we aren't able to handle this as a bug report, as there are no details of how to reproduce the problem.

**Comment by m-pasha** [comment]
Thanks. its issue with **parent_page** in my code. I solved it
