### ISSUE TITLE
Elasticsearch search backends do not support ordering set by the reverse method on a QuerySet

### ISSUE THREAD

**Issue by m1kola** [wagtail/wagtail#5319]
### Issue Summary

Elasticsearch search backends do not support ordering set by the `reverse` method on a `QuerySet`.

### Steps to Reproduce

1. Setup a project with an Ealsticsearch search backend
2. Create 2 or more pages with title (or any other searchable content) containing "social".
3. Run the following code in a Django shell:
    ```python
    from wagtail.core.models import Page
    from wagtail.search.backends import get_search_backend

    search_query = 'social'
    queryset = Page.objects.order_by('first_published_at')

    sb = get_search_backend()
    results = sb.search(search_query, queryset, operator=None, order_by_relevance=False)

    for r in results[:10]:
        print(r.pk, r.title)
    ```

4. Then run the same code snippet but with with reverse set by the `QuerySet.reverse` method:
    ```python
    from wagtail.core.models import Page
    from wagtail.search.backends import get_search_backend

    search_query = 'social'
    queryset = Page.objects.order_by('first_published_at')
    queryset = queryset.reverse()

    sb = get_search_backend()
    results = sb.search(search_query, queryset, operator=None, order_by_relevance=False)

    for r in results[:10]:
        print(r.pk, r.title)
    ```

**Expected result:** on the step 4 we get pages ordered in reverse order in comparison to pages from the step 3
**Actual result:** pages ordered in the same way

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

It looks like Elasticsearch backends do not detect reverse order set using the `QuerySet.reverse` method. Only using ``QuerySet.order_by``:

https://github.com/wagtail/wagtail/blob/58135ccf6ea06095379c32e07578095545b37762/wagtail/search/backends/base.py#L120-L140

It was the reason behind #3514 (see https://github.com/wagtail/wagtail/issues/3514#issuecomment-494831614).

**Note** that `wagtail.contrib.postgres_search.backend` doesn't use `_get_order_by` method, so you will get expected results with the Postgres backend.

* Python version: 3.6.4.
* Elasticsearch 5
* Django 2.1.3 and 2.1.5
* Wagtail 2.3, 2.4, 2.5

**Comment by nutjob4life** [comment]
I'm getting an identical stack trace, but with case-insensitive ordering, i.e.:
```python
matches = MyModel.objects.child_of(self).live().public().order_by(Lower('title'))
matches = matches.search(query, order_by_relevance=False)
```
which results in 
```python
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
…
    matches = matches.search(query, order_by_relevance=False)
  File "wagtail/search/queryset.py", line 18, in search
    return search_backend.search(
  File "wagtail/search/backends/base.py", line 432, in search
    return self._search(
  File "wagtail/search/backends/base.py", line 419, in _search
    search_query_compiler.check()
  File "wagtail/search/backends/base.py", line 221, in check
    list(self._get_order_by())
  File "wagtail/search/backends/base.py", line 174, in _get_order_by
    if field_name.startswith("-"):
AttributeError: 'Lower' object has no attribute 'startswith'
```
The docs say this should be all you have to do:
![Screen Shot 2022-07-11 at 12 20 15 PM](https://user-images.githubusercontent.com/814813/178321548-2a9513b6-4ea3-49ac-a2c7-6377e6c2539e.png)
But it looks like the Elasticsearch backend makes some assumptions about what the `field_name` is.

**Comment by gasman** [comment]
@nutjob4life I think that's best treated as a separate issue to the one described here. Essentially, the Elasticsearch backend is replicating the Django Queryset API on an object that isn't a standard database query - implementing arbitrary functions such as `Lower` on `order_by` will be a much bigger task (if the Elasticsearch query language supports it at all) than just adding the `reverse` method.

**Comment by nutjob4life** [comment]
Thanks @gasman. I see the point and made [a separate issue](https://github.com/wagtail/wagtail/issues/8859).
