### ISSUE TITLE
ManyToMany field is not saved in Inline model

### ISSUE THREAD

**Issue by hazaard** [wagtail/wagtail#5432]
### Issue Summary
Having ManyToMany field inside Inline panel doesn't allow to save raising error ValueError "... needs to have a value for field "id" before this many-to-many relationship can be used."

Model.py code:
`
class Company(ClusterableModel):
    title = models.CharField(
        max_length=128
    )
    panels = [
        FieldPanel('title'),
        InlinePanel('categories', label='Categories')
    ]

class CompanyCategory(Orderable):
    company = ParentalKey('Company',
        on_delete=models.CASCADE,
        related_name='categories')
    category = models.ForeignKey(
        'wagtailcore.Page',
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='+'
    )
    service_tags = models.ManyToManyField(
        'catalogue.ServiceTag',
        blank=True)

    panels = [
        PageChooserPanel('category', 'catalogue.ServiceCategoryPage'),
        FieldPanel('service_tags')
    ]
`

Traceback:
`
Traceback (most recent call last):
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 102, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/wagtail/admin/decorators.py", line 34, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/options.py", line 367, in edit_view
    return view_class.as_view(**kwargs)(request)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/views.py", line 711, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/views.py", line 78, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/wagtail/contrib/modeladmin/views.py", line 172, in form_valid
    instance = form.save()
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/modelcluster/forms.py", line 370, in save
    formset.save(commit=commit)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/modelcluster/forms.py", line 127, in save
    self.save_m2m()  # ensures any parental-m2m fields are saved.
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/forms/models.py", line 667, in save_m2m
    form.save_m2m()
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/forms/models.py", line 441, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/db/models/fields/related.py", line 1621, in save_form_data
    getattr(instance, self.attname).set(data)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 527, in __get__
    return self.related_manager_cls(instance)
  File "/home/aiv/webapps/itrate/venv/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 840, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<CompanyCategory: CompanyCategory object (None)>" needs to have a value for field "id" before this many-to-many relationship can be used.
`

As you can see service_tags field inside CompanyCategory model is relating to 3rd model. If I switch it to ParentalManyToManyField from modelcluster, it doesn't raise error, but doesn't save values in field (probably because parental key is referencing to another model here).

**Comment by hazaard** [comment]
I've created test project to show the issue:
https://github.com/hazaard/m2mtest

**Comment by hazaard** [comment]
Did some additional checks. Looks like issue is related to modelcluster (defferred manager) rather than to wagtail. Should i open issue there and close this instead?

**Comment by perepicornell** [comment]
@hazaard, I just stumbled upon this using latest wagtail version (4.0.1). If you ended up opening the issue somewhere else, could you please share the link? Or otherwise, any tip about how you ended up solving that?
Many thanks!

**Comment by hazaard** [comment]
@perepicornell 
I haven't opened an issue anywhere. From what I see in my old repository I had to do two things:
1. Switch from ManyToManyField to modelcluster.fields.ParentalManyToManyField.
2. Use FieldPanel('service_tags', widget=django_select2.forms.Select2MultipleWidget()).

**Comment by perepicornell** [comment]
I really appreciate that, thanks!
In the current iteration, the `ParentalKey` approach worked but making the editor's life worse. I'll take a look at what you propose and see... :)
