### ISSUE TITLE
Adds support for Elasticsearch 7x ES7 backend [PR volunteer needed]

### ISSUE THREAD

**Issue by pySilver** [wagtail/wagtail#5591]
ES7 works is not yet supported. Sorry it's not a pull request but rather working solution. One may make it to PR with tests.

Backend file: `elasticsearch7.py`
```python
from wagtail.search.backends.elasticsearch2 import (
    ElasticsearchAutocompleteQueryCompilerImpl,
)
from wagtail.search.backends.elasticsearch6 import (
    Elasticsearch6Index,
    Elasticsearch6Mapping,
    Elasticsearch6SearchBackend,
    Elasticsearch6SearchQueryCompiler,
    Elasticsearch6SearchResults,
)


class Elasticsearch7Mapping(Elasticsearch6Mapping):
    pass


class Elasticsearch7Index(Elasticsearch6Index):
    def add_model(self, model):
        # Get mapping
        mapping = self.mapping_class(model)

        # Put mapping
        self.es.indices.put_mapping(
            index=self.name,
            doc_type=mapping.get_document_type(),
            body=mapping.get_mapping(),
            include_type_name=True,
        )


class Elasticsearch7SearchQueryCompiler(Elasticsearch6SearchQueryCompiler):
    mapping_class = Elasticsearch6Mapping


class Elasticsearch7SearchResults(Elasticsearch6SearchResults):
    pass


class Elasticsearch7AutocompleteQueryCompiler(
    Elasticsearch6SearchQueryCompiler, ElasticsearchAutocompleteQueryCompilerImpl
):
    pass


class Elasticsearch7SearchBackend(Elasticsearch6SearchBackend):
    mapping_class = Elasticsearch7Mapping
    index_class = Elasticsearch7Index
    query_compiler_class = Elasticsearch7SearchQueryCompiler
    autocomplete_query_compiler_class = Elasticsearch7AutocompleteQueryCompiler
    results_class = Elasticsearch7SearchResults

    def __init__(self, params):
        self.settings["settings"]["index"] = {"max_ngram_diff": 12}
        super().__init__(params)


SearchBackend = Elasticsearch7SearchBackend
```

**Comment by pySilver** [comment]
Instead of making large ngram work via settings it might be smarter to simply override settings like so:

```python
class Elasticsearch7SearchBackend(Elasticsearch6SearchBackend):
    mapping_class = Elasticsearch7Mapping
    index_class = Elasticsearch7Index
    query_compiler_class = Elasticsearch7SearchQueryCompiler
    autocomplete_query_compiler_class = Elasticsearch7AutocompleteQueryCompiler
    results_class = Elasticsearch7SearchResults

    def __init__(self, params):
        self.settings["settings"]["analysis"]["tokenizer"]["ngram_tokenizer"][
            "max_gram"
        ] = 3
        self.settings["settings"]["analysis"]["tokenizer"]["edgengram_tokenizer"][
            "max_gram"
        ] = 2
        self.settings["settings"]["analysis"]["filter"]["ngram"]["max_gram"] = 3
        self.settings["settings"]["analysis"]["filter"]["edgengram"]["max_gram"] = 1
        super().__init__(params)
```

**Comment by pySilver** [comment]
Explanation https://medium.com/@ashishstiwari/what-should-be-the-value-of-max-gram-and-min-gram-in-elasticsearch-f091404c9a14

**Comment by gasman** [comment]
Tried making a PR for this (https://github.com/gasman/wagtail/tree/feature/elasticsearch7) but it's currently failing various tests with `mapper_parsing_exception`: https://travis-ci.org/gasman/wagtail/jobs/593789361

**Comment by pySilver** [comment]
@gasman looks strange. is it running against ES7?

**Comment by gasman** [comment]
@pySilver Yes - I get the same failures as shown on Travis CI when I test locally on my [vagrant-wagtail-develop](https://github.com/wagtail/vagrant-wagtail-develop/) instance running Elasticsearch 7.4.

```
$ curl http://localhost:9200
{
  "name" : "ubuntu-bionic",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "gxE654lWQqiN4on0K5Fv_w",
  "version" : {
    "number" : "7.4.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "22e1767283e61a198cb4db791ea66e3f11ab9910",
    "build_date" : "2019-09-27T08:36:48.569419Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by pySilver** [comment]
I'll take a look at it. Should be some kind of typo or similar simple thing.

**Comment by kaedroho** [comment]
We would need to test this against our Elasticsearch test suite. You can copy https://github.com/wagtail/wagtail/blob/master/wagtail/search/tests/test_elasticsearch6_backend.py as a starting point

**Comment by pySilver** [comment]
@gasman yeah, that was a simple thing to fix. here is update:

```python
from elasticsearch import NotFoundError
from elasticsearch.helpers import bulk
from wagtail.search.backends.elasticsearch2 import (
    ElasticsearchAutocompleteQueryCompilerImpl,
)
from wagtail.search.backends.elasticsearch6 import (
    Elasticsearch6Index,
    Elasticsearch6Mapping,
    Elasticsearch6SearchBackend,
    Elasticsearch6SearchQueryCompiler,
    Elasticsearch6SearchResults,
)
from wagtail.search.index import class_is_indexed


class Elasticsearch7Mapping(Elasticsearch6Mapping):
    def get_mapping(self):
        mapping = super().get_mapping()
        return mapping[self.get_document_type()]


class Elasticsearch7Index(Elasticsearch6Index):
    def add_model(self, model):
        # Get mapping
        mapping = self.mapping_class(model)

        # Put mapping
        self.es.indices.put_mapping(index=self.name, body=mapping.get_mapping())

    def add_item(self, item):
        # Make sure the object can be indexed
        if not class_is_indexed(item.__class__):
            return

        # Get mapping
        mapping = self.mapping_class(item.__class__)

        # Add document to index
        self.es.index(
            self.name, mapping.get_document(item), id=mapping.get_document_id(item)
        )

    def add_items(self, model, items):
        if not class_is_indexed(model):
            return

        # Get mapping
        mapping = self.mapping_class(model)
        doc_type = "_doc"

        # Create list of actions
        actions = []
        for item in items:
            # Create the action
            action = {"_type": doc_type, "_id": mapping.get_document_id(item)}
            action.update(mapping.get_document(item))
            actions.append(action)

        # Run the actions
        bulk(self.es, actions, index=self.name)

    def delete_item(self, item):
        # Make sure the object can be indexed
        if not class_is_indexed(item.__class__):
            return

        # Get mapping
        mapping = self.mapping_class(item.__class__)

        # Delete document
        try:
            self.es.delete(self.name, mapping.get_document_id(item))
        except NotFoundError:
            pass  # Document doesn't exist, ignore this exception


class Elasticsearch7SearchQueryCompiler(Elasticsearch6SearchQueryCompiler):
    mapping_class = Elasticsearch6Mapping


class Elasticsearch7SearchResults(Elasticsearch6SearchResults):
    pass


class Elasticsearch7AutocompleteQueryCompiler(
    Elasticsearch6SearchQueryCompiler, ElasticsearchAutocompleteQueryCompilerImpl
):
    pass


class Elasticsearch7SearchBackend(Elasticsearch6SearchBackend):
    mapping_class = Elasticsearch7Mapping
    index_class = Elasticsearch7Index
    query_compiler_class = Elasticsearch7SearchQueryCompiler
    autocomplete_query_compiler_class = Elasticsearch7AutocompleteQueryCompiler
    results_class = Elasticsearch7SearchResults

    def __init__(self, params):
        self.settings["settings"]["index"] = {"max_ngram_diff": 12}
        super().__init__(params)


SearchBackend = Elasticsearch7SearchBackend
```

Tests output. I bet this failures are not related to ES.
```
 ~/Projects/sandbox/wagtail-pr/wagtail   feature/elasticsearch7 !2 ?2 ❯ ./runtests.py --elasticsearch7                                                                                                     17s  wagtail-Y5lYqxk1  3.7.4
Creating test database for alias 'default'...
System check identified some issues:

WARNINGS:
?: (wagtailadmin.W001) CSS for the Wagtail admin is missing
	HINT:
            Most likely you are running a development (non-packaged) copy of
            Wagtail and have not built the static assets -
            see http://docs.wagtail.io/en/latest/contributing/developing.html

            File not found: /Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/admin/static/wagtailadmin/css/normalize.css


System check identified 1 issue (0 silenced).
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../Users/Silver/.local/share/virtualenvs/wagtail-Y5lYqxk1/lib/python3.7/site-packages/Django-2.0.13-py3.7.egg/django/forms/widgets.py:126: MediaOrderConflictWarning: Detected duplicate Media files in an opposite order:
wagtailadmin/js/page-chooser-modal.js
wagtailimages/js/image-chooser.js
  MediaOrderConflictWarning,
..................................................................................................................................../Users/Silver/.local/share/virtualenvs/wagtail-Y5lYqxk1/lib/python3.7/site-packages/Django-2.0.13-py3.7.egg/django/forms/widgets.py:126: MediaOrderConflictWarning: Detected duplicate Media files in an opposite order:
wagtailadmin/js/page-chooser-modal.js
wagtailimages/js/image-chooser.js
  MediaOrderConflictWarning,
..........................................................................................................................................EE.........................................................................................................................................................................................................................................................................................................................................................................................................................................EEE............................../Users/Silver/.local/share/virtualenvs/wagtail-Y5lYqxk1/lib/python3.7/site-packages/Django-2.0.13-py3.7.egg/django/forms/widgets.py:126: MediaOrderConflictWarning: Detected duplicate Media files in an opposite order:
wagtailadmin/js/page-chooser-modal.js
wagtailimages/js/image-chooser.js
  MediaOrderConflictWarning,
..................................................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................ss.............sss....................sssssss...................................................................................................................................................................................................................................ss...........................s.......................................................................xxx/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/search/backends/db.py:63: UserWarning: Database search backend does not support term boosting.
  warn('Database search backend does not support term boosting.')
x...................xx..............x....xxx....x..............ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss.................................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss..............................................ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
ERROR: test_has_changed (wagtail.admin.tests.test_compare.TestTagsFieldComparison)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/admin/tests/test_compare.py", line 365, in test_has_changed
    self.assertEqual(comparison.htmldiff(), 'wagtail, <span class="deletion">bird</span>, <span class="addition">motacilla</span>')
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/admin/compare.py", line 250, in htmldiff
    sm = difflib.SequenceMatcher(0, items_a, items_b)
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 213, in __init__
    self.set_seqs(a, b)
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 225, in set_seqs
    self.set_seq2(b)
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 279, in set_seq2
    self.__chain_b()
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 312, in __chain_b
    indices = b2j.setdefault(elt, [])
  File "/Users/Silver/.local/share/virtualenvs/wagtail-Y5lYqxk1/lib/python3.7/site-packages/Django-2.0.13-py3.7.egg/django/db/models/base.py", line 530, in __hash__
    raise TypeError("Model instances without primary key value are unhashable")
TypeError: Model instances without primary key value are unhashable

======================================================================
ERROR: test_hasnt_changed (wagtail.admin.tests.test_compare.TestTagsFieldComparison)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/admin/tests/test_compare.py", line 350, in test_hasnt_changed
    self.assertEqual(comparison.htmldiff(), 'wagtail, bird')
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/admin/compare.py", line 250, in htmldiff
    sm = difflib.SequenceMatcher(0, items_a, items_b)
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 213, in __init__
    self.set_seqs(a, b)
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 225, in set_seqs
    self.set_seq2(b)
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 279, in set_seq2
    self.__chain_b()
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/difflib.py", line 312, in __chain_b
    indices = b2j.setdefault(elt, [])
  File "/Users/Silver/.local/share/virtualenvs/wagtail-Y5lYqxk1/lib/python3.7/site-packages/Django-2.0.13-py3.7.egg/django/db/models/base.py", line 530, in __hash__
    raise TypeError("Model instances without primary key value are unhashable")
TypeError: Model instances without primary key value are unhashable

======================================================================
ERROR: test_cloudfront (wagtail.contrib.frontend_cache.tests.TestBackendConfiguration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/tests.py", line 60, in test_cloudfront
    'DISTRIBUTION_ID': 'frontend',
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/utils.py", line 53, in get_backends
    backend_objects[backend_name] = backend_cls(backend_config)
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/backends.py", line 118, in __init__
    import boto3
ModuleNotFoundError: No module named 'boto3'

======================================================================
ERROR: test_cloudfront_distribution_id_mapping (wagtail.contrib.frontend_cache.tests.TestBackendConfiguration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Silver/.pyenv/versions/3.7.4/lib/python3.7/unittest/mock.py", line 1209, in patched
    return func(*args, **keywargs)
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/tests.py", line 137, in test_cloudfront_distribution_id_mapping
    'www.wagtail.io': 'frontend',
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/utils.py", line 53, in get_backends
    backend_objects[backend_name] = backend_cls(backend_config)
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/backends.py", line 118, in __init__
    import boto3
ModuleNotFoundError: No module named 'boto3'

======================================================================
ERROR: test_cloudfront_validate_distribution_id (wagtail.contrib.frontend_cache.tests.TestBackendConfiguration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/tests.py", line 127, in test_cloudfront_validate_distribution_id
    'BACKEND': 'wagtail.contrib.frontend_cache.backends.CloudfrontBackend',
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/utils.py", line 53, in get_backends
    backend_objects[backend_name] = backend_cls(backend_config)
  File "/Users/Silver/Projects/sandbox/wagtail-pr/wagtail/wagtail/contrib/frontend_cache/backends.py", line 118, in __init__
    import boto3
ModuleNotFoundError: No module named 'boto3'

----------------------------------------------------------------------
Ran 3455 tests in 165.722s

FAILED (errors=5, skipped=291, expected failures=11)
Destroying test database for alias 'default'...
```
```

**Comment by pySilver** [comment]
@gasman did it work ?

**Comment by gasman** [comment]
@pySilver Please can you open a PR for this? That way we can see the test results through Travis CI - reapplying changes manually isn't a good use of anyone's time. (I did it last time as an exception because I was interested and it looked like this might be a "quick win", but it seems that's not the case now.)

Also, please see @kaedroho's comment - we need to run this against a version of the ES test suite, not just the general search tests.

**Comment by kaedroho** [comment]
Fixed by https://github.com/wagtail/wagtail/pull/5611
