### ISSUE TITLE
Decoder object

### ISSUE THREAD

**Issue by wesgarlock** [wagtail/wagtail#5655]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I'm trying to implement WebP support into my Wagtail app. I'm following wagtail 2.7a making changes I need to bring it live. Everything runs fine but when I use {% image page.photo format-webp *}. I get this error.

I've also tried Creating CustomImage classes etc., but always end in the same issue.

Have you experienced this issue in development and is there a solution?

~~~
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/wagtail/images/models.py", line 285, in get_rendition
    focal_point_key=cache_key,
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
wagtail.images.models.Rendition.DoesNotExist: Rendition matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/query.py", line 486, in get_or_create
    return self.get(**lookup), False
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
wagtail.images.models.Rendition.DoesNotExist: Rendition matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/wagtail/images/templatetags/wagtailimages_tags.py", line 102, in render
    rendition = get_rendition_or_not_found(image, self.filter)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/wagtail/images/shortcuts.py", line 13, in get_rendition_or_not_found
    return image.get_rendition(specs)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/wagtail/images/models.py", line 314, in get_rendition
    defaults={'file': File(generated_image.f, name=output_filename)}
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 657, in get_or_create
    return super(RelatedManager, self.db_manager(db)).get_or_create(**kwargs)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/query.py", line 488, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/query.py", line 522, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/query.py", line 411, in create
    obj = self.model(**kwargs)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/base.py", line 487, in __init__
    post_init.send(sender=cls, instance=self)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/db/models/fields/files.py", line 449, in update_dimension_fields
    width = file.width
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/core/files/images.py", line 19, in width
    return self._get_image_dimensions()[0]
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/core/files/images.py", line 29, in _get_image_dimensions
    self._dimensions_cache = get_image_dimensions(self, close=close)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/django/core/files/images.py", line 59, in get_image_dimensions
    p.feed(data)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/PIL/ImageFile.py", line 401, in feed
    im = Image.open(fp)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/PIL/Image.py", line 2672, in open
    im = _open_core(fp, filename, prefix)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/PIL/Image.py", line 2658, in _open_core
    im = factory(fp, filename)
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/PIL/ImageFile.py", line 103, in __init__
    self._open()
  File "/Users/wgarlock/Git/wagtaildev/lib/python3.7/site-packages/PIL/WebPImagePlugin.py", line 62, in _open
    self._decoder = _webp.WebPAnimDecoder(self.fp.read())
RuntimeError: could not create decoder object
~~~
 pip freeze
~~~
beautifulsoup4==4.6.0
boto3==1.9.151
botocore==1.12.151
certifi==2019.3.9
cffi==1.13.1
chardet==3.0.4
cycler==0.10.0
Django==2.1.13
django-modelcluster==4.4
django-storages==1.7.1
django-taggit==0.24.0
django-treebeard==4.3
djangorestframework==3.9.4
docutils==0.14
draftjs-exporter==2.1.5
html5lib==1.0.1
idna==2.8
jmespath==0.9.4
kiwisolver==1.1.0
matplotlib==3.1.1
numpy==1.17.3
Pillow==5.4.1
psycopg2==2.8.2
pycparser==2.19
pyparsing==2.4.2
PyQt5==5.13.1
PyQt5-sip==12.7.0
python-dateutil==2.8.0
pytz==2019.1
requests==2.22.0
s3transfer==0.2.0
six==1.12.0
sqlparse==0.3.0
Unidecode==1.0.23
urllib3==1.24.3
wagtail==2.6
wagtail-modelchooser==2.2.1
wagtailmodelchooser==0.3.0
webencodings==0.5.1
webp==0.1.0a15
webp-converter==4.0.1
webptools==0.0.2
Willow==1.3
~~~

**Comment by gasman** [comment]
Hi @wesgarlock,
This is an installation issue with the `pillow` library rather than a Wagtail issue - I'd suggest upgrading to the latest version of pillow (6.2.1) as a first step.

**Comment by wesgarlock** [comment]
I tried the upgrade and it still results in the same error.

**Comment by allcaps** [comment]
Pip freeze shows you have `wagtail==2.6`, should that not be `2.7rc2`?

**Comment by wesgarlock** [comment]
I changed my versions from 2.6 to 2.7r1 to 2.7r2, but I'm still encountering the decoder error. 

~~~
alabaster==0.7.12
astroid==2.3.2
Babel==2.7.0
beautifulsoup4==4.6.0
boto3==1.9.151
botocore==1.12.151
certifi==2019.3.9
cffi==1.13.1
chardet==3.0.4
curlify==2.2.1
cycler==0.10.0
Django==2.1.13
django-modelcluster==5.0
django-storages==1.7.1
django-taggit==1.1.0
django-treebeard==4.3
djangorestframework==3.9.4
docutils==0.14
draftjs-exporter==2.1.5
entrypoints==0.3
facebook-business==4.0.8
flake8==3.7.8
future==0.18.1
html5lib==1.0.1
idna==2.8
imagesize==1.1.0
isort==4.3.21
Jinja2==2.10.3
jmespath==0.9.4
kiwisolver==1.1.0
lazy-object-proxy==1.4.2
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
numpy==1.17.3
oauthlib==3.1.0
olefile==0.46
packaging==19.2
Pillow==6.2.1
psycopg2==2.8.2
pycodestyle==2.5.0
pycparser==2.19
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.4.3
pyparsing==2.4.2
PyQt5==5.13.1
PyQt5-sip==12.7.0
python-dateutil==2.8.0
python-facebook-api==0.5.1
pytz==2019.1
requests==2.22.0
requests-oauthlib==1.2.0
s3transfer==0.2.0
six==1.12.0
snowballstemmer==2.0.0
Sphinx==2.2.0
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sqlparse==0.3.0
typed-ast==1.4.0
Unidecode==1.0.23
urllib3==1.24.3
wagtail==2.7rc1
wagtail-modelchooser==2.2.1
wagtailmodelchooser==0.3.0
webencodings==0.5.1
webp==0.1.0a15
webp-converter==4.0.1
webptools==0.0.2
Willow==1.3
wrapt==1.11.2
~~~
