### ISSUE TITLE
Base Command integration, .publish() method results in `people.models.DoesNotExist`

### ISSUE THREAD

**Issue by SgtPorkChops** [wagtail/wagtail#5690]
I am attempting to create a BaseCommand to call from the command line that takes a CSV file, iterates through each entry and for each row, assembles a python object (Unless it already exists). I have attached the script file.

Upon creating a page object in the `wagtailcore_page` table, I called the `.save_revision() `method to create the appropriate entry in the `wagtailcore_pagerevision` table. Unfortunately, this registers the page as having unpublished changes so I tried to call the `.publish()` method to trigger the publication (and linking of the `page_revision_id` field in the `wagtailcore_page` table).

It works Hunky-Dorey on my local SQLlite database but the minute I run it on my production server, it goes belly up with the following error message:

```console
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1427: RuntimeWarning: DateTimeField Page.first_published_at received a naive datetime (2019-10-29 08:19:32.228211) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1427: RuntimeWarning: DateTimeField Page.last_published_at received a naive datetime (2019-10-29 09:16:02.702390) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1427: RuntimeWarning: DateTimeField Page.latest_revision_created_at received a naive datetime (2019-10-29 09:16:02.702390) while time zone support is active.
  RuntimeWarning)
Traceback (most recent call last):
  File "/usr/share/nginx/html/SASDGHUB_Django/articles/management/commands/InnovationBridgeImport.py", line 72, in handle
    title=str(row[1]),
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
articles.models.DoesNotExist: InnovationBridgeEntries matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/share/nginx/html/SASDGHUB_Django/articles/management/commands/InnovationBridgeImport.py", line 134, in handle
    NewInnovation.save_revision(user=Owner).publish()
  File "/usr/local/lib/python3.6/site-packages/wagtail/core/models.py", line 1592, in publish
    page = self.as_page_object()
  File "/usr/local/lib/python3.6/site-packages/wagtail/core/models.py", line 1570, in as_page_object
    return self.page.specific.with_content_json(self.content_json)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/wagtail/core/models.py", line 590, in specific
    return content_type.get_object_for_this_type(id=self.id)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/contenttypes/models.py", line 168, in get_object_for_this_type
    return self.model_class()._base_manager.using(self._state.db).get(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
people.models.DoesNotExist: PeoplePage matching query does not exist.
```

Here is my code that deals with the publishing:
```python
# Now retrieve the entry we just made:
NewInnovation = InnovationBridgeEntries.objects.get(
    InnovationID=int(row[0]),
    content=str(row[2]),
    CSIRURL=str(row[3]),
    title=str(row[1]),
)

Owner = User.objects.get(id=1)
NewInnovation.save_revision(user=Owner).publish()

print("Creation of new entry successful.")
```

Just as a side note, I have confirmed that the user exists, and from what I can tell, it imports fine or a line or few then all of a sudden crashes. From what I'm getting, it cant find that user again?

**Comment by gasman** [comment]
Hi @SgtPorkChops,
There's no information here to indicate that this is a Wagtail bug rather than an error in your code - all we can see from the code you've given is that you're performing a lookup on `InnovationBridgeEntries`, and that lookup is failing.

If you believe this is a Wagtail bug, please open a new issue with all of the requested details in the form filled in - in particular, the steps to reproduce this issue independently.

If you're looking for support with Wagtail, please use the channels listed in [the Support page in the documentation](https://docs.wagtail.io/en/stable/support.html).
