### ISSUE TITLE
Migrations fail when using the non-default database `manage.py migrate --database=foo`

### ISSUE THREAD

**Issue by mikemonteith** [wagtail/wagtail#5846]
### Issue Summary

Wagtail migrations fail when using the --database flag. 

https://docs.djangoproject.com/en/3.0/ref/django-admin/#cmdoption-migrate-database

### Steps to Reproduce

Add a secondary database to a wagtail project.

e.g in the bakerydemo
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'bakerydemodb')
    },
    'secondary': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'bakerydemosecondarydb')
    },
}
```

Run migrations on the non-default database
`python manage.py migrate --database=secondary`

Results in stack trace:
```
Operations to perform:
  Apply all migrations: admin, auth, base, blog, breads, contenttypes, locations, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailsearchpromotions, wagtailusers
Running migrations:
  Applying wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field...Traceback (most recent call last):
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_content_type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/wagtail/core/migrations/0001_squashed_0016_change_page_url_path_to_text_field.py", line 19, in initial_data
    app_label='wagtailcore'
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/models/query.py", line 559, in get_or_create
    return self.get(**kwargs), False
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1144, in execute_sql
    cursor.execute(sql, params)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/mike/dev/nhsdigital/venvs/bakerydemo/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_content_type
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

* Python version: 3.7.6
* Django version: 3.0.3
* Wagtail version: 2.8

### Explanation

I think this is because the database migrations correctly run on the specified database, but the initial data setup is run against the default database.

**Comment by Piezoid** [comment]
I got this error with `loaddata` on a non default sqlite3 database, freshly migrated from zero.

**Comment by BigWhale** [comment]
Apparently this is still an issue with Wagtail 6.0.

**Comment by gasman** [comment]
I'll close this in favour of #11237, which covers the current state of play regarding support for multiple databases. In short - if you define multiple databases, you are expected to define a [database router](https://docs.djangoproject.com/en/5.0/topics/db/multi-db/#topics-db-multi-db-routing) such as https://github.com/gasman/wagtail-multiple-databases/blob/main/multipledatabases/routers.py to ensure that Wagtail's tables in the 'default' database and no others.

Wagtail does not currently support configurations where its tables exist on non-default databases - such as the configuration you get if you don't specify a router - as it's not clear whether there are any valid use-cases for this. If you believe this should be supported, your input on #11237 would be very welcome.
