### ISSUE TITLE
Migrations fail when using Djongo as database driver

### ISSUE THREAD

**Issue by Tafhim** [wagtail/wagtail#5873]
### Issue Summary

I know that it might not be the case that MongoDB is supported. But since I did not find anywhere stating that it wasn't supported, I gave it a go with Wagtail. It was working to some extent until at one point one of the migrations failed. That migration literally has nothing which probably is the cause of this failure.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Configure you DB driver config to something like the following. Note: You will need to install Djongo `pip install djongo`
`DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'dbname',
        'CLIENT': {
            'host': 'localhost',
            'port': 27017,
            'username': 'admin',
            'password': 'password',
        }
    }
}`
3. Then run the migration `python manage.py migrate`

And this is what I get.
`Operations to perform:
  Apply all migrations: admin, auth, contenttypes, home, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailredirects, wagtailsearch, wagtailusers
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field... OK
  Applying wagtailcore.0017_change_edit_page_permission_description... OK
  Applying wagtailcore.0018_pagerevision_submitted_for_moderation_index... OK
  Applying wagtailcore.0019_verbose_names_cleanup... OK
  Applying wagtailcore.0020_add_index_on_page_first_published_at... OK
  Applying wagtailcore.0021_capitalizeverbose... OK
  Applying wagtailcore.0022_add_site_name... OK
  Applying wagtailcore.0023_alter_page_revision_on_delete_behaviour... OK
  Applying wagtailcore.0024_collection... OK
  Applying wagtailcore.0025_collection_initial_data... OK
  Applying wagtailcore.0026_group_collection_permission... OK
  Applying wagtailcore.0027_fix_collection_path_collation... OK
  Applying wagtailcore.0024_alter_page_content_type_on_delete_behaviour... OK
  Applying wagtailcore.0028_merge... OK
  Applying wagtailcore.0029_unicode_slugfield_dj19... OK
  Applying wagtailcore.0030_index_on_pagerevision_created_at... OK
  Applying wagtailcore.0031_add_page_view_restriction_types... OK
  Applying wagtailcore.0032_add_bulk_delete_page_permission... OK
  Applying wagtailcore.0033_remove_golive_expiry_help_text... OK
  Applying wagtailcore.0034_page_live_revision... OK
  Applying wagtailcore.0035_page_last_published_at... OK
  Applying wagtailcore.0036_populate_page_last_published_at...Traceback (most recent call last):
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 824, in parse
    return handler(self, statement)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 953, in _update
    self._query = UpdateQuery(self.db, self.connection_properties, sm, self._params)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 309, in __init__
    super().__init__(*args)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 72, in __init__
    self.parse()
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 339, in parse
    kwargs.update(self.set_columns.to_mongo())
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/converters.py", line 348, in to_mongo
    '$set': {
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/converters.py", line 350, in <dictcomp>
    if sql.rhs_indexes is not None else None
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/__init__.py", line 200, in rhs_indexes
    raise SQLDecodeError
djongo.sql2mongo.SQLDecodeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/migrations/migration.py", line 121, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/wagtail/core/migrations/0036_populate_page_last_published_at.py", line 9, in forwards_func
    Page.objects.filter(has_unpublished_changes=False).update(last_published_at=F('latest_revision_created_at'))
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/models/query.py", line 741, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1469, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/cursor.py", line 48, in execute
    self.result = Result(
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 753, in __init__
    self.parse()
  File "/home/tafhim/test/wagtail-blog/tafhim-venv/lib/python3.8/site-packages/djongo/sql2mongo/query.py", line 846, in parse
    raise exe from e
djongo.sql2mongo.SQLDecodeError: FAILED SQL: UPDATE "wagtailcore_page" SET "last_published_at" = "wagtailcore_page"."latest_revision_created_at" WHERE "wagtailcore_page"."has_unpublished_changes" = %(0)s
Params: (False,)
Version: 1.3.1`

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.8.1
* Django version: 2.2.11.
* Wagtail version: 2.8.
* Browser version: Chrome 80.

**Comment by gasman** [comment]
Hi @Tafhim,
No, Djongo isn't supported, sorry - the supported database backends are detailed at https://github.com/wagtail/wagtail#compatibility .
