### ISSUE TITLE
wagtail admin issue

### ISSUE THREAD

**Issue by janebaik** [wagtail/wagtail#5890]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue.
my python manage.py runserver complies as in 
when i run python manage.py runserver the terminal gives me back this

System check identified no issues (0 silenced).
March 19, 2020 - 06:23:37
Django version 3.0.4, using settings 'setisite2.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

But when i go to the local host and place /admin it gives me this

downbelow 
my basic question is that i cannout find the bug anywhere. Where should i look at. 

Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 108, in wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/wagtail/admin/auth.py", line 168, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/wagtail/admin/views/home.py", line 116, in home
    RecentEditsPanel(request),
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/wagtail/admin/views/home.py", line 98, in __init__
    pages = Page.objects.specific().in_bulk(page_keys)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/models/query.py", line 698, in in_bulk
    return {getattr(obj, field_name): obj for obj in qs}
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/wagtail/core/query.py", line 393, in specific_iterator
    pages_by_type[content_type] = {page.pk: page for page in pages}
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/debug_toolbar/panels/sql/tracking.py", line 133, in _record
    return method(sql, params)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/janebaik/djangoprojects/myvenv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/sqlite3/dbapi2.py", line 64, in convert_date
    return datetime.date(*map(int, val.split(b"-")))
ValueError: invalid literal for int() with base 10: b'17 21:47:00'

### Steps to Reproduce

1. (for example) Start a new project with `wagtail start myproject`
2. Edit models.py as follows...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by gasman** [comment]
Hi @janebaik - thanks for the report.
This can happen on sqlite when a field has been changed from `DateTimeField` to `DateField` and the existing data has not been updated - sqlite does not have true date/time field types. I would advise using PostgreSQL as the database backend instead.

Closing as this is a Django / sqlite issue rather than a Wagtail one.
