### ISSUE TITLE
Wagtail migration doesn't respect --run-syncdb

### ISSUE THREAD

**Issue by DavHau** [wagtail/wagtail#5918]
Running `migrate` under wagtail creates tables with data despite using `--run-syncdb`.
As a result of this, it is difficult to load a database dump via `./manage.py loaddata`. It fails because some tables are not empty.
There are open tickets where people come up with unnecessary complicated hacks to load data:
- https://github.com/wagtail/wagtail/issues/4472
- https://github.com/wagtail/wagtail/issues/5464

This would all become quite simple if the wagtail migration would respect `--run-syncdb`

### Issue Summary

When running `./manage.py migrate --run-syncdb`, some wagtail tables are initialized with data which they should not.
At least the following tables are not empty:
 - " wagtailcore_page"
 - " wagtailcore_site"
 - " wagtailcore_groupcollectionpermission"
 - " wagtailcore_grouppagepermission"

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Run `./manage.py migrate --run-syncsb`
3. Inspect tables listed above

### Expected Behaviour
When running migrations with `--run-syncdb` on an empty database, empty tables should be created without any data

### Technical details

* Python version: 3.7.5
* Django version: 3.0.4
* Wagtail version: 2.8

**Comment by Cheradenine** [comment]
not sure if this is related. I'm trying to do loaddata and getting an exception:
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/projects/test/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/projects/test/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/projects/test/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/projects/test/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/projects/test/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/projects/test/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/projects/test/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/projects/test/lib/python3.7/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/projects/test/lib/python3.7/site-packages/django/db/models/base.py", line 795, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/projects/test/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/projects/test/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/projects/test/lib/python3.7/site-packages/wagtail/search/signal_handlers.py", line 13, in post_save_signal_handler
    index.insert_or_update_object(instance)
  File "/projects/test/lib/python3.7/site-packages/wagtail/search/index.py", line 150, in insert_or_update_object
    indexed_instance = get_indexed_instance(instance)
  File "/projects/test/lib/python3.7/site-packages/wagtail/search/index.py", line 143, in get_indexed_instance
    if check_exists and not type(indexed_instance).get_indexed_objects().filter(pk=indexed_instance.pk).exists():
AttributeError: Problem installing fixture '/projects/test/extinctionr/db.json': type object 'ArticleRevision' has no attribute 'get_indexed_objects'
```
Django docs suggest not running post save signal handlers during loaddata:
https://docs.djangoproject.com/en/3.0/ref/django-admin/#what-s-a-fixture

Is this the kind of failure this issue is causing or is this a different issue?

**Comment by eeintech** [comment]
I ran into the same issue (database is not empty after running migrate with `--run-syncdb` option) and this is a real problem for migrating to a new database...

**Comment by gasman** [comment]
@DavHau @eeintech Can you point me to any documentation / code that confirms that `./manage.py migrate --run-syncdb` is supposed to create empty database tables (or, better, gives instructions for what an app has to do to ensure that this happens)?

The [only reference I can find in the Django docs](https://docs.djangoproject.com/en/3.0/ref/django-admin/#cmdoption-migrate-run-syncdb) says that the option "allows creating tables for apps without migrations." Perhaps you're interpreting that to mean "it will cause migration files to be ignored and create tables based purely on models.py instead"? That's not how I interpret it: I understand it as "IF you have an app without migrations, THEN this will cause tables to be created based on models.py rather than ./manage.py skipping over the app entirely". Since Wagtail's apps _do_ have migrations, this option is not applicable.

@Cheradenine I don't think there's any connection between that error and the issue described here - please open a new issue with full details.

**Comment by eeintech** [comment]
@gasman On my side I am trying to migrate from SQLite3 to a PostgreSQL database, so I followed this guide:
https://gist.github.com/sirodoht/f598d14e9644e2d3909629a41e3522ad

It does say to run it with `--run-syncdb` option, which in my mind is the way to create empty tables which will be filled up with the `loaddata` command later on.

I ran into a separate issue (I believe related to #6069) but after configuring my PostgreSQL database as default in my `base.py` Django settings file, I ran into another error:
```$ ./manage.py loaddata datadump.json
Traceback (most recent call last):
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "wagtailcore_page_path_key"
DETAIL:  Key (path)=(00010001) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)

(...troncated ...)

django.db.utils.IntegrityError: Problem installing fixture '/home/eeintech/eeintech/datadump.json': Could not load wagtailcore.Page(pk=7): duplicate key value violates unique constraint "wagtailcore_page_path_key"
DETAIL:  Key (path)=(00010001) already exists.
```

Indeed:
```
>>> from wagtail.core.models import Page
>>> Page.objects.all()
<PageQuerySet [<Page: Root>, <Page: Welcome to your new Wagtail site!>]>
```

I deleted the Page instance but still running into a content type error when running `loaddata`:
```
django.db.utils.IntegrityError: Problem installing fixture '/home/eeintech/eeintech/datadump_content.json': Could not load contenttypes.ContentType(pk=16): duplicate key value violates unique constraint "django_content_type_app_label_model_76bd3d3b_uniq"
DETAIL:  Key (app_label, model)=(wagtailsearch, query) already exists.
```

And can't find a way to delete the initial content load from the shell:
```>>> from django.contrib.contenttypes.models import ContentType
>>> ContentType.objects.all().delete()
Traceback (most recent call last):
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/db/backends/base/base.py", line 243, in _commit
    return self.connection.commit()
psycopg2.errors.ForeignKeyViolation: update or delete on table "django_content_type" violates foreign key constraint "wagtailcore_page_content_type_id_c28424df_fk_django_co" on table "wagtailcore_page"
DETAIL:  Key (id)=(1) is still referenced from table "wagtailcore_page".
```

So I've tried to dump the data exluding content types `python manage.py dumpdata --exclude=contenttypes --exclude=auth.Permission > dumpdata.json` as a workaround ([suggested here](https://coderwall.com/p/kogbla/django-fixture-dumpdata-loaddata-and-integrity-error)) but no luck:
```
$ ./manage.py loaddata datadump_nocontent.json
Traceback (most recent call last):
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/contrib/contenttypes/models.py", line 110, in get_for_id
    ct = self._cache[self.db][id]
KeyError: 64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/wagtail/core/models.py", line 936, in get_indexed_instance
    return self.specific
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/wagtail/core/models.py", line 620, in specific
    content_type = ContentType.objects.get_for_id(self.content_type_id)
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/contrib/contenttypes/models.py", line 114, in get_for_id
    ct = self.get(pk=id)
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/eeintech/virtualenv/eeintech/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 417, in get
    self.model._meta.object_name
django.contrib.contenttypes.models.DoesNotExist: ContentType matching query does not exist.
```

Anyway, I digress...

What's your proposed way to be able to create tables but not load initial data?
Better yet, what your proposed way for migrating data from one database to another?

Thanks a lot.

**Comment by gasman** [comment]
`./manage.py migrate` followed by `./manage.py flush` should give you an empty database with all tables intact.
