### ISSUE TITLE
Copying a page with a unique field raises a ValidationError when the page has been successively published and unpublished

### ISSUE THREAD

**Issue by thibaudmartinez** [wagtail/wagtail#5966]
Hi there,

First of all, many thanks for your hard work on Wagtail, it's a really nice piece of software!

I ran into this issue recently.

### Issue Summary

Attempting to copy a page with a unique field will raise a ValidationError when the page you're trying to copy has the unique field filled and has been successively published and unpublished. The error indicates that the unique field already exists even though it is part of `exclude_fields_in_copy`. 

### Steps to Reproduce

1. Start a new project
```
wagtail start mysite && cd mysite
pip install -r requirements.txt
```

2. Add the following model in `home/models.py`.

```python
from django.db import models
from wagtail.core.models import Page
from wagtail.admin.edit_handlers import FieldPanel


class MyPage(Page):
    my_unique_field = models.CharField(
        max_length=250, blank=True, null=True, unique=True
    )

    exclude_fields_in_copy = ["my_unique_field"]

    content_panels = Page.content_panels + [
        FieldPanel("my_unique_field"),
    ]
```
3. Create and apply the migrations. Then create a superuser and start the server.

```
./manage.py makemigrations
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver
```
4. Create a new page of type MyPage under the page Home and publish it. Don't forget to fill the field `my_unique_field`!

![image](https://user-images.githubusercontent.com/22032123/79637075-7067cc80-817c-11ea-99bf-f17e29992b48.png)

5. Then, click edit on the page you've just created and unpublish the page.

6.  Now, still from the Home page view, try to copy the page using the button **MORE**. Change the slug and hit **COPY THIS PAGE**.

![image](https://user-images.githubusercontent.com/22032123/79637159-3519cd80-817d-11ea-963d-6f851e640e15.png)

7. You will get a ValidationError.

````python
Internal Server Error: /admin/pages/4/copy/
Traceback (most recent call last):
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 108, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/wagtail/admin/auth.py", line 168, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/wagtail/admin/auth.py", line 59, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/wagtail/admin/views/pages.py", line 905, in copy
    user=request.user,
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/wagtail/core/models.py", line 1199, in copy
    latest_revision_as_page_revision = latest_revision.save_revision(user=user, changed=False)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/wagtail/core/models.py", line 644, in save_revision
    self.full_clean()
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/wagtail/core/models.py", line 445, in full_clean
    super().full_clean(*args, **kwargs)
  File "/home/thibaud/workspace/bugs/copy-unique-field/env/lib/python3.7/site-packages/django/db/models/base.py", line 1222, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'my_unique_field': ['My page with this My unique field already exists.']}
````

This bug involves the validation of the new *latest_revision* that is created when the page is copied. 
As the field *my_unique_field* in *latest_revision* is - as expected - not unique, the pre-save validation of the page fails. Altering, the method `validate_unique(self, exclude=None)` seems to be a way to fix the problem.

However, it is not clear why I have only been able to reproduce the bug by successively publishing and unpublishing the source page.

I would be curious to hear your take on this issue.

Thanks in advance!

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.7.4
* Django version: 3.0.5
* Wagtail version: 2.8.1
* Browser version: Google Chrome 81

**Comment by rgs258** [comment]
In case it helps, I use this code:
```
    def copy(self, *args, **kwargs):
        """
        Override copy; removes fform_id when copying the form.

        :param args:
        :param kwargs:
        :return:
        """
        update_attrs = {"fform_id": None}
        if kwarg_update_attrs := kwargs.pop('update_attrs', None):
            update_attrs.update(kwarg_update_attrs)
        super().copy(*args, update_attrs=update_attrs, **kwargs)
```

**Comment by johncarter-phntm** [comment]
@rgs258 it looks like since 3.0 `exclude_fields_in_copy = ["fform_id", "my_other_unique_field"]` is the cleaner solution.

 https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#wagtail.models.Page.exclude_fields_in_copy
