### ISSUE TITLE
Unique constraints on a page superclass throw a ValidationError

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6023]
As reported by eon01 on the Wagtail slack:

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit home/models.py as follows:
```
from django.db import models

from wagtail.admin.edit_handlers import FieldPanel
from wagtail.core.models import Page


class HomePage(Page):
    pass

class ClassA(Page):
    # some unique field here
    link = models.URLField("link", unique=True, blank=False, null=True)

class ClassB(ClassA):
    content_panels = Page.content_panels +  [
        FieldPanel('link'),
    ]
```

3. makemigrations / migrate / createsuperuser / runserver
4. Log in to admin, create a page of type "Class B", fill in "https://wagtail.io" as the link and hit Publish

Expected: page should be created and published successfully
Actual: ValidationError `{'link': ['Class a with this Link already exists.']}`

Traceback:

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/admin/pages/add/home/classb/3/

Django Version: 3.0.4
Python Version: 3.6.8
Installed Applications:
['home',
 'search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/vagrant/wagtail/wagtail/admin/urls/__init__.py", line 109, in wrapper
    return view_func(request, *args, **kwargs)
  File "/vagrant/wagtail/wagtail/admin/auth.py", line 188, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/wagtail/wagtail/admin/views/pages.py", line 251, in create
    revision.publish()
  File "/vagrant/wagtail/wagtail/core/models.py", line 1744, in publish
    page.save()
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/vagrant/wagtail/wagtail/core/models.py", line 493, in save
    self.full_clean()
  File "/vagrant/wagtail/wagtail/core/models.py", line 467, in full_clean
    super().full_clean(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.6/site-packages/django/db/models/base.py", line 1222, in full_clean
    raise ValidationError(errors)

Exception Type: ValidationError at /admin/pages/add/home/classb/3/
Exception Value: {'link': ['Class a with this Link already exists.']}
```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.6.8
* Django version: 3.0.4
* Wagtail version: master (2.10a0)
* Browser version: Chrome 81, OS X 10.14.6

**Comment by ankit02327** [comment]
Hi, I’d like to work on this issue if it’s still available. I’ll start by reproducing the bug locally and investigating how the unique field validation behaves across inherited Page models during publish.
