### ISSUE TITLE
Error docker wagtail with debug False

### ISSUE THREAD

**Issue by Allan-Nava** [wagtail/wagtail#6055]
I got this error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 828, in _resolve_lookup
    current = current[bit]
  File "/usr/local/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'self'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 834, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'self'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 842, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'self'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [self] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f25da699ef0>>, 'request': <WSGIRequest: GET '/favicon.ico'>, 'user': <SimpleLazyObject: <function AuthenticationMiddleware.process_request.<locals>.<lambda> at 0x7f25da727a70>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f25da697f50>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f25da697b10>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}, 'ENV': 'PROD', 'VIEW_NAME': '', 'API_URL': 'https://api.justfit.live/', 'MEDIA_API_URL': 'https://api.justfit.live', 'CDN_URL': '/staticfiles/', 'WEBRTC_URL': 'https://reza.ies-italia.it/call', 'KEYCLOAK_URL': 'https://auth.ies-italia.it/auth', 'KEYCLOAK_REALM': 'fitwithme', 'KEYCLOAK_CLIENT': 'dev', 'SCALEDRONE_URL': 'https://sio.justfit.live/', 'EVENT_URL': '/en/event/', 'MY_VIDEO_URL': '/en/on-demand/', 'MY_EVENT_URL': '/en/rooms/', 'VIDEOS_URL': '/en/videos/', 'VIDEO_URL': '/en/videos/', 'TRAINER_URL': '/en/trainers/channel/', 'ROOM_EDIT_URL': '', 'VIDEO_EDIT_URL': '', 'wagtailmenus_vals': <SimpleLazyObject: <function wagtailmenus.<locals>._get_wagtailmenus_vals at 0x7f25da63a050>>}, {}, {'request_path': '/favicon.ico', 'exception': 'Resolver404'}, {'block': <Block Node: title_suffix. Contents: [<TextNode: '\n                '>, <WithNode>, <TextNode: '\n            '>]>}]
[22/May/2020 08:39:32] ERROR [django.request:228] Internal Server Error: /favicon.ico
```

**Comment by zerolab** [comment]
Hi @Allan-Nava, this looks like an issue with your template.
Can you please join the Wagtail Slack #support channel for support queries like this (see https://github.com/wagtail/wagtail/wiki/Slack). Do provide further context to this (e.g. your template) in the #support channel

Thank you.

**Comment by Allan-Nava** [comment]
But for this problem? 

File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/loader_tags.py", line 53, in render
    result = self.nodelist.render(context)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/wagtailmenus/templatetags/menu_tags.py", line 41, in main_menu
    **kwargs
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/wagtailmenus/models/menus.py", line 1070, in render_from_tag
    **kwargs
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/wagtailmenus/models/menus.py", line 97, in render_from_tag
    **kwargs
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/wagtailmenus/models/menus.py", line 110, in _get_render_prepared_object
    ctx_vals = cls._create_contextualvals_obj_from_context(context)
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/wagtailmenus/models/menus.py", line 134, in _create_contextualvals_obj_from_context
    context['request'],
  File "/Users/joi/.local/share/virtualenvs/seafy-portal-lite-IIjt4mo4/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)

**Comment by gasman** [comment]
Yes, this should go to the support channel too - we don't provide a debugging service here.
