### ISSUE TITLE
Support OpenAPI Schema generation for Wagtail API

### ISSUE THREAD

**Issue by Kokozzi** [wagtail/wagtail#6209]
### Issue Summary

It's not possible to generate OpenAPI Schema for WagtailAPI. I tried different ways, including [drf-yasg](https://github.com/axnsan12/drf-yasg) package and default [DRF schema generator](https://www.django-rest-framework.org/api-guide/schemas/), but they use mostly the same mechanism and raised Exceptions are common.

First exception is related with `wagtailapi_router` attribute of `request`, which is special for Wagtail API requests.

<details>

<summary>Traceback</summary>

```
2020-07-06 09:29:04,931 django.request  ERROR    Internal Server Error: /openapi
Traceback (most recent call last):
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/request.py", line 409, in __getattr__
    return getattr(self._request, attr)
AttributeError: 'WSGIRequest' object has no attribute 'wagtailapi_router'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/main/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/main/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/main/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/main/.venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/main/.venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/schemas/views.py", line 48, in handle_exception
    return super().handle_exception(exc)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/schemas/views.py", line 37, in get
    schema = self.schema_generator.get_schema(request, self.public)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/schemas/openapi.py", line 64, in get_schema
    paths = self.get_paths(None if public else request)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/schemas/openapi.py", line 47, in get_paths
    operation = view.schema.get_operation(path, method)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/schemas/openapi.py", line 95, in get_operation
    operation['operationId'] = self._get_operation_id(path, method)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/schemas/openapi.py", line 130, in _get_operation_id
    name = self.view.get_serializer_class().__name__
  File "/main/.venv/lib/python3.8/site-packages/wagtail/api/v2/views.py", line 316, in get_serializer_class
    return self._get_serializer_class(self.request.wagtailapi_router, model, fields_config, show_details=show_details)
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/request.py", line 411, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'wagtailapi_router'
```

</details>

Second exception was already mentioned at [this comment](https://github.com/wagtail/wagtail/pull/4922#issuecomment-626399255), but as I can find, it was not transferred to separate issue.

<details>

<summary>Traceback</summary>

```
2020-07-06 09:52:57,513 drf_yasg.inspectors.base WARNING  view's PagesAPIViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/main/.venv/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 50, in call_view_method
    return view_method()
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/main/.venv/lib/python3.8/site-packages/wagtail/api/v2/views.py", line 298, in get_serializer_class
    model = type(self.get_object())
  File "/main/.venv/lib/python3.8/site-packages/wagtail/api/v2/views.py", line 449, in get_object
    base = super().get_object()
  File "/main/.venv/lib/python3.8/site-packages/rest_framework/generics.py", line 88, in get_object
    assert lookup_url_kwarg in self.kwargs, (
AssertionError: Expected view PagesAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
```

</details>

This `AssertionError` appears for each of Wagtail APIViewSet (PagesAPIViewSet, DocumentsAPIViewSet, ImagesAdminAPIViewSet, etc.)

### Steps to Reproduce

1. Enable WagtailAPI as mentioned at [this documentation section](https://docs.wagtail.io/en/stable/advanced_topics/api/v2/configuration.html)

First exception:
2. Install `pyyaml` package for DRF Schema generation
3. Enable dynamic schema based on [this DRF docs section](https://www.django-rest-framework.org/api-guide/schemas/#generating-a-dynamic-schema-with-schemaview)
4. Open dynamic schema URL at browser
5. `AttributeError: 'Request' object has no attribute 'wagtailapi_router'` exception will appear at console

Second exception:
2. Install [drf-yasg](https://github.com/axnsan12/drf-yasg)
3. Enable generating schema as mentioned at [this drf-yasg docs section](https://drf-yasg.readthedocs.io/en/stable/readme.html#quickstart)
4. Open Swagger URL at browser
5. Several exceptions will appear at console:
 - `AttributeError: 'Request' object has no attribute 'wagtailapi_router'` exception will appear
 - ```AssertionError: Expected view PagesAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.``` for each of WagtailAPI ViewSets

This issue can be reproduced as described on a fresh Wagtail project.

### Technical details

* Python version: 3.8.2
* Django version: 2.2.14
* Wagtail version: 2.9.1
* DRF version: 3.11.0

**Comment by jayvdb** [comment]
@Kokozzi would you mind trying with https://github.com/tfranzel/drf-spectacular , and reporting any problems found?  It typicallu is actively developed.  And it typically does not throw exceptions; instead it emits warnings for components it doesnt understand.

**Comment by educolo** [comment]
I have the same messages trying to use drf-yags.
Using drf-spectacular I have these:

```
$ python manage.py spectacular --file schema.yml
Error #0: Exception raised while getting serializer from DocumentsAdminAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'Request' object has no attribute 'wagtailapi_router')
Error #1: Exception raised while getting serializer from DocumentsAdminAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: Expected view DocumentsAdminAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.)
Error #2: Exception raised while getting serializer from ImagesAdminAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'Request' object has no attribute 'wagtailapi_router')
Error #3: Exception raised while getting serializer from ImagesAdminAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: Expected view ImagesAdminAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.)
Error #4: Exception raised while getting serializer from PagesAdminAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'Request' object has no attribute 'wagtailapi_router')
Error #5: Exception raised while getting serializer from PagesAdminAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: Expected view PagesAdminAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.)
Error #6: Unable to guess serializer for LogoutView. This is graceful fallback handling for APIViews. Consider using GenericAPIView as view base class, if view is under your control. ignoring view for now. 
Error #7: Exception raised while getting serializer from DocumentsAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'Request' object has no attribute 'wagtailapi_router')
Error #8: Exception raised while getting serializer from DocumentsAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: Expected view DocumentsAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.)
Error #9: Exception raised while getting serializer from ImagesAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'Request' object has no attribute 'wagtailapi_router')
Error #10: Exception raised while getting serializer from ImagesAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: Expected view ImagesAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.)
Error #11: Exception raised while getting serializer from PagesAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: 'Request' object has no attribute 'wagtailapi_router')
Error #12: Exception raised while getting serializer from PagesAPIViewSet. Hint: Is get_serializer_class() returning None or is get_queryset() not working without a request? Ignoring the view for now. (Exception: Expected view PagesAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.)
Warning #0: operationId "admin_api_main_documents_retrieve" has collisions [('/admin/api/main/documents/', 'get'), ('/admin/api/main/documents/{id}/', 'get')]. resolving with numeral suffixes.
Warning #1: operationId "admin_api_main_images_retrieve" has collisions [('/admin/api/main/images/', 'get'), ('/admin/api/main/images/{id}/', 'get')]. resolving with numeral suffixes.
Warning #2: operationId "admin_api_main_pages_retrieve" has collisions [('/admin/api/main/pages/', 'get'), ('/admin/api/main/pages/{id}/', 'get')]. resolving with numeral suffixes.
Warning #3: operationId "api_documents_retrieve" has collisions [('/api/documents/', 'get'), ('/api/documents/{id}/', 'get')]. resolving with numeral suffixes.
Warning #4: operationId "api_images_retrieve" has collisions [('/api/images/', 'get'), ('/api/images/{id}/', 'get')]. resolving with numeral suffixes.
Warning #5: operationId "api_pages_retrieve" has collisions [('/api/pages/', 'get'), ('/api/pages/{id}/', 'get')]. resolving with numeral suffixes.

Schema generation summary:
Warnings: 6 (6 unique)
Errors:   80 (13 unique)

```

**Comment by moonburnt** [comment]
Just encountered this issue too. I guess the only solution for now is to manually specify schemas for wagtail's endpoints. Or try to find out if its possible to attach middleware to drf-yasg's endpoint discovery logic

**Comment by berzi** [comment]
I use DRF Spectacular. The issues are in how Wagtail requires a request for things like generating a viewset's queryset (specifically because it adds the API router to the request itself, which seems rather unorthodox), though this [can be worked around](https://github.com/tfranzel/drf-spectacular/issues/141#issuecomment-692345656), and in a few more oddities that Wagtail does (described a few comments after the one I just linked).

To be fair, I don't think it would be easy for Wagtail to change its approach, these are rather deep things...

**Comment by yokwejuste** [comment]
Good this issue is still opened.

On my side I did encounter the same thing, the schema loads (abnormally with some traces in the log.

```python
 view's PagesAPIViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
web  | Traceback (most recent call last):
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/request.py", line 421, in __getattr__
web  |     return getattr(_request, attr)
web  |            ^^^^^^^^^^^^^^^^^^^^^^^
web  | AttributeError: 'WSGIRequest' object has no attribute 'wagtailapi_router'
web  | 
web  | During handling of the above exception, another exception occurred:
web  | 
web  | Traceback (most recent call last):
web  |   File "/usr/local/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
web  |     return view_method()
web  |            ^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 112, in get_serializer
web  |     serializer_class = self.get_serializer_class()
web  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/wagtail/api/v2/views.py", line 364, in get_serializer_class
web  |     self.request.wagtailapi_router,
web  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/request.py", line 423, in __getattr__
web  |     return self.__getattribute__(attr)
web  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  | AttributeError: 'Request' object has no attribute 'wagtailapi_router'
web  | view's PagesAPIViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
web  | Traceback (most recent call last):
web  |   File "/usr/local/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
web  |     return view_method()
web  |            ^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 112, in get_serializer
web  |     serializer_class = self.get_serializer_class()
web  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/wagtail/api/v2/views.py", line 345, in get_serializer_class
web  |     model = type(self.get_object())
web  |                  ^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/wagtail/api/v2/views.py", line 582, in get_object
web  |     base = super().get_object()
web  |            ^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 92, in get_object
web  |     assert lookup_url_kwarg in self.kwargs, (
#....
#.....
#.....
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 112, in get_serializer
web  |     serializer_class = self.get_serializer_class()
web  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/wagtail/api/v2/views.py", line 345, in get_serializer_class
web  |     model = type(self.get_object())
web  |                  ^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/wagtail/api/v2/views.py", line 582, in get_object
web  |     base = super().get_object()
web  |            ^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 92, in get_object
web  |     assert lookup_url_kwarg in self.kwargs, (
web  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  | AssertionError: Expected view PagesAdminAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
web  | view's PagesAdminAPIViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
web  | Traceback (most recent call last):
web  |   File "/usr/local/lib/python3.11/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
web  |     return view_method()
web  |            ^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 112, in get_serializer
web  |     serializer_class = self.get_serializer_class()
web  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/wagtail/api/v2/views.py", line 345, in get_serializer_class
web  |     model = type(self.get_object())
web  |                  ^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/wagtail/api/v2/views.py", line 582, in get_object
web  |     base = super().get_object()
web  |            ^^^^^^^^^^^^^^^^^^^^
web  |   File "/usr/local/lib/python3.11/site-packages/rest_framework/generics.py", line 92, in get_object
web  |     assert lookup_url_kwarg in self.kwargs, (
web  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web  | AssertionError: Expected view PagesAdminAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
```

### More Details:
- The issue seems to be related to `drf_yasg` (redoc and swagger UIs)
- I followed [this tutorial](https://docs.wagtail.org/en/stable/advanced_topics/add_to_django_project.html) to be able to add wagtail to my project.
- NB: Downgrading the wagtail version does not give any clue on the issue.

**Comment by lucasmoeskops** [comment]
I wanted support for some filter fields in DRF-spectacular, but it was quite a hassle. For what it's worth, here are some findings so maybe someone can use them :-)

Problems I encountered:

* The request doesn't contain wagtailapi_router when spectacular inspects it. The wagtailapi_router is necessary for the serializer to correctly map related objects. 
* Spectacular tries to find out if a view is a listing view, but has some troubles. It expects "list" to be the default action for list views, but Wagtail uses listing_view instead. Therefor the Wagtail api view thinks it should serve a detail view and calls get_object. This fails because no "pk" kwarg is present.
* To detect if a view is a list view it tests basically if it extends ListSerializer or if action == 'list'. In wagtail it seems that the listing_view serializer does not fulfill any of these.

To make detection of the filter fields (defined in the filter_backends attribute) work I wrote this override of get_serializer_class in the end:

```python
    def get_serializer_class(self):
        from myproject.api.core import api_router
        
        if getattr(self.request, "wagtailapi_router", None) is None:
            # Assume this is drf-spectacular inspecting

            # "Hack" to make sure spectacular thinks this is the list view
            if self.action == "list" or self.action == "listing_view":
                
                # To make Wagtail behave as a listing view
                self.action = "listing_view"
                
                # To correctly handle relations for the serializer
                setattr(self.request, "wagtailapi_router", api_router)

                serializer = super().get_serializer_class()

                # To make successive calls to this view act the same
                setattr(self.request, "wagtailapi_router", None)
                
                # To make spectacular detect this as list view
                self.action = "list"

            return serializer

        return super().get_serializer_class()
```

**Comment by rick1290** [comment]
@thibaudcolas Is DRF Spectacluar on the roadmap? Have an existing project and would like to use it with wagtail and autogen the openapi specs.

**Comment by thibaudcolas** [comment]
@rick1290 here’s our [public roadmap](https://wagtail.org/roadmap/). DRF Spectacular support isn’t on there currently, though if someone wants to work on this I’ll happily review any PRs coming our way (based on the findings of @lucasmoeskops).

In the meantime people who need OpenAPI schemas can get that to work by doing their own API views just like with any vanilla Django data, with Django Ninja as covered in the Wagtail docs, or with a DRF implementation that doesn’t rely on Wagtail’s built-in one.

**Comment by andreasnuesslein** [comment]
So,

I was fed up with DRF and DRF-Spectacular.

Please kindly look at https://github.com/sinnwerkstatt/wagtail-ninja and https://pypi.org/project/wagtail-ninja/ for a first alpha.


Basically it should be as simple as
```
from wagtail_ninja.api import api as ninja_api


urlpatterns += [
    path("api/wagtail/v3/", ninja_api.urls),
]
```

Mostly it should follow the logic of the existing wagtail api pages endpoint at auto-discovering a bunch of fields.

not included right now is the support for `APIField()` but that might be something that needs to be changed since DRF-Serializer != Pydantic Model.

would be happy for feedback

**Comment by thibaudcolas** [comment]
For anyone interested in this, we will be tackling this as part of [RFC 115: Write API](https://github.com/wagtail/rfcs/pull/115). This goes well beyond generating OpenAPI schemas but the schemas are a must. Current status is trying to confirm whether "v3" of our API will be built on DRF or Ninja. And I’m sure there are a ton of design choices to do related to schema generation after that. Feedback very welcome!

**Comment by thibaudcolas** [comment]
This is now implemented in the v3 API, available in Wagtail 8.0 🚀 feedback thread: [v3 API feedback #14531](https://docs.wagtail.org/en/stable/advanced_topics/api/v3/migration.html#comparison-of-v2-and-v3-apis).

And see [Comparison of v2 and v3 APIs](https://docs.wagtail.org/en/stable/advanced_topics/api/v3/migration.html#comparison-of-v2-and-v3-apis) for more details on how the two differ.
