### ISSUE TITLE
django tests are not passing for elasticsearch

### ISSUE THREAD

**Issue by AurangZ** [wagtail/wagtail#6338]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
4 of the tests for elasticsearch i.e. `python runtests.py --elasticsearch7` are failing. 
Tests are in two different tests:
1. test_issue_613_on_add (wagtail.documents.tests.test_search.TestIssue613)
2. test_issue_613_on_edit (wagtail.documents.tests.test_search.TestIssue613)

They all fail with the same stack:
```
Traceback (most recent call last):
  File "/Projects/github/wagtail/wagtail/documents/tests/test_search.py", line 79, in test_issue_613_on_add
    self.search_backend.add_type(models.Document)
  File "/Projects/github/wagtail/wagtail/search/backends/base.py", line 317, in add_type
    self.get_index_for_model(model).add_model(model)
  File "/Projects/github/wagtail/wagtail/search/backends/elasticsearch7.py", line 25, in add_model
    self.es.indices.put_mapping(index=self.name, body=mapping.get_mapping())
  File "/Projects/github/wagtail/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/Projects/github/wagtail/venv/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 380, in put_mapping
    return self.transport.perform_request(
  File "/Projects/github/wagtail/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 345, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Projects/github/wagtail/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 256, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Projects/github/wagtail/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 287, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'analyzer [edgengram_analyzer] not found for field [title_edgengrams]')
```
 
### Steps to Reproduce

1. Cloned the wagtail repo
2. Followed the instructions to install
3. Installed the elasticsearch==7.8.1
4. Ran the `python runtests.py --elasticsearch7`

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I have also installed the bakerydemo project, but reran the pip install as instructed in instructions.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

* Python version: Run `python --version`.
Python 3.8.4
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
3.1
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
2.11a0
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.
N/A

**Comment by gasman** [comment]
These tests are passing on our CI instance (see the bottom line at https://travis-ci.org/github/wagtail/wagtail/builds/718697568 ), so it looks like this is something environment-specific. I'd suggest retrying through [vagrant-wagtail-develop](https://github.com/wagtail/vagrant-wagtail-develop), and if that succeeds, look at how your local environment differs from that.
