### ISSUE TITLE
Unable to generate swagger

### ISSUE THREAD

**Issue by ivannnnnnnnnn** [wagtail/wagtail#6475]
I want use Wagtail in my existing project, but i have trouble with generate OpenApiSchema via drf-yasg2. 
I have next traceback: 
```
AssertionError: Expected view PagesAdminAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
view's PagesAdminAPIViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "D:\dev\test_app\venv\lib\site-packages\drf_yasg2\inspectors\base.py", line 49, in call_view_method
    return view_method()
  File "D:\dev\test_app\venv\lib\site-packages\rest_framework\generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "D:\dev\test_app\venv\lib\site-packages\wagtail\api\v2\views.py", line 297, in get_serializer_class
    model = type(self.get_object())
  File "D:\dev\test_app\venv\lib\site-packages\wagtail\api\v2\views.py", line 448, in get_object
    base = super().get_object()
  File "D:\dev\test_app\venv\lib\site-packages\rest_framework\generics.py", line 92, in get_object
    (self.__class__.__name__, lookup_url_kwarg)
AssertionError: Expected view PagesAdminAPIViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
spec validation failed: {'ssv': 'Duplicate operationId: api_v2_listing_view'}
Internal Server Error: /api/swagger/
Traceback (most recent call last):
  File "D:\dev\test_app\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\dev\test_app\venv\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "D:\dev\test_app\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "D:\dev\test_app\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "D:\dev\test_app\venv\lib\site-packages\drf_yasg2\renderers.py", line 39, in render
    return codec.encode(data)
  File "D:\dev\test_app\venv\lib\site-packages\drf_yasg2\codecs.py", line 84, in encode
    raise exc
drf_yasg2.errors.SwaggerValidationError: spec validation failed: {'ssv': 'Duplicate operationId: api_v2_listing_view'}

```

May be some one have same issue or have expirience with using drf-yasg2 with WagtailApi

**Comment by zerolab** [comment]
Adding for reference the previous drf-yasg related issues/PRs: #6209, #4922, #4811

**Comment by jumasheff** [comment]
How do I upvote this? I have encountered this issue

**Comment by zerolab** [comment]
To everyone "bumping" this. The issue would be closed if fixed. What you can do is:

1. add the details of the errors you encounter, and how you've configured the API.
2. post the exact versions of the related libraries. e.g. https://github.com/wagtail/wagtail/pull/4922#issuecomment-626399255 confirmed it was all working
3. perhaps have a go at providing a fix.

Thank you
