### ISSUE TITLE
Changing language in admin breaks the page explorer menu

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6511]
### Steps to Reproduce

On a fresh Wagtail install, log in to the admin and go to Account settings -> Language preferences and set language to French. Opening the page explorer then gives a server error, with this error in the console:

```
Internal Server Error: /admin/api/main/pages/
Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/admin/auth.py", line 170, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/api/v2/router.py", line 63, in wrapped
    return func(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/api/v2/views.py", line 116, in handle_exception
    return super().handle_exception(exc)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/admin/api/views.py", line 98, in listing_view
    response = super().listing_view(request)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/api/v2/views.py", line 74, in listing_view
    return self.get_paginated_response(serializer.data)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/api/v2/serializers.py", line 287, in to_representation
    meta[field.field_name] = field.to_representation(attribute)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/api/v2/serializers.py", line 62, in to_representation
    return page.full_url
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/core/models.py", line 1609, in get_full_url
    url_parts = self.get_url_parts(request=request)
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/core/models.py", line 1587, in get_url_parts
    if get_supported_content_language_variant(translation.get_language()) == language_code:
  File "/Users/matthew/.virtualenvs/langwithoutwagtail/lib/python3.9/site-packages/wagtail/core/utils.py", line 271, in get_supported_content_language_variant
    raise LookupError(lang_code)
LookupError: fr
```

Related: #6510

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.9
* Django version: 3.1.3
* Wagtail version: 2.11
* Browser version: Chrome 86

**Comment by gasman** [comment]
Fixed in #6521
