### ISSUE TITLE
Upgrading to 2.11 breaks websites relying on caching

### ISSUE THREAD

**Issue by saevarom** [wagtail/wagtail#6513]
### Issue Summary

When upgrading to Wagtail 2.11 on websites using caching, specifically Redis in the case we tested, breaks some, or worst case, all rendering of the website.

### Steps to Reproduce

1. Run a previous version of wagtail, e.g. 2.10.2
2. Configure Redis caching
3. Make sure the :1:_wagtail_site_root_paths key has been generated in redis
4. Upgrade to 2.11
5. Visit the admin. You should see the error 

```
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/wagtail/admin/auth.py", line 191, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/wagtail/admin/views/home.py", line 187, in home
    site_details = get_site_for_user(request.user)
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/wagtail/admin/navigation.py", line 36, in get_site_for_user
    root_site = root_page.get_site()
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/wagtail/core/models.py", line 1678, in get_site
    url_parts = self.get_url_parts()
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/wagtail/core/models.py", line 1565, in get_url_parts
    possible_sites = [
  File "/Users/som/Virtualenvs/wagtailredistest/lib/python3.8/site-packages/wagtail/core/models.py", line 1567, in <listcomp>
    for pk, path, url, language_code in self._get_site_root_paths(request)
ValueError: not enough values to unpack (expected 4, got 3)
```

In the [release notes](https://docs.wagtail.io/en/v2.11/releases/2.11.html#site-get-site-root-paths-now-returns-language-code), we have what I suspect is the reason for this error. 
The addition of this fourth argument, the language, to _get_site_root_paths causes [this line](https://github.com/wagtail/wagtail/blob/12e8ee97bbe2957aa27a9c783680f38307e72056/wagtail/core/models.py#L1567) to break. 

I would expect Wagtail internals to handle this kind of upgrade internally, the object stored in the cache is created by Wagtail internally, and accessed by Wagtail internally. 

A simple fix would be to count the parameters returned from cache, and simply invalidate it if they do not match the expected value.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes)

### Technical details

* Python version: 3.8.5
* Django version: 3.1.3
* Wagtail version: 2.11

**Comment by gasman** [comment]
Fixed in #6515
