### ISSUE TITLE
CircularDependencyError with Custom User Model app

### ISSUE THREAD

**Issue by ZackPlauche** [wagtail/wagtail#6516]
### Issue Summary

I'm new to Wagtail, and wanted to START a project (I say START meaning before makemigrations or migrate):

1. Without the "home" app
2. With an app called "base"
3. The base app contains a Custom User Model
4. The base app also contains a Home(Page) model
5. The base app User model is the project's user model (obvious, but thought I'd clarify)

But after running migrate (after makemigrations) I get this big ugly error:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\core\management\__init__.py", line 395, in execute   
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\core\management\base.py", line 330, in run_from_argv 
    self.execute(*args, **cmd_options)
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\core\management\base.py", line 371, in execute       
    output = self.handle(*args, **options)
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\core\management\base.py", line 85, in wrapped        
    res = handle_func(*args, **kwargs)
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\core\management\commands\migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__     
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\db\migrations\loader.py", line 53, in __init__       
    self.build_graph()
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\db\migrations\loader.py", line 282, in build_graph   
    self.graph.ensure_not_cyclic()
  File "C:\Users\zackp\.virtualenvs\wagtail_training_3-TmuBvXmb\lib\site-packages\django\db\migrations\graph.py", line 274, in ensure_not_cyclic
    raise CircularDependencyError(", ".join("%s.%s" % n for n in cycle))
django.db.migrations.exceptions.CircularDependencyError: wagtailcore.0017_change_edit_page_permission_description, wagtailcore.0018_pagerevision_submitted_for_moderation_index, wagtailcore.0019_verbose_names_cleanup, wagtailcore.0020_add_index_on_page_first_published_at, wagtailcore.0021_capitalizeverbose, wagtailcore.0022_add_site_name, wagtailcore.0023_alter_page_revision_on_delete_behaviour, wagtailcore.0024_collection, wagtailcore.0025_collection_initial_data, wagtailcore.0026_group_collection_permission, wagtailcore.0027_fix_collection_path_collation, wagtailcore.0028_merge, wagtailcore.0029_unicode_slugfield_dj19, wagtailcore.0030_index_on_pagerevision_created_at, wagtailcore.0031_add_page_view_restriction_types, wagtailcore.0032_add_bulk_delete_page_permission, wagtailcore.0033_remove_golive_expiry_help_text, wagtailcore.0034_page_live_revision, wagtailcore.0035_page_last_published_at, wagtailcore.0036_populate_page_last_published_at, wagtailcore.0037_set_page_owner_editable, wagtailcore.0038_make_first_published_at_editable, wagtailcore.0039_collectionviewrestriction, wagtailcore.0040_page_draft_title, wagtailcore.0041_group_collection_permissions_verbose_name_plural, wagtailcore.0042_index_on_pagerevision_approved_go_live_at, wagtailcore.0043_lock_fields, wagtailcore.0044_add_unlock_grouppagepermission, wagtailcore.0045_assign_unlock_grouppagepermission, wagtailcore.0046_site_name_remove_null, wagtailcore.0047_add_workflow_models, wagtailcore.0048_add_default_workflows, wagtailcore.0049_taskstate_finished_by, wagtailcore.0050_workflow_rejected_to_needs_changes, wagtailcore.0051_taskstate_comment, 
wagtailcore.0052_pagelogentry, wagtailcore.0053_locale_model, wagtailcore.0054_initial_locale, wagtailcore.0055_page_locale_fields, wagtailcore.0056_page_locale_fields_populate, wagtailcore.0057_page_locale_fields_notnull, wagtailcore.0058_page_alias_of, wagtailcore.0059_apply_collection_ordering, base.0001_initial, wagtailcore.0001_squashed_0016_change_page_url_path_to_text_field
```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Delete the home app
3. Create a new app named "base" 
4. Edit the base app models page like so (add a custom User model, then add a Wagtail page): 

```
#base/models.py

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models

from wagtail.core.models import Page


# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)

    USERNAME_FIELD ='email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}' 

# Home Page
class Home(Page):
    pass
```
5. In the myproject/settings/base.py file, update INSTALLED_APPS like so:
```
# myproject/settings/base.py
INSTALLED_APPS = [
    'base',
    'search',

    'modelcluster',
    'taggit',
    'django_extensions',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
```
6. Also in the myproject/settings/base.py file, add the custom Auth user model:
```
# myproject/settings/base.py

AUTH_USER_MODEL = 'base.User'
```
7. Run `python manage.py makemigrations`
8. Run `python manage.py migrate`

Then the error occurs.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.8.6
* Django version: 3.1.3
* Wagtail version: 2.11

**Comment by gasman** [comment]
Hi @ZackPlauche - thanks for the detailed report!

This is an expected consequence of how Django migrations behave. You can't create a custom user model in the same migration as a page model, because Wagtail's base Page model contains references to the user model, and so the migrations need to create the user model first, followed by Wagtail's base Page model, then your home page model. If you proceed as follows:

* Delete the failing `base.0001_initial` migration
* Comment out the definition of `class Home(Page):` in your models.py
* Run `python manage.py makemigrations`
* Uncomment the definition of `class Home(Page):`
* Run `python manage.py makemigrations` again

then the dependencies will be set up correctly, and migrations should then complete successfully.

**Comment by ZackPlauche** [comment]
Hi @gasman, thanks for the reply!

That makes a lot of sense. Your explanation was clear as crystal.

Out of curiosity, and coming to this as a beginner, is this somewhere in the documentation? If not, I think it would be a valuable addition to the docs as a warning above in the "Custom User Models" section in the Advanced Topics / Customising Wagtail documentation:  https://docs.wagtail.io/en/v2.11/advanced_topics/customisation/custom_user_models.html

Currently it the layout is a bit confusing, as the heading above where the Custom User Model is created it says "Custom user forms example", instead of first just talking about the Custom User part.

I know that's where I looked (and I literally just went through the first 2 parts of the documentation 2 days ago haha) and it was confusing to me.

Here's what I think would help: 
![image](https://user-images.githubusercontent.com/43456955/98244272-d6307000-1f77-11eb-84c9-f3e4635ab14a.png)
