### ISSUE TITLE
Circular Import Error in wagtail.cotrib.forms.models for a FormPage in 2.11

### ISSUE THREAD

**Issue by davemerwin** [wagtail/wagtail#6518]
### Issue Summary

When upgrading from a previous version of Wagtail, the form pages are not working anymore. I'm getting a circular import error for code that previously worked. The ONLY change was upgrading to 2.11

### Steps to Reproduce

1. Update virtual env to use Wagtail 2.11
2. Startup runserver
3. Now getting the following error: 

`ImportError: cannot import name 'FORM_FIELD_CHOICES' from partially initialized module 'wagtail.contrib.forms.models' (most likely due to a circular import) (/home/user/sandbox/clients/client/project/web/env/envname/lib/python3.8/site-packages/wagtail/contrib/forms/models.py)`

My expectation is that the code would run as before.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: 3.8.
* Django version: 3.1.3.
* Wagtail version: 2.11.
* Browser version: Version 86.0.4240.111

**Comment by gasman** [comment]
Hi @davemerwin - thanks for the report. Please can you include the full traceback of the error?

**Comment by davemerwin** [comment]
Here's the fill stack trace

(client2) user@user:~/sandbox/clients/client/client/web$ python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/wagtail/contrib/forms/models.py", line 16, in <module>
    from wagtail.admin.mail import send_mail
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/wagtail/admin/mail.py", line 10, in <module>
    from wagtail.admin.auth import users_with_page_permission
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/wagtail/admin/auth.py", line 8, in <module>
    from django.contrib.auth.views import redirect_to_login as auth_redirect_to_login
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/contrib/auth/views.py", line 10, in <module>
    from django.contrib.auth.forms import (
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 21, in <module>
    UserModel = get_user_model()
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 157, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/apps/registry.py", line 209, in get_model
    app_config.import_models()
  File "/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/sandbox/clients/client/client/web/profiles/models.py", line 20, in <module>
    from products.models import AccountToProduct
  File "/home/user/sandbox/clients/client/client/web/products/models.py", line 27, in <module>
    from wagtail.contrib.forms.models import (
ImportError: cannot import name 'FORM_FIELD_CHOICES' from partially initialized module 'wagtail.contrib.forms.models' (most likely due to a circular import) (/home/user/sandbox/clients/client/client/web/env/client2/lib/python3.8/site-packages/wagtail/contrib/forms/models.py)

**Comment by gasman** [comment]
Thanks for the extra detail. I've now been able to replicate this independently by the following steps:

1. Create a new project with `wagtail start myproject`
2. `./manage.py startapp customuser` and add 'customuser' to the bottom of `INSTALLED_APPS`
3. Edit customuser/models.py as follows:

       from django.contrib.auth.models import AbstractUser

       class CustomUser(AbstractUser):
           pass

4. Add `AUTH_USER_MODEL = 'customuser.CustomUser'` to settings
5. Run `./manage.py makemigrations` and `./manage.py migrate`
6. Add `from wagtail.contrib.forms.models import FORM_FIELD_CHOICES` to the top of customuser/models.py
7. Run `./manage.py check`

Looks like this is happening because importing wagtail.contrib.forms.models is setting off a chain of imports starting with wagtail.admin.mail, then Wagtail's authentication helpers, then django.contrib.auth which tries to import the custom user model, leading to a circular import if the original import of wagtail.contrib.forms.models was in the same place as that custom user model. Investigating further now...

**Comment by gasman** [comment]
@davemerwin What version of Wagtail were you running before upgrading to 2.11?

**Comment by davemerwin** [comment]
@gasman I was using 2.5.1

**Comment by gasman** [comment]
Cheers - looks like this bug was introduced in 2.7, so that checks out. Have now submitted a fix in #6522.
