### ISSUE TITLE
Get 500 error when deleting default language from locale admin

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail#6533]
### Issue Summary

I get a 500 error when deleting the default language in locale admin.

### Steps to Reproduce

Deleting the default language from the locale admin gives the following error:

```
Internal Server Error: /locales/1/delete/
Traceback (most recent call last):
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\views\generic.py", line 45, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\generic\edit.py", line 218, in post
    return self.delete(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail_localize\locales\views.py", line 62, in delete
    return super().delete(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\admin\views\generic.py", line 242, in delete
    response = super().delete(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\generic\edit.py", line 213, in delete
    self.object.delete()
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\base.py", line 946, in delete
    collector.collect([self], keep_parents=keep_parents)
  File "C:\Work\virtual_env\lib\site-packages\django\db\models\deletion.py", line 308, in collect
    set(chain.from_iterable(protected_objects.values())),
django.db.models.deletion.ProtectedError: ("Cannot delete some instances of model 'Locale' because they are referenced through protected foreign keys: 'Page.locale'.", {<Page: Root>})
```

I expect wagtail to give a warning within the admin interface that this action cannot be executed.

### Technical details

* Python version: 3.7.6
* Django version: 3.1.2
* Wagtail version: 2.11.1

**Comment by gasman** [comment]
Hi @Warqus - thanks for the report.

I'm unable to replicate this by following these steps:

* Start a new project with `wagtail start myproject`
* Edit myproject/settings/base.py - add `'wagtail.locales',` to INSTALLED_APPS and the following to the end of the file

      WAGTAIL_I18N_ENABLED = False
      WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
          ('en', "English"),
          ('fr', "French"),
          ('es', "Spanish"),
      ]

* Run `./manage.py migrate`, `./manage.py createsuperuser` and `./manage.py runserver`
* Log in to http://localhost:8000/admin/locales/, see language English with 1 page listed
* Attempt to delete the English locale and receive the message: "This locale cannot be deleted because there are pages and/or other objects using it."

![Screenshot 2020-11-13 at 14 38 17](https://user-images.githubusercontent.com/85097/99083787-f090cc00-25bd-11eb-8f32-ddbcbeef183d.png)

If you can provide full steps to replicate this, I'll be happy to investigate further.

**Comment by Warqus** [comment]
Thanks for reacting. If you delete that one page, the error will appear when trying to delete the locale:

![image](https://user-images.githubusercontent.com/14151318/99156038-04bbf280-26be-11eb-942b-594e44d99f67.png)

![image](https://user-images.githubusercontent.com/14151318/99156050-1bfae000-26be-11eb-82f9-5d017250e0bc.png)

![image](https://user-images.githubusercontent.com/14151318/99156053-24531b00-26be-11eb-98a0-6ac25f60be85.png)

**Comment by gasman** [comment]
Thanks! That makes sense - the page tree in Wagtail has a root node that's usually hidden within the UI (for example, it's ignored in the page counts shown here) and can't be deleted. The locale on this node would be set to the default locale (LANGUAGE_CODE) that existed when the initial migrations were run, causing the error here.

@kaedroho What do you think is the best way of handling this case? I'm thinking:

* don't allow deleting a locale if it's the only one
* don't allow deleting a locale that is in use anywhere other than the root node (i.e. keep the current check as is)
* when deleting the locale that is in use on the root node, silently reassign it to a different locale: preferably the one corresponding to the current LANGUAGE_CODE (if that exists and isn't the one being deleted), or else an arbitrarily chosen one (`Locale.objects.exclude(id=locale_being_deleted).first()`)

**Comment by kaedroho** [comment]
Hey @gasman,

Yep, that sounds good to me!
