### ISSUE TITLE
search & locale parameters not working together with api

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail#6626]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Whenever I use both the 'search' and 'locale' parameters while using the API I get an error.

e.g.: http://127.0.0.1:8001/cms/pages/?search=home&locale=nl

### Steps to Reproduce

```
Internal Server Error: /cms/pages/
Traceback (most recent call last):
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Work\virtual_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\api\v2\router.py", line 63, in wrapped
    return func(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\api\v2\views.py", line 116, in handle_exception
    return super().handle_exception(exc)
  File "C:\Work\virtual_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Work\virtual_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Work\virtual_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\api\v2\views.py", line 71, in listing_view
    queryset = self.filter_queryset(queryset)
  File "C:\Work\virtual_env\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "C:\Work\virtual_env\lib\site-packages\wagtail\api\v2\filters.py", line 235, in filter_queryset
    queryset = queryset.filter(locale=locale)
AttributeError: 'PostgresSearchResults' object has no attribute 'filter'
```

### Technical details

* Wagtail version: 2.11.2

**Comment by gasman** [comment]
Thanks for the report @Warqus! Fix now opened here: #6627
