### ISSUE TITLE
Error when navigating to snippets after removing default language from locales

### ISSUE THREAD

**Issue by Warqus** [wagtail/wagtail#6663]
### Issue Summary

After removing the default language from locales (within wagtail admin interface), I want to navigate to snippets but I get the following error:

```
Internal Server Error: /admin/snippets/app_cms/snippetheader/
Traceback (most recent call last):
  File "C:\virtual_env\lib\site-packages\wagtail\core\models.py", line 372, in get_active
    return cls.objects.get_for_language(translation.get_language())
  File "C:\virtual_env\lib\site-packages\wagtail\core\models.py", line 339, in get_for_language
    return self.get(language_code=get_supported_content_language_variant(language_code))
  File "C:\virtual_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\virtual_env\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
wagtail.core.models.Locale.DoesNotExist: Locale matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\virtual_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\virtual_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\virtual_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\virtual_env\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\virtual_env\lib\site-packages\wagtail\admin\auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\virtual_env\lib\site-packages\wagtail\snippets\views\snippets.py", line 99, in list
    locale = Locale.get_active()
  File "C:\virtual_env\lib\site-packages\wagtail\core\models.py", line 374, in get_active
    return cls.get_default()
  File "C:\virtual_env\lib\site-packages\wagtail\core\models.py", line 364, in get_default
    return cls.objects.get_for_language(settings.LANGUAGE_CODE)
  File "C:\virtual_env\lib\site-packages\wagtail\core\models.py", line 339, in get_for_language
    return self.get(language_code=get_supported_content_language_variant(language_code))
  File "C:\virtual_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\virtual_env\lib\site-packages\django\db\models\query.py", line 431, in get
    self.model._meta.object_name
wagtail.core.models.Locale.DoesNotExist: Locale matching query does not exist.
[30/Dec/2020 18:22:15] "GET /admin/snippets/app_cms/snippetheader/ HTTP/1.1" 500 133555
```

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add second language to locales within wagtail admin
3. Remove default language from locales within wagtail admin
4. Navigate to snippets, then clicking on a snippet (see image below; clicking on "Headers" or "Blog Authors" will result in the error).

![image](https://user-images.githubusercontent.com/14151318/103370210-80d29400-4acc-11eb-812d-21ccc285a505.png)

### Technical details

* Python version: 3.7.4
* Django version: 3.1.4
* Wagtail version: 2.11.3
* wagtail-localize: 0.9.4

**Comment by gasman** [comment]
Hi @Warqus - thanks for the report. Just to confirm - have you been able to replicate this as described on a fresh Wagtail project?

**Comment by Warqus** [comment]
Hi @gasman - Thanks for the fast response. I did not, I will remove that part!

**Comment by gasman** [comment]
Thanks, but if you're able to test this on a fresh install too (and adjust the steps if required) then that will make this report far more useful!

**Comment by Warqus** [comment]
@gasman I have tested it with a new project. Error still occurs.

It happens when trying to add a new snippet. My Header snippet:

```
@register_snippet
class SnippetHeader(TranslatableMixin):
    name = models.CharField(_('name'), max_length=100, null=False, blank=False, default="")

    class Meta(TranslatableMixin.Meta):
        verbose_name = _('header')
        verbose_name_plural = _('headers')

        unique_together = [('translation_key', 'locale')]

    def __str__(self):
        return self.name
```

Using 'wagtail.locales' in INSTALLED_APPS instead of the wagtail_localize apps doesn't help. Error still occurs.
