### ISSUE TITLE
JSONDecodeError RichTextBlock

### ISSUE THREAD

**Issue by ogola89** [wagtail/wagtail#6728]
### Issue Summary

I am getting a JSONDecodeError when using a RichTextBlock in a StreamField that works when either using a TextBlock or not using any rich text features in the RichTextBlock.

Custom Block:

```
from wagtail.core import blocks

class EdExpBlock(blocks.StructBlock):
    """For use in the education portion of the resume page"""
    title = blocks.CharBlock(max_length=100)
    start = blocks.IntegerBlock(help_text="Start Year")
    end = blocks.IntegerBlock(help_text="Start Year")
    institution = blocks.CharBlock(max_length=100)
    description = blocks.RichTextBlock()  #this is the line that is causing issues

```

Model:
```
class ResumePage(Page):
    template = "Leven/resume.html"
    max_count = 1

    education = StreamField([
        ("education", **EdExpBlock()**),
    ],  null=True, blank=True)

    experience = StreamField([
        ("experience", EdExpBlock()),
    ],  null=True, blank=True)

    certificates = StreamField([
        ("certificates", CertificateBlock()),
    ],  null=True, blank=True)

    lab_skills = StreamField([
        ("lab_skills", SkillBlock()),
    ],  null=True, blank=True)
    coding_skills = StreamField([
        ("coding_skills", SkillBlock()),
    ],  null=True, blank=True)

    content_panels = Page.content_panels + [
        StreamFieldPanel("education"),
        StreamFieldPanel("experience"),
        StreamFieldPanel("certificates"),
        StreamFieldPanel("lab_skills"),
        StreamFieldPanel("coding_skills"),
    ]
```
Template:

```
<div id="timeline_1" class="timeline clearfix">
                            {% for block in page.education %}
                            <div class="timeline-item clearfix">
                                <h5 class="item-period ">{{block.value.start}} - {{block.value.end}}</h5>
                                <span class="item-company">{{block.value.instituion}}</span>
                                <h4 class="item-title">{{block.value.title}}</h4>
                                <p>{{block.value.description|safe}}</p>
                            </div>
                            {% endfor %}
                        </div>
```

### Steps to Reproduce

1. Add rich text to block
2. Preview

### Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

When I don't include any rich text editing, the template loads fine even though it's a RichTextBlock. I think it is when it has to parse the JSON that comes through the RichTextBlock. I tried adding a safe filter but that didn't change either.

I have seen a similar issue in issue #4232 but it seemed that this was fixed prior to 2.0

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:  no

Full error:
```
 Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/pages/17/edit/preview/

Django Version: 3.1.5
Python Version: 3.8.5
Installed Applications:
['home',
 'search',
 'flex',
 'streams',
 'site_settings',
 'subscribers',
 'blogsite',
 'projects',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.contrib.settings',
 'wagtail.contrib.routable_page',
 'wagtail.contrib.sitemaps',
 'wagtail.contrib.modeladmin',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'djrichtextfield',
 'wagtailfontawesome',
 'wagtailcodeblock',
 'wagtailuiplus',
 'wagalytics',
 'wagtail_blocks',
 'wagtailstreamforms',
 'wagtail_color_panel',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'debug_toolbar']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)

During handling of the above exception (0), another exception occurred:
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\admin\auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\admin\views\pages\preview.py", line 82, in get
    if not form.is_valid():
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\modelcluster\forms.py", line 316, in is_valid
    form_is_valid = super(ClusterForm, self).is_valid()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\forms\forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\forms\forms.py", line 172, in errors
    self.full_clean()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\forms\forms.py", line 374, in full_clean
    self._clean_fields()
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\forms\forms.py", line 386, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\core\blocks\base.py", line 552, in value_from_datadict
    return self.block_def.value_from_datadict(data, files, name)
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\core\blocks\stream_block.py", line 177, in value_from_datadict
    child_block.value_from_datadict(data, files, '%s-%d-value' % (prefix, i)),
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\core\blocks\struct_block.py", line 114, in value_from_datadict
    return self._to_struct_value([
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\core\blocks\struct_block.py", line 115, in <listcomp>
    (name, block.value_from_datadict(data, files, '%s-%s' % (prefix, name)))
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\core\blocks\field_block.py", line 69, in value_from_datadict
    return self.value_from_form(self.field.widget.value_from_datadict(data, files, prefix))
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\admin\rich_text\editors\draftail\__init__.py", line 68, in value_from_datadict
    return self.converter.to_database_format(original_value)
  File "C:\Users\Tomo_\AppData\Roaming\Python\Python38\site-packages\wagtail\admin\rich_text\converters\contentstate.py", line 90, in to_database_format
    return self.exporter.render(json.loads(contentstate_json))
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

Exception Type: JSONDecodeError at /admin/pages/17/edit/preview/
Exception Value: Expecting value: line 1 column 1 (char 0)

```

### Technical details

* Python version: 3.8.5
* Django version: 3.1.5
* Wagtail version: 2.11.3
* Browser version: https://www.whatsmybrowser.org/b/30393

**Comment by gasman** [comment]
Hi @ogola89 - thanks for the report. As you haven't reproduced this on a fresh Wagtail project, we'll need some extra details to confirm that this indeed a Wagtail bug rather than a bug in your project...

* Does this happen on any page you've created, or just one specific page? Is it triggered by one particular piece of text in the rich text block, or can you repeat the error with any text (e.g. just entering "hello world" in the text area)?
* Does the error only happen on clicking 'Preview', or does the 'Save draft' button trigger it too? If it happens on 'Save draft', please share the POST data (shown under "Request information" on the error page).
* If you open [Chrome developer tools](https://developers.google.com/web/tools/chrome-devtools/open) while editing the page, do any error messages appear there?
* Does you see the toolbar of formatting options on the rich text field (see screenshot below)?

![Screenshot 2021-01-27 at 12 06 59](https://user-images.githubusercontent.com/85097/105988889-3bd45a00-6098-11eb-9f90-08477b054b84.png)

**Comment by ogola89** [comment]
Hi gasman,

It seems to have resolved itself now, I think when I saved the draft it then worked, but I added content to a few other fields. So I'm not entirely sure what resolved it (sorry!). I wasn't getting the bug with just a plain 'Hello', but when I used bolding and bullet points it came up.

Thankfully now it has resolved, and the only thing I can think of that resolved it was saving the draft.
