### ISSUE TITLE
wagtail.contrib.forms causes database issues

### ISSUE THREAD

**Issue by matthiasrohmer** [wagtail/wagtail#6746]
### Issue Summary

Using `wagtail.contrib.forms` seems to interact with the database in unprecedented ways and by that blocks certain command flows.

I use django-extensions' `reset_db` command and `migrate` in a custom management command called `bootstrap`. It looks something along the lines of the following:

```python
class Command(BaseCommand):

    def handle(self, *args, **options):
            call_command('reset_db', noinput=True, interactive=False)
            self.stdout.write(
                self.style.SUCCESS('Successfully reset database.'))

        call_command('migrate')
        self.stdout.write(self.style.SUCCESS('Successfully ran migrations.'))
```

As soon as I started using the forms app this failed with either:

```
/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture '...': Could not load auth.User(pk=1): attempt to write a readonly database
```

for the local SQLite database or

```
File "/usr/local/lib/python3.7/site-packages/django_extensions/management/commands/reset_db.py", line 175, in handle        
remote:            cursor.execute(drop_query)        
remote:        psycopg2.errors.ObjectInUse: database "db_test_ftb_jansen_de" is being accessed by other users        
remote:        DETAIL:  There is 1 other session using the database.      
```

for the production PostgreSQL database and I couldn't figure out why. Though disabling the `wagtail.contrib.forms` app (and my custom ones that were relying on it) made the issue disappear.

When debugging today I found out that the culprit is here:

https://github.com/wagtail/wagtail/blob/30b90a0f6563d0aa385f9b717f67a489450c377d/wagtail/contrib/forms/models.py#L166-L174

Overriding `AbstractFormField._migrate_legacy_clean_name` like so

```python
@classmethod
    def _migrate_legacy_clean_name(cls):
        return None
```

also makes the issue disappear.

I know that is a very special case but since I spent some time debugging this I wanted to see if there is a more sophisticated fix or even one that can be made upstream?

**Comment by gasman** [comment]
Hi @matthiasrohmer,
Presumably this is happening because the system check in wagtail.contrib.forms is performing a database operation, and postgres/sqlite won't let you drop the database once the running command has made a connection to it. If so, I think the solution would be to set [`requires_system_checks = False`](https://docs.djangoproject.com/en/3.1/howto/custom-management-commands/#django.core.management.BaseCommand.requires_system_checks) on your command class.

This does raise the question of whether Wagtail is breaking a Django convention or policy by making a database connection inside a system check... I'm not aware of any rule against it, but if there is one, then I'd be open to reviewing this and looking for alternative ways of making this system check work.

**Comment by quinox** [comment]
I'm not saying this should or shouldn't be changed, just adding my 2 cents: I'm running into a similar problem, I can work around it but it feels a bit wrong.

My scenario: when running `python manage.py makemigrations` I normally switch to the Dummy database: this prevents issues under certain conditions in my setup, and `makemigrations` is completely database-independent so it shouldn't matter. Except that now Wagtail tries to use the DB which triggers a crash.

Because I use Django's standard management command I can't actually use `requires_system_checks = False`. I'll switch to SQLite for now.

```python
$ python manage.py makemigrations

Traceback (most recent call last):
  File "/x/y/project-with-wagtail/website/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/core/management/base.py", line 393, in execute
    self.check()
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/wagtail/contrib/forms/models.py", line 170, in check
    messages = cls._migrate_legacy_clean_name()
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/wagtail/contrib/forms/models.py", line 143, in _migrate_legacy_clean_name
    if objects.count() == 0:
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/query.py", line 412, in count
    return self.query.get_count(using=self.db)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/query.py", line 519, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/query.py", line 504, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 527, in as_sql
    from_, f_params = self.get_from_clause()
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 806, in get_from_clause
    clause_sql, clause_params = self.compile(from_clause)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/datastructures.py", line 168, in as_sql
    base_sql = compiler.quote_name_unless_alias(self.table_name)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 436, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "/x/y/project-with-wagtail/virtual/lib/python3.8/site-packages/django/db/backends/dummy/base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

```
