### ISSUE TITLE
Embed Uniqueness Issues on 2.12

### ISSUE THREAD

**Issue by jacobtoppm** [wagtail/wagtail#6764]
### Issue Summary

Embed uniqueness was not enforced at a db level pre-2.12, so it is possible for https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/migrations/0008_allow_long_urls.py to fail during upgrade. (Additionally, because the uniqueness is enforced on the hash, rather than the url, there seems to be an additional issue with certain url strings that are apparently unique in postgres (a `url_count` annotation is 1 for both) but equal in Python, but I haven't worked out exactly what the problem is here)

### Steps to Reproduce

1. Start a new project with `wagtail start myproject` on Wagtail 2.11, making sure the embeds app is added
2. Enter the django shell
3. Create two Embeds objects with the same url using `Embed.objects.create`
4. Attempt the 2.12 upgrade

### Technical details

* Python version: 3.6.4
* Django version: 2.2.13
* Wagtail version: 2.11.3 -> 2.12
* Browser version: N/A

**Comment by gasman** [comment]
A data migration to delete the duplicates would fix this, although it's hard to see how to roll that out without breaking anything, since it has to run before migration 0008, and adding a new migration to the sequence would cause an inconsistent migration history error for people who already applied 0008. Bundling the data migration into migration 0008 could work, but we'll have to make sure that combining a data and schema migration doesn't cause any issues on any databases (see https://stackoverflow.com/questions/60806250/mix-data-and-schema-migrations-in-one-migrations-file-django).

**Comment by gasman** [comment]
PR: #6815
I forgot that there was an existing data migration as part of this change, so it wasn't as complicated as I'd feared :-) The only proviso is that if someone tried upgrading to 2.12 and encountered the failure on migration 0008, then after upgrading to this fixed version they'll have to roll back migrations to before 0007 to get unstuck...

    ./manage.py migrate wagtailembeds 0005
    ./manage.py migrate

**Comment by gasman** [comment]
Fixed in #6815

**Comment by nickmoreton** [comment]
I saw this issue yesterday so waited for the fix. I just tried it but it's not working for me.

```
psycopg2.errors.UndefinedObject: constraint "wagtailembeds_embed_url_max_width_8a2922d8_uniq" of relation "wagtailembeds_embed" does not exist
```

I was upgrading from 2.11 to 2.12 and saw the error then tried out the above
```
./manage.py migrate wagtailembeds 0005
./manage.py migrate
```

As a bit of background we have been moving a site from 2.2.1 in major version steps and all has been fine up to 2.11. When i tried the 2.12 upgrade yesterday I saw the error and found this issue report so stopped at 2.11

From a fresh 2.2.1 database I tried upgrading to 2.11 (in one go) and that all worked OK but when the going to 2.12.1 I see the error again.

**Comment by gasman** [comment]
@nickmoreton Can you share the full output of `./manage.py migrate`, please? In particular, it would be useful to know which migration number is triggering this error.

**Comment by nickmoreton** [comment]
Sure
```
Running migrations:
  Applying wagtailembeds.0006_add_embed_hash... OK
  Applying wagtailembeds.0007_populate_hash... OK
  Applying wagtailembeds.0008_allow_long_urls...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedObject: constraint "wagtailembeds_embed_url_max_width_8a2922d8_uniq" of relation "wagtailembeds_embed" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 530, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 363, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 399, in _delete_composed_index
    self.execute(self._delete_constraint_sql(sql, model, constraint_names[0]))
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: constraint "wagtailembeds_embed_url_max_width_8a2922d8_uniq" of relation "wagtailembeds_embed" does not exist
```

**Comment by gasman** [comment]
Thanks @nickmoreton. That seems odd then... at this point it looks like it's not failing due to the presence of duplicates, but because the _old_ uniqueness constraint - the one we're trying to drop here - doesn't exist.

To clarify - when you say:

> From a fresh 2.2.1 database I tried upgrading to 2.11 (in one go) and that all worked OK but when the going to 2.12.1 I see the error again.

you were starting from a database dump where the upgrade to 2.12 had NOT previously been attempted (and rolled back), correct? I'd like to rule out the possibility that the missing database constraint is due to migration 0008 failing after the point where the constraint had been dropped. (That theory doesn't really add up though: migrations ought to happen in a transaction that prevents them from failing in a partially-complete state, and either way, that step happens _after_ the one that we know to be failure-prone.)

If you still have the pre-upgrade 2.2.1 database available, please could you check whether the uniqueness constraint is present there? Run `./manage.py dbshell`, and then `\d wagtailembeds_embed` - the output should end with:

    Indexes:
        "wagtailembeds_embed_pkey" PRIMARY KEY, btree (id)
        "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE CONSTRAINT, btree (url, max_width)

**Comment by nickmoreton** [comment]
Thanks @gasman I have setup the repo again at where we started with Wagtail 2.2.1 with the sql dump from postgres that was taken then.

Probably doesn't make any different but there was a migration needs to be run:
```
wagtail@f30e8dd7f11b:/app/app$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, base, blog, contenttypes, general, home, portfolio, sessions, taggit, wagtailadmin, wagtailcore, wagtaildocs, wagtailembeds, wagtailforms, wagtailimages, wagtailmenus, wagtailredirects, wagtailsearch, wagtailusers, work
Running migrations:
  Applying wagtailmenus.0023_remove_use_specific... OK
wagtail@f30e8dd7f11b:/app/app$ 
```

This is the result of \d wagtailembeds_embed

```
pipit=# \d wagtailembeds_embed
                                          Table "public.wagtailembeds_embed"
    Column     |            Type             | Collation | Nullable |                     Default
---------------+-----------------------------+-----------+----------+-------------------------------------------------
 id            | integer                     |           | not null | nextval('wagtailembeds_embed_id_seq'::regclass)
 url           | character varying(200)      |           | not null |
 max_width     | integer                     |           |          |
 type          | character varying(10)       |           | not null |
 html          | text                        |           | not null |
 title         | text                        |           | not null |
 author_name   | text                        |           | not null |
 provider_name | text                        |           | not null |
 thumbnail_url | character varying(200)      |           |          |
 width         | integer                     |           |          |
 height        | integer                     |           |          |
 last_updated  | timestamp without time zone |           | not null |
Indexes:
    "wagtailembeds_embed_pkey" PRIMARY KEY, btree (id)
    "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE, btree (url, max_width)

pipit=#
```
The CONSTRAINT is missing 

I'll keep the setup at this point, let me know if you need me to do anything else please.

**Comment by gasman** [comment]
I expect the UNIQUE vs UNIQUE CONSTRAINT is just a difference between postgresql versions...

Could you try installing Wagtail 2.12.1, then applying the migrations from wagtailembeds one at a time (`./manage.py migrate wagtailembeds 0004`, `./manage.py migrate wagtailembeds 0005` up to `0008`), checking the output of `\d wagtailembeds_embed` after each one to see if the UNIQUE line is still there?

**Comment by nickmoreton** [comment]
0004
```
Indexes:
    "wagtailembeds_embed_pkey" PRIMARY KEY, btree (id)
    "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE, btree (url, max_width)
```
0005
```
Indexes:
    "wagtailembeds_embed_pkey" PRIMARY KEY, btree (id)
    "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE, btree (url, max_width)
```
0006
```
Indexes:
    "wagtailembeds_embed_pkey" PRIMARY KEY, btree (id)
    "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE, btree (url, max_width)
```
0007
```
Indexes:
    "wagtailembeds_embed_pkey" PRIMARY KEY, btree (id)
    "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE, btree (url, max_width)
```
0008 Crashes
```
Running migrations:
  Applying wagtailembeds.0008_allow_long_urls...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedObject: constraint "wagtailembeds_embed_url_max_width_8a2922d8_uniq" of relation "wagtailembeds_embed" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 530, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 363, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 399, in _delete_composed_index
    self.execute(self._delete_constraint_sql(sql, model, constraint_names[0]))
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: constraint "wagtailembeds_embed_url_max_width_8a2922d8_uniq" of relation "wagtailembeds_embed" does not exist
```

**Comment by nickmoreton** [comment]
I'm beginning to think the database dump given to me is not correct in some way.
It turns out the data base in use at the moment is Postgres 9.5

Im not suggesting this is the way to fix this but lets see if I can shed some light so to speak.

If I create an empty database and run the 2.11 migrations on it I see the same output as you do @gasman 

```
Indexes:
    "wagtailembeds_embed_pkey" PRIMARY KEY, btree (id)
    "wagtailembeds_embed_url_max_width_8a2922d8_uniq" UNIQUE CONSTRAINT, btree (url, max_width)
```

I'm going to try a dumpdata from working database at 2.11 and loaddata...

It failed with 
```
wagtail@ea65b08269cd:/app/app$ ./manage.py loaddata data.json 
/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1421: RuntimeWarning: DateTimeField Embed.last_updated received a naive datetime (2018-09-02 15:37:06.843000) while time zone support is active.
  RuntimeWarning)
/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py:1421: RuntimeWarning: DateTimeField Embed.last_updated received a naive datetime (2018-09-03 10:04:56.957000) while time zone support is active.
  RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "wagtailembeds_embed_hash_c9bd8c9a_uniq"
DETAIL:  Key (hash)=() already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.7/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1332, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: Problem installing fixture '/app/app/data.json': Could not load wagtailembeds.Embed(pk=2): duplicate key value violates unique constraint "wagtailembeds_embed_hash_c9bd8c9a_uniq"
DETAIL:  Key (hash)=() already exists.
```
There are just a couple of embed records so I'll remove them from the dump 
```
{
  "model": "wagtailembeds.embed",
  "pk": 1,
  "fields": {
    "url": "https://youtu.be/HtuaL9OOIkc",
    "max_width": null,
    "type": "video",
    "html": "<iframe width=\"480\" height=\"270\" src=\"https://www.youtube.com/embed/HtuaL9OOIkc?feature=oembed\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>",
    "title": "PrimarySite promotional video",
    "author_name": "ThePrimarySite",
    "provider_name": "YouTube",
    "thumbnail_url": "https://i.ytimg.com/vi/HtuaL9OOIkc/hqdefault.jpg",
    "width": 480,
    "height": 270,
    "last_updated": "2018-09-02T15:37:06.843"
  }
},
{
  "model": "wagtailembeds.embed",
  "pk": 2,
  "fields": {
    "url": "https://vimeo.com/287978345",
    "max_width": null,
    "type": "video",
    "html": "<iframe src=\"https://player.vimeo.com/video/287978345?app_id=122963\" width=\"640\" height=\"360\" frameborder=\"0\" title=\"PrimarySite Demo Video\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>",
    "title": "PrimarySite Demo Video",
    "author_name": "Nick Rawson",
    "provider_name": "Vimeo",
    "thumbnail_url": "https://i.vimeocdn.com/video/723258267_640.jpg",
    "width": 640,
    "height": 360,
    "last_updated": "2018-09-03T10:04:56.957"
  }
},
```

Now ill try updating to 2.12.2

The migrations worked OK

So now the sites working, somewhere there's a couple of videos missing but we can add them back in I hope.

**Comment by gasman** [comment]
@nickmoreton Glad you got it working. I don't think you need to take any further action to add those records back: the records you had to delete were duplicate records that shouldn't have been there, and in any case, the embeds table only serves as a cache to store the data returned by the embed provider - so even if you did delete something important from there, the only ill effect would be that it has to re-download that data next time someone visits a page using that embed.

**Comment by alramalho** [comment]
I'm having the same issue, when upgrading from wagtail 2.11.
I use MySQL DB and at first the error is exactely the same

Then when I run
```
./manage.py migrate wagtailembeds 0005
./manage.py migrate
```
I face the issue
```
line 133, in _delete_composed_index
    return super()._delete_composed_index(model, fields, *args)
  File "/Users/AlexandreR/Library/Python/3.9/lib/python/site-packages/django/db/backends/base/schema.py", line 437, in _delete_composed_index
    raise ValueError("Found wrong number (%s) of constraints for %s(%s)" % (
ValueError: Found wrong number (0) of constraints for wagtailembeds_embed(url, max_width)
```
In the same `wagtailembeds.0008_allow_long_urls` migration.
Any tip?

**Comment by CCWongVR** [comment]
I just resolved this same issue and the solution is pretty simple, especially if you have a GUI to interact with the database (I'm using HeidiSQL). For reference, I'm on Wagtail 2.13.1 and Django 3.2.4.

1) Drop the wagtailembeds_embed table.
2) Remove all 'wagtailembeds' migrations from the django_migrations table.
3) Run 'python manage.py migrate'.

It'll just rebuild the whole table cleanly.
