### ISSUE TITLE
Pages with missing models and unpublished changes throw error on explorer

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#6817]
### Issue Summary

Ref previous issues #5209, #5928, https://github.com/wagtail/wagtail/pull/5240#issuecomment-654311795 - if the specific model for a page in the tree cannot be found (usually because the model was deleted without first deleting the pages, or the developer is switching between git branches that don't all have the model definition) then editing that page is an error, but it should still be possible the page tree and delete the page. However, if the page's `has_unpublished_changes` flag is set, then the explorer view hits this line

https://github.com/wagtail/wagtail/blob/7b61ee28890a333fffcf6c06f4fbea818c0ba077/wagtail/admin/wagtail_hooks.py#L139

and fails because [`is_previewable` tries to access `preview_modes` on `page.specific_class`](https://github.com/wagtail/wagtail/blob/7b61ee28890a333fffcf6c06f4fbea818c0ba077/wagtail/core/models.py#L2582) which is None.

### Steps to Reproduce

1. On bakerydemo, create a new page type

        class TempPage(Page):
            pass

    and run manage.py makemigrations / migrate

2. In the admin, create a page of type TempPage and save it (not publish)
3. Delete the definition of TempPage and run manage.py makemigrations / migrate
4. In the admin, attempt to view the explorer listing for the TempPage's parent. This throws the error:

```
Internal Server Error: /admin/pages/69/
Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/auth.py", line 187, in overridden_render
    return render()
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/matthew/.virtualenvs/wagtail/lib/python3.8/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/templatetags/wagtailadmin_tags.py", line 446, in page_listing_buttons
    buttons.extend(hook(page, page_perms, is_parent, next_url))
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/admin/wagtail_hooks.py", line 139, in page_listing_buttons
    if page.has_unpublished_changes and page.is_previewable():
  File "/Users/matthew/Development/tbx/wagtail/devscript/wagtail/wagtail/core/models.py", line 2525, in is_previewable
    if page.specific_class.preview_modes != type(page).preview_modes:
AttributeError: 'NoneType' object has no attribute 'preview_modes'
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.0
* Django version: 3.1.5
* Wagtail version: [master (2.13a0)](7b61ee28890a333fffcf6c06f4fbea818c0ba077) and 2.11.4

**Comment by FlipperPA** [comment]
I ran into this bug today. For anyone looking for a fix, you should be able to delete the offending rows from the `Page` model.

- find the offending page in the stack trace
- find the `content_type_id` missing the model, I.e. `Page.objects.filter(title="My Bad Page!")[0].content_type_id`
- remove the pages with something like `Page.objects.filter(content_type_id=12345).delete()`, substituting the appropriate `content_type_id`

**Comment by ankit02327** [comment]
Hi, I’d like to investigate this issue and verify whether it still reproduces on the current `main` branch. If it does, I can work on a fix and add a regression test.
