### ISSUE TITLE
Redirect middleware seems to be incompatible with ASGI

### ISSUE THREAD

**Issue by thenewguy** [wagtail/wagtail#6821]
I've been investigating ASGI.  I am observing this error from the redirect middleware.

``` 
Traceback (most recent call last):
   File "/var/lib/integration/django/core/handlers/exception.py", line 47, in inner
     response = get_response(request)
   File "/var/lib/integration/django/utils/deprecation.py", line 116, in __call__
     response = self.process_response(request, response)
   File "/var/lib/integration/wagtail/contrib/redirects/middleware.py", line 37, in process_response
     if response.status_code != 404:
 AttributeError: 'coroutine' object has no attribute 'status_code'
```

**Comment by thenewguy** [comment]
I've been looking through how these work and its got nothing to do with something you would fix
