### ISSUE TITLE
The content_type attribute on the Document model clashes with custom models with a content_type ForeignKey to ContentType

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#6863]
We have a CustomDocument model with a `content_type = models.ForeignKey(ContentType, ...)` field

https://github.com/wagtail/wagtail/blob/master/wagtail/documents/models.py#L170-L176 is preventing us from upgrading cleanly to 2.11+

One workaround is to rename the field and adding a `db_column="content_type_id"` kwarg on the definition to keep the values, and rewrite loads of code.

I would argue that `content_type = models.ForeignKey(ContentType, ...)` is a typical convention (and we use it with Page https://github.com/wagtail/wagtail/blob/master/wagtail/core/models.py#L748) and that we should change the property on the Document model

**Comment by gasman** [comment]
Hi @zerolab - can you give an example of the kind of error this is causing? Have tried to make a test case out of this at https://github.com/gasman/wagtail/commit/871be296739172a5d61331c4c6c232c239d30433 , but the worst thing that happens is that it doesn't serve PDFs inline (because it's returning an unexpected value for `document.content_type` that doesn't match any of the recognised mime types to be served inline).

**Comment by zerolab** [comment]
Here's a traceback. It only happens when trying to add a new doc

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/views/decorators/vary.py", line 20, in inner_func
    response = func(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/wagtail/admin/views/generic/multiple_upload.py", line 44, in dispatch
    return super().dispatch(request)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/wagtail/admin/views/generic/permissions.py", line 35, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/wagtail/admin/views/generic/multiple_upload.py", line 166, in get_context_data
    self.form = upload_form_class(user=self.request.user)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/wagtail/admin/forms/collections.py", line 106, in __init__
    super().__init__(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/the_site/lib/python3.8/site-packages/django/forms/models.py", line 289, in __init__
    self.instance = opts.model()
  File "/vagrant/the_site/utils/models/mixins.py", line 69, in __init__
    self.content_type = ContentType.objects.get_for_model(self)

Exception Type: AttributeError at /admin/documents/multiple/add/
Exception Value: can't set attribute
```
</details>

**Comment by gasman** [comment]
Thanks @zerolab - could you expand your model code to show where the line `self.content_type = ContentType.objects.get_for_model(self)` in `/vagrant/the_site/utils/models/mixins.py` comes in?

**Comment by gasman** [comment]
Actually, I'm wondering if the use of a mixin is the issue here? If you've defined your document model as

    class CustomDocument(AbstractDocument, MixinThatAddsContentTypeField):

then AbstractDocument's definition of `content_type` as a method will take precedence over the field, breaking the ability to set it as a field - but if you put the mixin first in the ordering (or define the `content_type` field directly on CustomDocument) then the field will take precedence, and the only breakage will be that PDFs won't be served inline (i.e. the same situation as in my test case).

**Comment by zerolab** [comment]
@gasman took more time to look at this without deadlines looming. It is indeed the inheritance precedence 🤦‍♂️ swapping things around allows adding new docs without an issue. It leaves the inline serving breakage which you had a plan for

**Comment by gasman** [comment]
Good to hear! Renaming AbstractDocument's `content_type` to `mimetype` (or `mime_type`? I think there's precedence in Python for the single-word version, but I could be wrong...) is probably still worth doing, then, but if it isn't a blocker for upgrading to 2.11 then we can do that in a feature release with the proper deprecation process.
