### ISSUE TITLE
Storybook 6.3 pre-release breaks npm run build

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#7153]
As of commit 325587c3d2bf463112eef5183f154450f7f93376, building assets with

    nvm use
    npm install --no-save
    npm run build

fails with the error:

```
(node:45983) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'compiler' of undefined
    at /Users/matthew/Development/tbx/wagtail/devscript/wagtail/node_modules/ts-loader/dist/after-compile.js:13:25
    at loader._compilation.hooks.afterProcessAssets.tap (/Users/matthew/Development/tbx/wagtail/devscript/wagtail/node_modules/ts-loader/dist/instances.js:259:84)
    at Hook.eval [as call] (eval at create (/Users/matthew/Development/tbx/wagtail/devscript/wagtail/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/matthew/Development/tbx/wagtail/devscript/wagtail/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at hooks.processAssets.callAsync.err (/Users/matthew/Development/tbx/wagtail/devscript/wagtail/node_modules/webpack/lib/Compilation.js:2469:40)
    at eval (eval at create (/Users/matthew/Development/tbx/wagtail/devscript/wagtail/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:45983) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:45983) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
(While this shows up as a warning rather than an error, it is indeed a hard failure, as verified by `rm wagtail/admin/static/wagtailadmin/js/telepath/*.js` and confirming that those files are not rebuilt.

My installed version of node (as selected by `nvm use`) is v10.16.2. (update: same error on the latest node 10 release, 10.24.1)

**Comment by gasman** [comment]
Same error occurs on node 14.16.1 LTS and 16.0.0.

**Comment by kaedroho** [comment]
This must be caused by the upgrade of Webpack from 5.11.0 to 5.35.1 as Storybook doesn't run during our normal builds.
