### ISSUE TITLE
Error while copying pages when the user does not have publishing permissions for the original location

### ISSUE THREAD

**Issue by roodie** [wagtail/wagtail#7293]
### Issue Summary

Error during article copy if you have a particular set of permissions - if the given user has only editing (and no publishing) permissions on the page tree they copying FROM, but has publication permissions on the page tree they copying TO, then the copy form omits the "alias" checkbox, thus the copy action fails with the following error message:  

`Traceback (most recent call last):
  File "C:\virtualenv\wagtail211\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\virtualenv\wagtail211\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\virtualenv\wagtail211\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\virtualenv\wagtail211\lib\site-packages\wagtail\admin\urls\__init__.py", line 127, in wrapper
    return view_func(request, *args, **kwargs)
  File "C:\virtualenv\wagtail211\lib\site-packages\wagtail\admin\auth.py", line 193, in decorated_view
    return view_func(request, *args, **kwargs)
  File "C:\virtualenv\wagtail211\lib\site-packages\wagtail\admin\auth.py", line 60, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "C:\virtualenv\wagtail211\lib\site-packages\wagtail\admin\views\pages\copy.py", line 56, in copy
    if can_publish and form.cleaned_data['alias']:

Exception Type: KeyError at /admin/pages/7/copy/
Exception Value: 'alias'`

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Create a simple model (for example "ArticlePage", even without a content field), and in the admin, create 2 page trees (lets name them Tree A and Tree B) with an another page under Tree A
3. Create a group where you give view/edit permissions to Tree A, and view/edit/publish permission to Tree B
4. Create a new admin user and assign the group you created
5. Now navigate to Tree A, and try to copy the article to Tree B
6. You will get the error message after the copy form (which does not show the 'alias' checkbox)
7. If you give publish permissions to Tree A, then the alias checbox appears upon copy, and everything works

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: YES

### Technical details

* Django version: 3.1.12
* Wagtail version: 2.12.5 and 2.13.2

**Comment by thibaudcolas** [comment]
It looks like #7313 fixes this in Wagtail 2.15, so will close this now.
