### ISSUE TITLE
Wagtail model ChooserBlock cannot be optional

### ISSUE THREAD

**Issue by MajorFailz** [wagtail/wagtail#7344]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When adding a `ChooserBlock` with a `target_model` field specified, the field works as intended when a model has been selected however if the field is left blank (and required=False) the admin bugs out complaining that it was provided a blank (not None) value for the id. Having a look at the source the method `value_from_form` checks if the value is `None` but not blank and therefore tries to use the empty string as the id, causing the error.

The upshot is you can't have an optional model ChooseBlock.

I can fix this by overriding the method and checking for a blank string and returning `None`:

```
def value_from_form(self, value):
    # ModelChoiceField sometimes returns an ID, and sometimes an instance; we want the instance
    if value is None or isinstance(value, self.target_model):
        return value
    elif value == '':
        return None
    else:
        try:
            print('honk')
            print(value)
            return self.target_model.objects.get(pk=value)
        except self.target_model.DoesNotExist:
            return None
```

### Steps to Reproduce

What happens:
1. Extend ChooserBlock and add `target_model = MyModel` and `widget = django.forms.Select`
2. Include extended class in a page or other block with `required = False` as an option
3. Create a page, add the block and do not select a model
4. Attempt to publish / save page
5. Error occurs (see stack in Technical details)

What should happen:
Page saves and provides `None` value when rendering block.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

* Python version: Python 3.8.11
* Django version: 3.1
* Wagtail version: 2.13.4
* Browser version: Chrome v91

### Stack trace

```
Environment:


Request Method: POST
Request URL: http://warrior:9000/cms/pages/3/edit/

Django Version: 3.1.13
Python Version: 3.8.11
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.flatpages',
 'haystack',
 'oscar.config.Shop',
 'oscar.apps.analytics.apps.AnalyticsConfig',
 'project.apps.checkout.apps.CheckoutConfig',
 'oscar.apps.address.apps.AddressConfig',
 'oscar.apps.shipping.apps.ShippingConfig',
 'project.apps.catalogue.apps.CatalogueConfig',
 'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
 'oscar.apps.communication.apps.CommunicationConfig',
 'oscar.apps.partner.apps.PartnerConfig',
 'oscar.apps.basket.apps.BasketConfig',
 'oscar.apps.payment.apps.PaymentConfig',
 'oscar.apps.offer.apps.OfferConfig',
 'oscar.apps.order.apps.OrderConfig',
 'oscar.apps.customer.apps.CustomerConfig',
 'oscar.apps.search.apps.SearchConfig',
 'oscar.apps.voucher.apps.VoucherConfig',
 'oscar.apps.wishlists.apps.WishlistsConfig',
 'oscar.apps.dashboard.apps.DashboardConfig',
 'oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
 'oscar.apps.dashboard.users.apps.UsersDashboardConfig',
 'oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
 'oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
 'oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
 'oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
 'oscar.apps.dashboard.pages.apps.PagesDashboardConfig',
 'oscar.apps.dashboard.ranges.apps.RangesDashboardConfig',
 'oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig',
 'oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig',
 'oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig',
 'oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'wagtailcaptcha',
 'wagtailgmaps',
 'captcha',
 'django_extensions',
 'django_filters',
 'widget_tweaks',
 'treebeard',
 'sorl.thumbnail',
 'django_tables2',
 'project.apps.core',
 'project.apps.cookies',
 'project.apps.users',
 'project.apps.admin',
 'project.apps.site']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.common.BrokenLinkEmailsMiddleware',
 'oscar.apps.basket.middleware.BasketMiddleware',
 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)

The above exception (invalid literal for int() with base 10: '') was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 108, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/views/pages/edit.py", line 224, in dispatch
    return super().dispatch(request)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/views/pages/edit.py", line 310, in post
    if self.form.is_valid() and not self.page_perms.page_locked():
  File "/usr/local/lib/python3.8/site-packages/wagtail/admin/forms/pages.py", line 150, in is_valid
    return super().is_valid()
  File "/usr/local/lib/python3.8/site-packages/modelcluster/forms.py", line 316, in is_valid
    form_is_valid = super(ClusterForm, self).is_valid()
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 374, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 386, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/base.py", line 535, in value_from_datadict
    return self.block_def.value_from_datadict(data, files, name)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/stream_block.py", line 114, in value_from_datadict
    child_block.value_from_datadict(data, files, '%s-%d-value' % (prefix, i)),
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/struct_block.py", line 107, in value_from_datadict
    return self._to_struct_value([
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/struct_block.py", line 108, in <listcomp>
    (name, block.value_from_datadict(data, files, '%s-%s' % (prefix, name)))
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/field_block.py", line 48, in value_from_datadict
    return self.value_from_form(self.field.widget.value_from_datadict(data, files, prefix))
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/blocks/field_block.py", line 695, in value_from_form
    return self.target_model.objects.get(pk=value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1360, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1379, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1321, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1167, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(

Exception Type: ValueError at /cms/pages/3/edit/
Exception Value: Field 'id' expected a number but got ''.
```

**Comment by dragon-dxw** [comment]
I've hit much the same error. My fix (based on yours) was simply:
```
def value_from_form(self, value):
        if value == "":
            return None
        else:
            return super().value_from_form(value)
```
