### ISSUE TITLE
Support for Pymemcache

### ISSUE THREAD

**Issue by krzysztofjeziorny** [wagtail/wagtail#7419]
Django with the version 3.2 [supports](https://docs.djangoproject.com/en/3.2/releases/3.2/#pymemcache-support) `Pymemcache`, and `MemcachedCache` is deprecated:

>The MemcachedCache backend is deprecated as python-memcached has some problems and seems to be unmaintained. Use PyMemcacheCache or PyLibMCCache instead.
([source](https://docs.djangoproject.com/en/3.2/topics/cache/#memcached))

Are there any plans for implementing Pymemcache?

**Comment by RealOrangeOne** [comment]
Is there anything Wagtail needs to do to support this explicitly? Just pymemcache as a cache backend should "just work", as the compatibilities are handled by Django, right?

**Comment by zerolab** [comment]
That should be the case indeed. 

The only `MemcachedCache` reference we have is in the docs for the rendition cache example: https://docs.wagtail.io/en/stable/advanced_topics/performance.html#caching-image-renditions

**Comment by RealOrangeOne** [comment]
If you're having a specific issue though, we'd love to hear about it!

**Comment by krzysztofjeziorny** [comment]
Setting `PyMemcacheCache` as a backend gives now:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wagtail/core/models.py", line 1683, in _get_site_root_paths
    return cache_object._wagtail_cached_site_root_paths
```

Maybe it's my site's specific? `MemcachedCache` still works though.
I'm on Django 3.2.6 and Wagtail 2.13.4.

**Comment by zerolab** [comment]
@krzysztofjeziorny can you include the full traceback please? the bit you've shared doesn't provide much information

**Comment by krzysztofjeziorny** [comment]
@zerolab Sure, here's the traceback.

```
Environment:


Request Method: GET
Request URL: https://domain.tld/

Django Version: 3.2.6
Python Version: 3.7.3
Installed Applications:
['wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.settings',
 'django.contrib.sitemaps',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wagtail.contrib.routable_page',
 'core',
 'gallery',
 'search',
 'wagtail.contrib.postgres_search']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']


Template error:
In template /path/to/templates/base.html, error at line 9
   2
   1 : {% load static i18n wagtailuserbar navigation_tags my_tags %}
   2 : <!DOCTYPE html>
   3 : <html class="no-js" lang="en" dir="ltr" prefix="og: http://ogp.me/ns#">
   4 :     <head>
   5 :         <meta charset="utf-8">
   6 :         <meta name="viewport" content="width=device-width">
   7 :         <title>
   8 :             {% block title %}{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}{% endblock %}
   9 :             {% block title_suffix %} {% with self.get_site.site_name as site_name %} {% if site_name %} — {{ site_name }}{% endif %}{% endwith %}{% endblock %}
   10 :         </title>
   11 :         <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
   12 :         {% block css %}{% endblock %}
   13 :         <script>
   14 :             (localStorage.getItem('theme')) && document.documentElement.setAttribute('data-theme', localStorage.getItem('theme'))
   15 :         </script>
   16 :         <meta name="description" content="{% if self.search_description %}{{ self.search_description }}{% else %}{{ self.body|striptags|truncatewords:20 }}{% endif %}">
   17 :         <meta property="og:title" content="{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %} {% with self.get_site.site_name as site_name %} {% if site_name %}- {{ site_name }}{% endif %}{% endwith %}">
   18 :         <meta property="og:description" content="{% if self.search_description %}{{ self.search_description }}{% else %}{{ self.body|striptags|truncatewords:20 }}{% endif %}">        
   19 :         <meta property="og:url" content="{{ page.full_url }}">


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wagtail/core/models.py", line 1683, in _get_site_root_paths
    return cache_object._wagtail_cached_site_root_paths

During handling of the above exception ('StandardPage' object has no attribute '_wagtail_cached_site_root_paths'), another exception occurred:
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.7/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.7/dist-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.7/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 514, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 514, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/dist-packages/wagtail/core/models.py", line 1831, in get_site
    url_parts = self.get_url_parts()
  File "/usr/local/lib/python3.7/dist-packages/wagtail/core/models.py", line 1708, in get_url_parts
    for pk, path, url, language_code in self._get_site_root_paths(request)
  File "/usr/local/lib/python3.7/dist-packages/wagtail/core/models.py", line 1685, in _get_site_root_paths
    cache_object._wagtail_cached_site_root_paths = Site.get_site_root_paths()
  File "/usr/local/lib/python3.7/dist-packages/wagtail/core/models.py", line 307, in get_site_root_paths
    result = cache.get('wagtail_site_root_paths')
  File "/usr/local/lib/python3.7/dist-packages/django/core/cache/backends/memcached.py", line 77, in get
    return self._cache.get(key, default)
  File "/usr/local/lib/python3.7/dist-packages/pymemcache/client/hash.py", line 361, in get
    return self._run_cmd('get', key, None, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymemcache/client/hash.py", line 335, in _run_cmd
    client, func, default_val, *args, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/pymemcache/client/hash.py", line 214, in _safely_run_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymemcache/client/base.py", line 619, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/usr/local/lib/python3.7/dist-packages/pymemcache/client/base.py", line 1018, in _fetch_cmd
    self._connect()
  File "/usr/local/lib/python3.7/dist-packages/pymemcache/client/base.py", line 420, in _connect
    sock.connect(sockaddr)

Exception Type: FileNotFoundError at /
Exception Value: [Errno 2] No such file or directory
```

**Comment by RealOrangeOne** [comment]
The issue there appears to be that `pymemcache` cannot connect to the socket, which it appears to be looking for in `/` for some reason.

Is your `CACHES` definitely setup correctly? See https://docs.djangoproject.com/en/3.2/topics/cache/#memcached. Also if you open the shell and try to use `caches.get` / `caches.set` (ie the Django native APIs https://docs.djangoproject.com/en/3.2/topics/cache/#basic-usage) manually, does it work?

**Comment by krzysztofjeziorny** [comment]
It works when `LOCATION` is set to an ip:port (`'LOCATION': '127.0.0.1:11211',`)
It fails with setting of a sock file.

```python
>>> from django.core.cache import cache
>>> cache.set('my_key', 'hello, world!', 30)
>>> cache.get('my_key')
'hello, world!'
>>>
```

`MemcachedCache`, `python-memcached` 1.59 
`PyMemcacheCache`, `pymemcache` 3.5.0

**Comment by RealOrangeOne** [comment]
Huh that's strange!

Can't tell from here whether it's a Django bug or a `PyMemcache` bug, but fairly confident it's not a Wagtail given you can reproduce it without touching Wagtail at all.

Best thing to do is try a minimal example using just `PyMemcache` (https://pymemcache.readthedocs.io/en/latest/getting_started.html). If you see the issue, it's a `PyMemcache` bug. If you don't, it's probably a Django bug. Either way, something to open against the relevant project's issue tracker.

**Comment by krzysztofjeziorny** [comment]
You're absolutely right, @RealOrangeOne. Thanks for pointing me in the right direction! I'm closing it here.
