### ISSUE TITLE
Namespace conflict between "comment" / "comments" and admin comments introduced in 2.13

### ISSUE THREAD

**Issue by awhileback** [wagtail/wagtail#7476]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

This has been reported (#7343) but the person reporting it did not tag it as a bug and I think it should be a bug.

### Steps to Reproduce

1. install wagtail, make a basic page model
2. install [django-comments-dab](https://github.com/Radi85/Comment), add it to that page model to add comment functionality to said page
3. add some comments to an instance of the wagtail page
4. edit the instance of the wagtail page in the wagtail admin

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

```
Internal Server Error: /admin/pages/45/edit/
Traceback (most recent call last):
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/wagtail/admin/auth.py", line 187, in overridden_render
    return render()
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 305, in render
    match = condition.eval(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/defaulttags.py", line 889, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/modelcluster/forms.py", line 323, in is_multipart
    or any(formset.is_multipart() for formset in self.formsets.values())
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/modelcluster/forms.py", line 323, in <genexpr>
    or any(formset.is_multipart() for formset in self.formsets.values())
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/forms/formsets.py", line 427, in is_multipart
    if self.forms:
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/forms/formsets.py", line 155, in forms
    return [
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/forms/formsets.py", line 156, in <listcomp>
    self._construct_form(i, **self.get_form_kwargs(i))
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/modelcluster/forms.py", line 41, in _construct_form
    return super(BaseModelFormSet, self)._construct_form(i, **kwargs)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/django/forms/formsets.py", line 193, in _construct_form
    form = self.form(**defaults)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/modelcluster/forms.py", line 296, in __init__
    self.formsets[rel_name] = formset_class(data, files, instance=instance, prefix=formset_prefix)
  File "/Users/ausername/Dropbox/wagdev/siteenv/lib/python3.8/site-packages/modelcluster/forms.py", line 85, in __init__
    queryset = getattr(self.instance, self.rel_name).all()
AttributeError: 'function' object has no attribute 'all'
```

It seems that wagtail finds the comment app's comment model before the wagtail comment model, and thus begins a cascade of errors due to the wrong comment/comments not having the same methods as the wagtail admin comment/comments.

The only way to simply fix this on the user's end is to disable wagtail admin comments entirely.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (yes / no)

yes

### Technical details

* Python version: Run `python --version`.
* Django version: Look in your requirements.txt, or run `pip show django | grep Version`.
* Wagtail version: Look at the bottom of the Settings menu in the Wagtail admin, or run `pip show wagtail | grep Version:`.
* Browser version: You can use https://www.whatsmybrowser.org/ to find this out.

**Comment by awhileback** [comment]
addition to this: if the user has overridden the save method of a page model, `super().save(*args, **kwargs)` will try to save 'comments' even if the wagtail comments are disabled via settings.  So I guess I have to downgrade wagtail at this point until there's a fix.
