### ISSUE TITLE
Calling update_or_create on model manager throws DoesNotExist exception

### ISSUE THREAD

**Issue by vladox** [wagtail/wagtail#7515]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When creating pages programmatically by invoking update_or_create on model manager an exception is raised.

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Edit models.py as follows:
```
from django.db.models import TextField
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.core.models import Page


class TestPage(Page):
    
    body = TextField()

    content_panels = Page.content_panels + [FieldPanel('body')]

```
3. Create custom management command as follows:

```
from django.core.management.base import BaseCommand
from wagtail.core.models import Site

from test_app.models import TestPage


class Command(BaseCommand):
    help = 'Simple page addition test'

    def handle(self, *args, **options):
        current_site = Site.objects.first()

        page_title = "This will be awesome"
        page_body = "yes indeed"
        test_page, created = TestPage.objects.update_or_create(
            defaults={'title': page_title},
            body=page_body)
        if created:
            current_site.root_page.add_child(instance=test_page)

        test_page.save_revision()
``` 

4. On running the custom management command following exception is thrown:
`python manage.py test_update_or_create`  

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 589, in update_or_create
    obj = self.select_for_update().get(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
home.models.DoesNotExist: TestPage matching query does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/project/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/project/home/management/commands/test_update_or_create.py", line 23, in handle
    test_page, created = TestPage.objects.update_or_create(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 594, in update_or_create
    obj, created = self._create_object_from_params(kwargs, params, lock=True)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models/__init__.py", line 481, in save
    self.full_clean()
  File "/usr/local/lib/python3.8/site-packages/wagtail/core/models/__init__.py", line 440, in full_clean
    super().full_clean(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1231, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'path': ['This field cannot be blank.'], 'depth': ['This field cannot be null.']}

```

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project:  yes 

### Technical details

* Python version: 3.8.1.
* Django version: 3.1.13.
* Wagtail version: 2.14.1.
* Browser version: Chrome 92.

**Comment by vladox** [comment]
a public repo with a dockerized example is available here: https://github.com/elpatiostudio/wagtail_test_update_or_create

**Comment by gasman** [comment]
Hi @vladox - this behaviour is expected. `add_child` must be passed an _unsaved_ Page instance, because a page is not valid until it has been assigned a place in the tree.

**Comment by vladox** [comment]
Hi @gasman thanks for the answer! Is this documented somewhere? Because I couldn't find any mention to it. I'll be glad to contribute it if not already documented. Thanks!
