### ISSUE TITLE
Missing admin notification of type and location of validation errors in StreamField with nested StructBlock. 

### ISSUE THREAD

**Issue by JeremyGibson** [wagtail/wagtail#7840]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

There are a few different closed issues with similarities to this one, but we can still reproduce this problem.
1. https://github.com/wagtail/wagtail/issues/5300
2. https://github.com/wagtail/wagtail/issues/7248

Versions of Wagtail 2.11.8 and below are not subject to this bug.

### Steps to Reproduce

1. Start a new project on a version 2.12 or above with `wagtail start myproject`
2. Add the following to `models.py`

```python
from django.core.exceptions import ValidationError
from django.forms.utils import ErrorList

from wagtail.admin.edit_handlers import StreamFieldPanel
from wagtail.core import blocks
from wagtail.core.fields import StreamField
from wagtail.core.models import Page

from wagtail.documents.blocks import DocumentChooserBlock


class CopyBlock(blocks.StructBlock):
    text = blocks.RichTextBlock(required=True)


class LinkBase(blocks.StructBlock):

    def __init__(self, **kwargs):
        super().__init__()
        self._required = kwargs.get("required", False)

    internal_link = blocks.PageChooserBlock(required=False, help_text="Internal page")
    document_link = DocumentChooserBlock(required=False, help_text="Choose a document")
    external_link = blocks.URLBlock(required=False, help_text="External URL")

    @property
    def link_types(self):
        """
        Register link fields on subclasses for proper validation
        """
        return ["internal_link", "document_link", "external_link"]

    # Override base required property of wagtail Block, which currently always
    # returns False.
    @property
    def required(self):
        return self._required


class LinkBlockBase(LinkBase):
    display_text = blocks.CharBlock(
        required=False,
        help_text="Text to display for the link. If left blank, page or document title will be used",
    )

    def clean(self, value):
        """
        Ensure that:
            if display_text is provided or this block is "required", exactly one link is provided.
            if display_text is not provided, zero or one links are provided.
            if the provided link is external, display text is provided
        """
        value = super().clean(value)
        errors = {}
        error = None

        links_present = [l for l in self.link_types if value.get(l)]
        display_text = value.get("display_text")

        # If there is no display text, and this block is not marked required,
        # no links are needed. But one is needed if there is display_text,
        # or if this block is required.
        min_links = 1 if display_text or self.required else 0
        link_count = len(links_present)

        # If more than one link type was provided, deliver an error to
        # each one specified. Otherwise, if one is needed but none
        # provided, deliver an error to every single field where the
        # the link could have been provided.
        if link_count > 1:
            error = ValidationError("Only one link type may be specified.")
            errors = {key: ErrorList(error) for key in links_present}
        elif link_count < min_links:
            error = ValidationError("One link type must be provided.")
            errors = {key: ErrorList(error) for key in self.link_types}

        # If user selects "external_link", display_text must be provided
        if value.get("external_link") and not display_text:
            errors.update(
                {"display_text": ErrorList([ValidationError("Display text is required if using an external link")])}
            )

        if errors:
            raise ValidationError("Link block validation error", params=errors)
        return value

    class Meta:
        icon = "link"


class CTAButtonBlock(LinkBlockBase):
    styled_as_primary = blocks.BooleanBlock(required=False, initial=False, help_text="Styled to draw attention")

    class Meta:
        template = "gp_wagtail_block_library/blocks/cta_button_block.html"


class GridLayoutBlock(blocks.StructBlock):
    body = blocks.StreamBlock(
        [
            ('copy', CopyBlock()),
            ('cta', CTAButtonBlock())
        ]
    )


class HomePage(Page):
    pass


class CustomPage(Page):
    body = StreamField([
        ('grid', GridLayoutBlock())
    ])

    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```

3. migrate and runserver
4. Create a Page and add the `cta` block to the page.
5. Add `display_text` to the `cta` block.
6. Do **not** add a link of any type
7. Save the page.
8. Note that the Page will not indicate the number or type of error.
9. Next back level to wagtail 2.11.8 and follow the same steps.
10. Observe
    - The error badge appears on the content tab with the correct number.
    - The block supplied error message is found under each field in error.

This seems to be a bug, or at least a deficit in documentation on how to properly configure StructBlock `clean` validation errors on 
Wagtail version later than 2.11.8.  I would expect the behavior found in 2.11.8 to persist into later versions, or an explicit mention about ErrorValidation API changes in the Changelog.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes.

### Technical details

* Python version: 3.9.6.
* Django version: Django >=3.0.6.
* Wagtail version: 2.12 and above.
* Browser version: Chrome 97

**Comment by zerolab** [comment]
Hey @JeremyGibson thank you for the detailed issue.
This looks very similar to #7202. Try changing `ValidationError` to `StructBlockValidationError`.

[This comment](https://github.com/wagtail/wagtail/issues/7202#issuecomment-922935349) outlines what we need to do (or better said, that we need to redesign the validation for StructBlock / ListBlock / StreamBlock to be more user friendly)

**Comment by JeremyGibson** [comment]
@zerolab Thanks for you response.  After changing to `StructBlockValidationError` on 2.15.1. 

```python
        # If more than one link type was provided, deliver an error to
        # each one specified. Otherwise, if one is needed but none
        # provided, deliver an error to every single field where the
        # the link could have been provided.
        if link_count > 1:
            error = StructBlockValidationError("Only one link type may be specified.")
            errors = {key: ErrorList(error) for key in links_present}
        elif link_count < min_links:
            error = StructBlockValidationError("One link type must be provided.")
            errors = {key: ErrorList(error) for key in self.link_types}

        # If user selects "external_link", display_text must be provided
        if value.get("external_link") and not display_text:
            errors.update(
                {"display_text": ErrorList([StructBlockValidationError("Display text is required if using an external link")])}
            )

        if errors:
            raise StructBlockValidationError("Link block validation error", params=errors)
        return value
```

The page 500s on save with the following error:

`TypeError: not all arguments converted during string formatting`

```python
2022-01-11 13:34:59,550 django.request       ERROR    Internal Server Error: /cms/pages/add/test_project/custompage/1/
Traceback (most recent call last):
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/admin/auth.py", line 195, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/admin/views/pages/create.py", line 98, in dispatch
    return super().dispatch(request)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/admin/views/pages/create.py", line 105, in post
    if self.form.is_valid():
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/admin/forms/pages.py", line 150, in is_valid
    return super().is_valid()
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/modelcluster/forms.py", line 318, in is_valid
    form_is_valid = super(ClusterForm, self).is_valid()
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/forms/forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/forms/forms.py", line 376, in full_clean
    self._clean_fields()
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/forms/forms.py", line 394, in _clean_fields
    value = field.clean(value)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/core/blocks/base.py", line 554, in clean
    return self.block.clean(value)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/core/blocks/stream_block.py", line 137, in clean
    (child.block.name, child.block.clean(child.value), child.id)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/core/blocks/struct_block.py", line 123, in clean
    result.append((name, self.child_blocks[name].clean(val)))
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/wagtail/core/blocks/stream_block.py", line 137, in clean
    (child.block.name, child.block.clean(child.value), child.id)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/apps/test_project/models.py", line 76, in clean
    errors = {key: ErrorList(error) for key in self.link_types}
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/apps/test_project/models.py", line 76, in <dictcomp>
    errors = {key: ErrorList(error) for key in self.link_types}
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/forms/utils.py", line 85, in __init__
    super().__init__(initlist)
  File "/home/jgibson/.pyenv/versions/3.9.6/lib/python3.9/collections/__init__.py", line 1142, in __init__
    self.data = list(initlist)
  File "/home/jgibson/local_dev/tsc/support_projects/wagtail_tests/test_project/.direnv/python-3.9.6/lib/python3.9/site-packages/django/core/exceptions.py", line 174, in __iter__
    message %= error.params
TypeError: not all arguments converted during string formatting

```

**Comment by JeremyGibson** [comment]
Additionally, I noticed that the `__init__` for the `StructBlockValidationError` isn't exactly the same so I matched by calling

```python
    raise StructBlockValidationError(block_errors=errors)
```

That also resulted in the same 500.

**Comment by zerolab** [comment]
The `errors` dict should have a list of message strings. e.g.

```python
errors.update(
    {"display_text": ErrorList([StructBlockValidationError("Display text is required if using an external link")])}
)
```
should be

```python
errors.update(
    {"display_text": ErrorList(["Display text is required if using an external link"])}
)
```

but leave the `raise StructBlockValidationError()`

I do suggest joining the [Wagtail Slack](https://github.com/wagtail/wagtail/wiki/Slack) if you haven't done so already. There's a fair active `#support` channel

**Comment by zerolab** [comment]
Closing this in favour of #7202 (and on the basis that, yes, we do need to make this more user friendly as at the moment it is not an official, documented API).

Thank you again for raising this and providing the additional detail. It will come in handy when someone gets to work on this. Suggestions are most welcome on #7202
