### ISSUE TITLE
Wagtail 2.16 Invalid HTTP_HOST header: 'localhost:8000:8000'

### ISSUE THREAD

**Issue by aliceni81** [wagtail/wagtail#7942]
Automatic redirect creation is a new feature in Wagtail 2.16. 

But when the program runs with WAGTAILREDIRECTS_AUTO_CREATE = True(by default), an error "**Invalid HTTP_HOST header: 'localhost:8000:8000'. The domain name provided is not valid according to RFC 1034/1035.**" will raise for changing page slug as well as moving page to another location.
I found that this problem can be handled by setting WAGTAILREDIRECTS_AUTO_CREATE = False.
Any other solution for this case?

**Comment by gasman** [comment]
Hi @aliceni81 - can you give the full stack trace of the error, please?

**Comment by zerolab** [comment]
Managed to replicate this locally. 

<details>
<summary>Traceback</traceback>

```
Environment:


Request Method: POST
Request URL: http://wagtail.test:8000/admin/pages/83/move/76/confirm/

Django Version: 4.0.2
Python Version: 3.8.12
Installed Applications:
['bakerydemo.base',
 'bakerydemo.blog',
 'bakerydemo.breads',
 'bakerydemo.locations',
 'bakerydemo.search',
 'wagtail.contrib.search_promotions',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.contrib.settings',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.api.v2',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.routable_page',
 'wagtail.core',
 'rest_framework',
 'modelcluster',
 'taggit',
 'wagtailfontawesome',
 'corsheaders',
 'bakerydemo.custommedia',
 'wagtailmedia',
 'wagtailmarkdown',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'wagtail.contrib.styleguide']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.8/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/vagrant/wagtail/wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "/vagrant/wagtail/wagtail/admin/auth.py", line 174, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/vagrant/wagtail/wagtail/admin/views/pages/move.py", line 72, in move_confirm
    action.execute()
  File "/vagrant/wagtail/wagtail/core/actions/move_page.py", line 109, in execute
    return self._move_page(self.page, self.target, pos=self.pos)
  File "/vagrant/wagtail/wagtail/core/actions/move_page.py", line 79, in _move_page
    post_page_move.send(
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 170, in send
    return [
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 171, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/vagrant/wagtail/wagtail/contrib/redirects/signal_handlers.py", line 85, in autocreate_redirects_on_page_move
    create_redirects(page=instance, page_old=page_old, sites=sites)
  File "/vagrant/wagtail/wagtail/contrib/redirects/signal_handlers.py", line 127, in create_redirects
    old_urls = _page_urls_for_sites(page_old, sites, cache_target=page)
  File "/vagrant/wagtail/wagtail/contrib/redirects/signal_handlers.py", line 98, in _page_urls_for_sites
    site_id, root_url, page_path = page.get_url_parts(request)
  File "/vagrant/wagtail/wagtail/core/models/__init__.py", line 1125, in get_url_parts
    site = Site.find_for_request(request)
  File "/vagrant/wagtail/wagtail/core/models/sites.py", line 97, in find_for_request
    site = Site._find_for_request(request)
  File "/vagrant/wagtail/wagtail/core/models/sites.py", line 103, in _find_for_request
    hostname = split_domain_port(request.get_host())[0]
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.8/site-packages/django/http/request.py", line 135, in get_host
    raise DisallowedHost(msg)

Exception Type: DisallowedHost at /admin/pages/83/move/76/confirm/
Exception Value: Invalid HTTP_HOST header: 'wagtail.test:8000:8000'. The domain name provided is not valid according to RFC 1034/1035.
```
</details>
