### ISSUE TITLE
Wagtail docs - build errors due to Revision model mixin

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#8567]
Getting a bunch of new errors when building the docs, looks like it is due to the `Revision` model changes.

```
WARNING: autodoc: failed to import method 'Revision.as_object' from module 'wagtail.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 440, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'wagtail.models' has no attribute 'Revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 102, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2827, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 456, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Revision

WARNING: autodoc: failed to import method 'Revision.approve_moderation' from module 'wagtail.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 440, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'wagtail.models' has no attribute 'Revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 102, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2827, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 456, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Revision

WARNING: autodoc: failed to import method 'Revision.reject_moderation' from module 'wagtail.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 440, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'wagtail.models' has no attribute 'Revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 102, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2827, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 456, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Revision

WARNING: autodoc: failed to import method 'Revision.is_latest_revision' from module 'wagtail.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 440, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'wagtail.models' has no attribute 'Revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 102, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2827, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 456, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Revision

WARNING: autodoc: failed to import method 'Revision.publish' from module 'wagtail.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 440, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'wagtail.models' has no attribute 'Revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 102, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2827, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 456, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Revision

WARNING: autodoc: failed to import attribute 'Revision.content_object' from module 'wagtail.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 440, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'wagtail.models' has no attribute 'Revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 102, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2827, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 456, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Revision

WARNING: autodoc: failed to import attribute 'Revision.specific_content_object' from module 'wagtail.models'; the following exception was raised:
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 440, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'wagtail.models' has no attribute 'Revision'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 102, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 327, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2827, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/vagrant/.virtualenvs/bakerydemo/lib/python3.9/site-packages/sphinx/util/inspect.py", line 456, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Revision
```

**Comment by lb-** [comment]
@laymonage or @kaedroho - just saw these errors when doing some docs validations, might be good to try to fix up if possible or not sure if this will resolve itself when the main revisions work is done.

**Comment by laymonage** [comment]
Seems to compile just fine for me...?

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/6379424/169430408-52bd6fd6-1511-4496-9a7c-d525d656507e.png">

> ```
> AttributeError: module 'wagtail.models' has no attribute 'Revision'
> ```

This sounds like the `Revision` model doesn't exist in your local copy of the codebase. Maybe you switched to a different branch or something?

**Comment by lb-** [comment]
Ok. I'll have another look. 
Thanks.

**Comment by lb-** [comment]
yep - I had not updated my requirements recently thanks for the help @laymonage
