### ISSUE TITLE
Search on MySQL ProgrammingError(1064, "syntax error, unexpected ')'")

### ISSUE THREAD

**Issue by berycz** [wagtail/wagtail#8614]
### Searching non-word characters between whitespace characters raises an exception

examples which raise an exception:
`ice & fire`
`ice - fire`
`ice + fire`
`ice # fire`
`💙 fire 💙`

the exceptions:
`ProgrammingError(1064, "syntax error, unexpected ')'")`
`ProgrammingError(1064, "syntax error, unexpected '+'")` (on the `💙 fire 💙`)

these work (or at least they don't raise an exception):
`ice fire`
`ice _ fire`
`ice&fire`
`ice-fire`
`ice+fire`
`ice#fire`
`💙fire`

I'm not the only one experiencing this - https://github.com/wagtail/wagtail/discussions/8094

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.10.2
* Django version: 4.0.4
* Wagtail version: 3.0
* Browser version: tested on Firefox and Chrome

**Comment by lb-** [comment]
@berycz could you possibly update / add exact steps to reproduce?

How were you searching these strings? Were you using the util  `wagtail.search.utils.parse_query_string` ?

This may be another similar case of the way strings are parsed - see https://github.com/wagtail/wagtail/issues/9951 & https://github.com/wagtail/wagtail/issues/7961

**Comment by berycz** [comment]
It happens in wagtail 3.0 + mysql, I tested v4 + pg and it works there

It does that in the admin search as well as in the web search
where I didn't touch the wagtail admin search
the web search I have more or less the default view from wagtail 3 which is [here](https://github.com/wagtail/wagtail/blob/stable/3.0.x/wagtail/project_template/search/views.py) 

here is the traceback from the admin search:
```
Request Method: GET
Request URL: https://example.com/admin/pages/search/?q=ice%20%26%20fire

Django Version: 4.0.8
Python Version: 3.10.2
Installed Applications:
['home',
 'feeds',
 'search',
 'users',
 'web',
 'extended_admin',
 'django_celery_results',
 'django.contrib.sitemaps',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.table_block',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'modelcluster',
 'taggit',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'tiutils.redirect.RedirectMiddleware']



Traceback (most recent call last):
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)

The above exception ((1064, "syntax error, unexpected ')'")) was the direct cause of the following exception:
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 161, in wrapper
    return view_func(request, *args, **kwargs)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/views/decorators/vary.py", line 21, in inner_func
    response = func(*args, **kwargs)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/wagtail/admin/auth.py", line 62, in wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/wagtail/admin/views/pages/search.py", line 107, in search
    for content_type_id, count in all_pages.facet(
  File "/srv/virtuals/testing/lib/python3.10/site-packages/wagtail/search/backends/database/mysql/mysql.py", line 559, in facet
    query = self.query_compiler.search(
  File "/srv/virtuals/testing/lib/python3.10/site-packages/wagtail/search/backends/database/mysql/mysql.py", line 475, in search
    object_ids = {
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/models/query.py", line 320, in __iter__
    self._fetch_all()
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/srv/virtuals/testing/lib/python3.10/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)

Exception Type: ProgrammingError at /adm/pages/search/
Exception Value: (1064, "syntax error, unexpected ')'")
```

**Comment by gasman** [comment]
Confirmed on current Wagtail main. Steps to reproduce:

```
wagtail start mysqlsearch
cd mysqlsearch
pip install mysqlclient
```

in settings/base.py, change DATABASES to

```
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "wagtailmysqlsearch",
        "USER": "root",
    }
}
```

within `mysql -uroot`, run `create database wagtailmysqlsearch;`

```
./manage.py migrate
./manage.py runserver
```

Visit http://localhost:8000/search/ and enter `ice & fire` in the search box - receive `(1064, "syntax error, unexpected ')'")
` as per above.

**Comment by gasman** [comment]
The out-of-the-box search functionality from the project template does not use `parse_query_string` - it [passes the entered search query straight to `.search()` as a string](https://github.com/wagtail/wagtail/blob/4f36562de7f1461de6202f4bd44b58cbbee00833/wagtail/project_template/search/views.py#L9-L14) - so the expected behaviour would be to treat this as a literal string, and escape or strip out any characters that have special meaning in MySQL's FTS implementation.

**Comment by gasman** [comment]
A minimal snippet to reproduce the error, replicating what the search backend is doing internally:

```python
from wagtail.search.backends.database.mysql.query import Lexeme, MatchExpression, SearchQuery
from wagtail.search.models import IndexEntry
from django.db.models.fields import BooleanField

lexemes = Lexeme('fire', invert=False, prefix=False) & Lexeme('&', invert=False) & Lexeme('ice', invert=False)
search_query = SearchQuery(lexemes)

match_expression = MatchExpression(
    search_query, columns=["title", "body"], output_field=BooleanField()
)
index_entries = IndexEntry.objects.filter(match_expression)
list(index_entries)
```

Looks like the problem is in [`Lexeme.as_sql()`](https://github.com/wagtail/wagtail/blob/d4544ec9ee83546117d19665e9a2d1edc567ecc9/wagtail/search/backends/database/mysql/query.py#L57-L71) - non-word characters are stripped out, which means that `Lexeme('&')` ends up as an empty value. It still goes on to try to use that token when constructing the final SQL expression, and since MySQL's search syntax uses unquoted words, it ends up as the equivalent of `(fire + ice + )` which is a syntax error.

**Comment by rjbullock** [comment]
I'm having this issue as well with Wagtail 5.2 running on Django 3.2.25. Looks like no movement or solution so far.
