### ISSUE TITLE
Random "'NoneType' object has no attribute '_meta'" in Group Detail Page.

### ISSUE THREAD

**Issue by uroybd** [wagtail/wagtail#8678]
This error shows up randomly upon accessing any Group's detail view. In addition to the Traceback, I'm running the application on docker (Docker version 20.10.17, build 100c701) using an `ubuntu:jammy` image.

### Traceback

```
Environment:


Request Method: GET
Request URL: https://toyota.com.bd/admin/groups/1/

Django Version: 3.2.13
Python Version: 3.10.4
Installed Applications:
['pages',
 'search',
 'others',
 'wagtail.contrib.settings',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.api.v2',
 'wagtail.contrib.modeladmin',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wagtail.contrib.table_block',
 'wagtail.contrib.styleguide',
 'wagtailmenus',
 'rest_framework',
 'corsheaders',
 'instance_selector',
 'wagtail_adminsortable',
 'takata']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/app/server/__pypackages__/3.10/lib/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/app/server/__pypackages__/3.10/lib/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/server/__pypackages__/3.10/lib/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/app/server/__pypackages__/3.10/lib/wagtail/admin/urls/__init__.py", line 161, in wrapper
    return view_func(request, *args, **kwargs)
  File "/app/server/__pypackages__/3.10/lib/wagtail/admin/auth.py", line 205, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/app/server/__pypackages__/3.10/lib/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/app/server/__pypackages__/3.10/lib/wagtail/admin/views/generic/permissions.py", line 36, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/app/server/__pypackages__/3.10/lib/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/server/__pypackages__/3.10/lib/django/views/generic/edit.py", line 190, in get
    return super().get(request, *args, **kwargs)
  File "/app/server/__pypackages__/3.10/lib/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/app/server/__pypackages__/3.10/lib/wagtail/users/views/groups.py", line 145, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/app/server/__pypackages__/3.10/lib/wagtail/users/views/groups.py", line 52, in get_context_data
    return super().get_context_data(**kwargs)
  File "/app/server/__pypackages__/3.10/lib/wagtail/admin/views/generic/models.py", line 271, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/app/server/__pypackages__/3.10/lib/wagtail/admin/views/generic/base.py", line 26, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/app/server/__pypackages__/3.10/lib/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/app/server/__pypackages__/3.10/lib/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
  File "/app/server/__pypackages__/3.10/lib/wagtail/users/forms.py", line 229, in __init__
    self.registered_permissions = self.registered_permissions | fn()
  File "/app/server/__pypackages__/3.10/lib/wagtail/snippets/wagtail_hooks.py", line 40, in register_permissions
    content_types = ContentType.objects.get_for_models(*get_snippet_models()).values()
  File "/app/server/__pypackages__/3.10/lib/django/contrib/contenttypes/models.py", line 89, in get_for_models
    opts_models = needed_opts.pop(ct.model_class()._meta, [])

Exception Type: AttributeError at /admin/groups/1/
Exception Value: 'NoneType' object has no attribute '_meta'
```

**Comment by tmechsner** [comment]
Same problem here, also when running wagtail locally. Version: 3.0.2

**Comment by rosticheg** [comment]
The problem is that the model is in the django_content_type. Can be removed like:
from django.contrib.contenttypes.models import ContentType
DEL_MODELS = ["MODEL NAME"]
ct = ContentType.objects.all().order_by("app_label", "model")
for c in ct:
    if (c.model in DEL_MODELS):
        c.delete()
This fixes the problem

**Comment by nitinb99** [comment]
Facing the same random error on accessing the Group Detail page on the wagtail version 2.15.5
