### ISSUE TITLE
Error in search backends when uploading an Image

### ISSUE THREAD

**Issue by itekhi** [wagtail/wagtail#8713]
### Issue Summary

So when I am uploading an image with postgres database, I get an error and get stuck on an Image Chooser
```
File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 126, in title
    for current_field, boost, value in self.prepare_field(self.obj, field):
File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 63, in prepare_field
    get_weight(field.boost),
File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/weights.py", line 59, in get_weight
    return weight
UnboundLocalError: local variable 'weight' referenced before assignment
```
I think it's a quick fix, so no need to explain it more ;)

### Technical details

-   Python version: 3.9.5.
-   Django version: 4.0.4.
-   Wagtail version: 3.0.
-   Browser version: Firefox 101

**Comment by gasman** [comment]
> I think it's a quick fix

Maybe, but it'll be a lot quicker if you describe how to replicate the bug rather than making us guess...

Can you provide the model definition, please? From an initial look, it seems that you've specified a `boost` value in a `search_fields` definition, but for some reason the search backend isn't finding it when loading the model definitions on startup.

**Comment by itekhi** [comment]
Sorry, I just looked up the code and saw that the `weight` variable `get_weight` is returning doesn't exist...

It's just a django model(with modeladmin), no `search_fields` at all, this bug happens on every model, checked it on `Page` models and on django model.

**Comment by itekhi** [comment]
Here's the full traceback

```
python_1  | Internal Server Error: /wt/cms/images/chooser/upload/
python_1  | Traceback (most recent call last):
python_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
python_1  |     response = get_response(request)
python_1  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
python_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
python_1  |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
python_1  |     response = view_func(request, *args, **kwargs)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 161, in wrapper
python_1  |     return view_func(request, *args, **kwargs)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 205, in decorated_view
python_1  |     return view_func(request, *args, **kwargs)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 62, in wrapped_view_func
python_1  |     return view_func(request, *args, **kwargs)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/images/views/chooser.py", line 224, in chooser_upload
python_1  |     search_index.insert_or_update_object(image)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/index.py", line 168, in insert_or_update_object
python_1  |     backend.add(indexed_instance)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 774, in add
python_1  |     self.get_index_for_object(obj).add_item(obj)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 238, in add_item
python_1  |     self.add_items(obj._meta.model, [obj])
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 353, in add_items
python_1  |     update_method(content_type_pk, indexers)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 252, in add_items_upsert
python_1  |     IndexEntry._meta.get_field("title"), indexer.title
python_1  |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 49, in __get__
python_1  |     res = instance.__dict__[self.name] = self.func(instance)
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 126, in title
python_1  |     for current_field, boost, value in self.prepare_field(self.obj, field):
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 63, in prepare_field
python_1  |     get_weight(field.boost),
python_1  |   File "/usr/local/lib/python3.8/site-packages/wagtail/search/backends/database/postgres/weights.py", line 59, in get_weight
python_1  |     return weight
python_1  | UnboundLocalError: local variable 'weight' referenced before assignment
```

**Comment by gasman** [comment]
Do you run into the same issue if you start from a fresh Wagtail project (`wagtail start myproject`)? If so, please list the exact steps you take that lead up to the error. There's clearly something non-typical about your setup or the code changes you've made here, or else this would have come up many times before - unfortunately without any details of how to replicate this issue, it's hard to take this any further.

**Comment by itekhi** [comment]
No, I already used `wagtail` 3 with `postgres` database, everything is working as expected...

> this would have come up many times before

Yeeah, that's true, it was strange for me that I couldn't find anything about this... I'm using a `wagtail-pipit` template for my project, so there's a lot of code changes... Maybe a custom `Image` model is causing problems? But I didn't yet change anything in it...

That's a strange bug because nothing is changed about search... What can cause this?

**Comment by itekhi** [comment]
Ohhhh... Found it!
`wagtail.search` was not added to `INSTALLED_APPS` setting, so everything was falling apart.
I tried to override `CustomImage`s search_fields and got `relation "wagtailsearch_indexentry" does not exist`, so I wondered if `wagtail.search` is even installed...
