### ISSUE TITLE
Console is overloaded with errors when characters like "−" and "é" are added to the page title

### ISSUE THREAD

**Issue by boldo-h** [wagtail/wagtail#8884]
Console is overloaded with errors when characters like "−" and "é" are added to the page title.

### Issue Summary

I get lots of errors in console if I try in admin panel to edit and then publish or show in pages' list a page with symbols like 'é' or '−' in the title.
This errors completely overwhelm console and looks like they are not related directly to the cause (errors like keyerror 'self', keyerror 'show_parent', 'checbox_aria_label', "Exception while resolving variable '%s' in template '%s" and so on). 

Adding one of the symbols in the title causes these errors.
And back, deleting it from the title leads to the disappearance of errors.

The symbols are:
for '−'
U+2212 : MINUS SIGN

for 'é'
U+00E9 : LATIN SMALL LETTER E WITH ACUTE

Tested on two different PCs with Windows 10, with demo site deployed locally. Mysql database is at the hosting server.
The versions of wagtail and django that have been tested:
wagtail 2.14 + Django 3.2.14
wagtail 2.15 + Django 3.2.14
wagtail 2.16 + Django 3.2.14
wagtail 2.16 + Django 3.2
wagtail 2.14 + Django 3.0.1
wagtail 3.0.1 + Django 4.0.6

### Steps to Reproduce

1. Deploy demo-site [Windows 10]:
```
cd /d <some_dir>
python -m venv env
"env/Scripts/activate.bat"
mkdir mysite
pip install django==<django-version>
pip install wagtail==<wagtail-version>
pip install mysqlclient
wagtail start mysite mysite
```

2. Here I create new mysql database and:
```
ALTER DATABASE `a0669085_3s`
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;
```

3. Change settings in wagtail settings/dev.py:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'a0669085_1s',
        'USER': 'a0669085_1s',
        'PASSWORD': '***',
        'HOST': mysql_host_ip,
        'PORT': '3306',
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        }
    }
}

# configure logging
debug_dir = 'debug/'
if not os.path.exists(debug_dir):
    os.makedirs(
        debug_dir
    )
debug_django_file = debug_dir + '/debug_django.log'
debug_django_server_file = debug_dir + '/debug_django_server.log'
open(debug_django_file, 'w').close()
open(debug_django_server_file, 'w').close()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file1': {
            'level': 'DEBUG',  #DEBUG
            'class': 'logging.FileHandler',
            'filename': debug_django_file,
        },
        'file2': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': debug_django_server_file,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file1'],
            'level': 'DEBUG',  #INFO
            'propagate': True,
        },
        'django.server': {
            'handlers': ['file2'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
```

4. Migrate and run:
"mysite/manage.py" migrate
"mysite/manage.py" createsuperuser
"mysite/manage.py" runserver

5. Go to http://127.0.0.1:8000/admin/pages/
Add 'é' to 'Home' page title.
Publish.
And now I get all these errors when I try do edit 'Homeé' page
like http://127.0.0.1:8000/admin/pages/3/edit/
and when I try to see list of pages where 'Homeé' is shown.
like http://127.0.0.1:8000/admin/pages/1/

If 'é' is deleted errors are absent.

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes.

### Technical details

-   Python version: 3.9.6 / 3.9.7.
-   Django + Wagtail versions: 
wagtail 2.14 + Django 3.2.14
wagtail 2.15 + Django 3.2.14
wagtail 2.16 + Django 3.2.14
wagtail 2.16 + Django 3.2
wagtail 2.14 + Django 3.0.1
wagtail 3.0.1 + Django 4.0.6
-   Browser version: Firefox.

**Comment by boldo-h** [comment]
[error-wagtail 3.0.1-django 4.0.6.txt](https://github.com/wagtail/wagtail/files/9149598/error-wagtail.3.0.1-django.4.0.6.txt)
![wagtail-3 0 1-screen](https://user-images.githubusercontent.com/79913504/179978639-af9d77f1-9985-4520-83cb-2e6f3d3be321.PNG)

**Comment by mehrdadmoradii** [comment]
I used bakerydemo project, that didn't produce the bug.

## Steps

1. Clone the bakerydemo project using `https://github.com/wagtail/bakerydemo.git`.
2. Run `docker-compose up -d`.
3. Enter the container shell and create a super user using `docker exec -it container-name bash` then `/venv/bin/python3.9 manage.py createsuperuser`.
4. Bring up the container logs with `docker logs -f container-name`.
5. Edit the homepage as shown in the following figure:

![bug](https://user-images.githubusercontent.com/63321262/184714046-a2581bc7-f956-49d3-8974-75b64c883bf5.gif)

**As shown in the above figure, following the steps does not reproduce the bug.**

**Comment by lb-** [comment]
@boldo-h is this still happening? I've done some other testing recently with various characters of a similar nature and not seen this problem.

**Comment by gasman** [comment]
I'm seeing lines like this in the posted logfile:

```
Traceback (most recent call last):
  File "C:\Users\G\AppData\Local\Programs\Python\Python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\G\AppData\Local\Programs\Python\Python39\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xe9' in position 1490: character maps to <undefined>
```

This suggests that it's trying to write a log entry containing the title, but failing because the file is opened in CP1251 encoding. https://stackoverflow.com/a/56399557/1853523 suggests that adding `'encoding':'utf8'` to the logging config should fix it.
