### ISSUE TITLE
relation "wagtailcore_userprofile" does not exist - when removing `wagtail.users` from INSTALLED_APPS

### ISSUE THREAD

**Issue by robinzachmann** [wagtail/wagtail#8913]
### Issue Summary

When removing `wagtail.users` from `INSTALLED_APPS` in `settings.py` the following runtime error occurs:

__Error__
> psycopg2.errors.UndefinedTable: relation "wagtailcore_userprofile" does not exist
> LINE 1: ...me_zone", "wagtailcore_userprofile"."avatar" FROM "wagtailco...

__Traceback__
```
Traceback (most recent call last):
  File ".../site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "wagtailcore_userprofile" does not exist
LINE 1: ...me_zone", "wagtailcore_userprofile"."avatar" FROM "wagtailco...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File ".../site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File ".../site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File ".../site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File ".../site-packages/wagtail/admin/urls/__init__.py", line 161, in wrapper
    return view_func(request, *args, **kwargs)
  File ".../site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    if hasattr(user, "wagtail_userprofile"):
  File ".../site-packages/django/utils/functional.py", line 259, in inner
    return func(self._wrapped, *args)
  File ".../site-packages/django/db/models/fields/related_descriptors.py", line 450, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
  File ".../site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File ".../site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File ".../site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File ".../site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File ".../site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File ".../site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File ".../site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File ".../site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File ".../site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File ".../site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File ".../site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "wagtailcore_userprofile" does not exist
LINE 1: ...me_zone", "wagtailcore_userprofile"."avatar" FROM "wagtailco...
```

Any other relevant information.

I would like to disable Wagtail's user management entirely, because we are managing users in Django admin. 
I found an old [google groups discussion](https://groups.google.com/g/wagtail/c/hzjCE8WxsLc) where someone proposed to remove wagtail's users app from the INSTALLED_APPS. So this is what I tried. 

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

-   Python version: 3.9.10
-   Django version: 4.0.4
-   Wagtail version: 3.0.1
-   Browser version: not relevant

**Comment by gasman** [comment]
Hi @robinzachmann - thanks for the report. There's an existing issue for this at #3657.
