### ISSUE TITLE
collectstatic fails with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by tomkins** [wagtail/wagtail#8988]
### Issue Summary

`./manage.py collectstatic` results in the following:

```
$ ./manage.py collectstatic --noinput
Post-processing 'wagtailadmin/css/core.css' failed!

Traceback (most recent call last):
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/mysite/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 338, in _post_process
    content = pattern.sub(converter, content)
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 215, in converter
    hashed_url = self._url(
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 152, in _url
    hashed_name = hashed_name_func(*args)
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 388, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/Users/tomkins/.virtualenvs/tmp-d4293f9b5c4f657/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 113, in hashed_name
    raise ValueError(
ValueError: The file 'wagtailadmin/images/icons/chevron-down.svg' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x104f4e710>.
```

Assuming that #8921 is the most likely cause.

### Steps to Reproduce

```
pip install wagtail==4.0rc1
wagtail start mysite
cd mysite
pip install -r requirements.txt
./manage.py migrate
./manage.py collectstatic --noinput
```

### Technical details

- Python: 3.10
- Django: 4.1
- Wagtail: 4.0rc1

**Comment by danhayden** [comment]
I'm getting the same error when running `./manage.py collectstatic --noinput` on Wagtail: 4.0rc1

**Comment by gasman** [comment]
Confirmed on a new `wagtail start` project. Bisecting shows that this was introduced in af9b16e93d1f57e2c13f085c58e5e0307c751caf

**Comment by gasman** [comment]
.svg files referenced from the wagtailadmin CSS need to exist under `wagtail/admin/static/wagtailadmin/images/icons`, which in turn means they need to be placed in `wagtail/admin/static_src/wagtailadmin/images/icons/` to be copied into place by `npm run build`. Copying `chevron-down.svg` from `wagtail/admin/templates/wagtailadmin/icons/` into that location fixes the issue, but

1) we should confirm that that does the right thing UI-wise (and doesn't e.g. result in an oversized icon)
2) before we apply that fix, we should add a collectstatic step to our CI so that this sort of error gets caught in future, which I'm currently attempting to do (without much success) in #9001.
