### ISSUE TITLE
Jinja2 settings tag throwing exception 4.0rc1

### ISSUE THREAD

**Issue by seb-b** [wagtail/wagtail#8996]
### Issue Summary

After upgrading from 3.0.1 to 4.0rc1 anywhere a `{{ settings( ) }}` tag is used causes an exception

### Steps to Reproduce

Try to use the jinja2 settings tag, happens for both missing settings models and ones that exsist

Stacktrace - 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/jinja2.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/srv/rmi/jinja2/layouts/home/home_page.html", line 3, in top-level template code
    {% from "macros/image.html" import image_banner, image_tall %}
  File "/srv/rmi/jinja2/layouts/_page.html", line 1, in top-level template code
    {% extends "layouts/_body.html" %}
  File "/srv/rmi/jinja2/layouts/_body.html", line 1, in top-level template code
    {% extends "layouts/_html.html" %}
  File "/srv/rmi/jinja2/layouts/_html.html", line 54, in top-level template code
    {% block body %}{% endblock %}
  File "/srv/rmi/jinja2/layouts/_body.html", line 4, in block 'body'
    {% include "includes/header.html" %}
  File "/srv/rmi/jinja2/includes/header.html", line 9, in top-level template code
    {% block menu %}
  File "/srv/rmi/jinja2/includes/header.html", line 12, in block 'menu'
    {% include_block settings('core.MenuBuilder').menu_items %}
  File "/usr/local/lib/python3.10/site-packages/wagtail/contrib/settings/jinja2tags.py", line 79, in get_setting
    return context_cache[cache_key][model_string]
  File "/usr/local/lib/python3.10/site-packages/wagtail/contrib/settings/jinja2tags.py", line 34, in __getitem__
    return super().__getitem__(force_str(key).lower())
  File "/usr/local/lib/python3.10/site-packages/wagtail/contrib/settings/jinja2tags.py", line 57, in __missing__
    out = self[key] = Model.for_site(self.site)
  File "/usr/local/lib/python3.10/site-packages/wagtail/contrib/settings/models.py", line 143, in for_site
    instance, created = queryset.get_or_create(site=site)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    num = len(clone)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 262, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1354, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 69, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 519, in from_db
    new = cls(*values)
  File "/usr/local/lib/python3.10/site-packages/wagtail/contrib/settings/models.py", line 220, in __init__
    return super().__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/contrib/settings/models.py", line 60, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 426, in __init__
    raise IndexError("Number of args exceeds number of fields")
IndexError: Number of args exceeds number of fields
```
Project name in this example was `rmi`

Removing all `settings()` tags lets the page render fine

### Technical details

-   Python version: 3.10
-   Django version:  4.0
-   Wagtail version: 4.0rc1

**Comment by mehrdadmoradii** [comment]
I can also reproduce the bug.

### Technical details

- Python version: 3.9
- Django version: 4.0.7
- Wagtail version: 4.0rc1

# Steps to reproduce

1. Start a new project with `wagtail start mysite`.
2. Edit TEMPLATES at mysite/settings/base.py as following:

```Python
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'APP_DIRS': True,
        'OPTIONS': {
            'extensions': [
                'wagtail.jinja2tags.core',
                'wagtail.admin.jinja2tags.userbar',
                'wagtail.images.jinja2tags.images',
                'wagtail.contrib.settings.jinja2tags.settings'
            ],
        },
    },
]
```

3.  Add the following to home/models.py:

```Python
@register_setting
class SocialMediaSettings(BaseSetting):
    facebook = models.URLField(
        help_text='Your Facebook page URL')
    instagram = models.CharField(
        max_length=255, help_text='Your Instagram username, without the @')
    trip_advisor = models.URLField(
        help_text='Your Trip Advisor page URL')
    youtube = models.URLField(
        help_text='Your YouTube channel or user account URL')
```

4. Run `python manage.py makemigrations` and`python manage.py migrate`.
5. Add the following to home/jinja2/home/home_page.html:

```HTML
{{ settings("home.SocialMediaSettings").facebook }}
```

6. Navigate the browser to http://localhost:8000/.

Following the steps is going to produce the following error:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/backends/jinja2.py", line 76, in render
    return self.template.render(context)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/testing/mysite/home/jinja2/home/home_page.html", line 2, in top-level template code
    {{ settings("home.SocialMediaSettings").facebook }}
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 79, in get_setting
    return context_cache[cache_key][model_string]
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 34, in __getitem__
    return super().__getitem__(force_str(key).lower())
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 57, in __missing__
    out = self[key] = Model.for_site(self.site)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 133, in for_site
    instance, created = queryset.get_or_create(site=site)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 88, in __iter__
    obj = model_cls.from_db(
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/base.py", line 574, in from_db
    new = cls(*values)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 210, in __init__
    return super().__init__(self, *args, **kwargs)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 59, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/base.py", line 478, in __init__
    raise IndexError("Number of args exceeds number of fields")
IndexError: Number of args exceeds number of fields
[15/Aug/2022 17:53:38] "GET / HTTP/1.1" 500 148152
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/backends/jinja2.py", line 76, in render
    return self.template.render(context)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/testing/mysite/home/jinja2/home/home_page.html", line 2, in top-level template code
    {{ settings("home.SocialMediaSettings").facebook }}
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 79, in get_setting
    return context_cache[cache_key][model_string]
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 34, in __getitem__
    return super().__getitem__(force_str(key).lower())
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 57, in __missing__
    out = self[key] = Model.for_site(self.site)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 133, in for_site
    instance, created = queryset.get_or_create(site=site)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 88, in __iter__
    obj = model_cls.from_db(
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/base.py", line 574, in from_db
    new = cls(*values)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 210, in __init__
    return super().__init__(self, *args, **kwargs)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 59, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/base.py", line 478, in __init__
    raise IndexError("Number of args exceeds number of fields")
IndexError: Number of args exceeds number of fields
[15/Aug/2022 17:53:40] "GET / HTTP/1.1" 500 148152
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/template/backends/jinja2.py", line 76, in render
    return self.template.render(context)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/testing/mysite/home/jinja2/home/home_page.html", line 2, in top-level template code
    {{ settings("home.SocialMediaSettings").facebook }}
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 79, in get_setting
    return context_cache[cache_key][model_string]
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 34, in __getitem__
    return super().__getitem__(force_str(key).lower())
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/jinja2tags.py", line 57, in __missing__
    out = self[key] = Model.for_site(self.site)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 133, in for_site
    instance, created = queryset.get_or_create(site=site)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 657, in get_or_create
    return self.get(**kwargs), False
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/query.py", line 88, in __iter__
    obj = model_cls.from_db(
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/base.py", line 574, in from_db
    new = cls(*values)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 210, in __init__
    return super().__init__(self, *args, **kwargs)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail/wagtail/contrib/settings/models.py", line 59, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/mehrdadmoradi/Desktop/wagtail-dev/wagtail-dev-env/lib/python3.9/site-packages/django/db/models/base.py", line 478, in __init__
    raise IndexError("Number of args exceeds number of fields")
IndexError: Number of args exceeds number of fields
```

**Note: As I changed the Wagtail version from 3.0.1 to 4.0rc1 the error has been produced - there was no issue when using the 3.0.1 version.**

**Comment by chosak** [comment]
I can also reproduce this with the following test case, from within the Wagtail admin alone:

On Wagtail 3.0.1:

1. Create a new project `wagtail start testproject; cd testproject`
2. Edit testproject/settings.py: add `"wagtail.contrib.settings",` to `INSTALLED_APPS`, add `""wagtail.contrib.settings.context_processors.settings",`" to `TEMPLATES: { "OPTIONS": [ ... ] }`.
3. Edit home/models.py:
   
   ```py
   from django.db import models
   
   from wagtail.contrib.settings.models import BaseSetting, register_setting
   from wagtail.models import Page
   
   @register_setting
   class TestSetting(BaseSetting):
       text = models.TextField()
   
   class HomePage(Page):
       pass
   ```
4. `./manage.py makemigrations; ./manage.py migrate; ./manage.py createsuperuser`
5. `./manage.py runserver`, login at http://localhost:8000/admin/
6. Go to Setting > Test Settings. Everything works.

Upgrade Wagtail: `pip install 'wagtail==4.0rc1'`

1. `./manage.py migrate`
2. `./manage.py runserver`
3. Go to Setting > Test Settings. Get error message above.

**Comment by chosak** [comment]
In Django 3.2, the error message is slightly different:

> TypeError at /admin/settings/home/testsetting/2/
> Field 'id' expected a number but got <TestSetting: Test setting for localhost [default]>.

<details>
<summary>Full stack trace</summary>

```
Internal Server Error: /admin/settings/home/testsetting/2/
Traceback (most recent call last):
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
home.models.TestSetting.DoesNotExist: TestSetting matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'TestSetting'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 165, in wrapper
    return view_func(request, *args, **kwargs)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/wagtail/admin/auth.py", line 205, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/wagtail/contrib/settings/views.py", line 101, in edit
    instance = model.for_site(site)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/wagtail/contrib/settings/models.py", line 143, in for_site
    instance, created = queryset.get_or_create(site=site)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 2486, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/chosaka/Projects/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <TestSetting: Test setting for localhost [default]>.
[15/Aug/2022 20:21:03] "GET /admin/settings/home/testsetting/2/ HTTP/1.1" 500 173306
```
</details>

I spent a little time trying to figure out what is going on here. The problem seems to be something with [this line](https://github.com/wagtail/wagtail/blob/8564383ef5165ab4852ce967408e8ce5580960b5/wagtail/contrib/settings/models.py#L143); maybe something about how the primary key `id` field isn't getting explicitly set is causing problems with Django downstream code? But I wouldn't expect to have to set that, and the previous Wagtail 3.0.1 code had [similar logic](https://github.com/wagtail/wagtail/blob/9f1652dd21b5871812704237069c5c4a40bd99d9/wagtail/contrib/settings/models.py#L53), so I'm not sure what the issue is.

**Comment by th3hamm0r** [comment]
I've stumbled across a related problem #9006.
For me, changing from the outdated `BaseSetting` class to the new `BaseSiteSetting` class fixes the issues. 

This has been documented in the release notes, but not that the existing solution would break, which is obviously unintended.
https://docs.wagtail.org/en/latest/releases/4.0.html#basesetting-model-replaced-by-basesitesetting
