### ISSUE TITLE
Animated GIFs not working with many frames in the GIF.

### ISSUE THREAD

**Issue by pdiede** [wagtail/wagtail#9068]
### Issue Summary

Install Wagtail with all required dependencies. In order to use a GIF, WAND and imagemagick must be installed.

All steps have been implemented as specified in the documentation. (https://docs.wagtail.org/en/stable/advanced_topics/images/animated_gifs.html)

It seems like too much frames in the GIF will cause the error. I tried it with a GIF with less frames and it worked.

Unfortunately, the GIF handling with Wagtail currently does not work must be set more, which is not documented?

When uploading a GIF file I now get the following error message:

### Error Message

    2022-08-23 10:29:53,630 ERROR [django.request:241] log 73 140094513477440 Internal Server Error: /admin/images/multiple/add/
    Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
    File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 161, in wrapper
    return view_func(request, *args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/django/views/decorators/vary.py", line 21, in inner_func
    response = func(*args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/wagtail/admin/views/generic/multiple_upload.py", line 44, in dispatch
    return super().dispatch(request)
    File "/usr/local/lib/python3.8/site-packages/wagtail/admin/views/generic/permissions.py", line 36, in dispatch
    return super().dispatch(request, *args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/wagtail/admin/views/generic/multiple_upload.py", line 144, in post
    if form.is_valid():
    File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
    File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
    File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 433, in full_clean
    self._clean_fields()
    File "/usr/local/lib/python3.8/site-packages/django/forms/forms.py", line 443, in _clean_fields
    value = field.clean(value, bf.initial)
    File "/usr/local/lib/python3.8/site-packages/django/forms/fields.py", line 670, in clean
    return super().clean(data)
    File "/usr/local/lib/python3.8/site-packages/django/forms/fields.py", line 198, in clean
    value = self.to_python(value)
    File "/usr/local/lib/python3.8/site-packages/wagtail/images/fields.py", line 122, in to_python
    self.check_image_pixel_size(f)
    File "/usr/local/lib/python3.8/site-packages/wagtail/images/fields.py", line 112, in check_image_pixel_size
    self.error_messages["file_too_many_pixels"] % (num_pixels),
    ValueError: unsupported format character ')' (0x29) at index 33

### Steps to Reproduce

Install Wagtail with all the libraries in techincal details

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

    Django>=4.0,<4.1
    wagtail>3
    wagtail_localize==1.2.1
    django-extensions==3.2.0
    psycopg2==2.9.3
    loglevel==0.1.2
    Wand==0.6.10

Ubunutu Server: `sudo apt-get install libmagickwand-dev`

Local MacOS: `brew install imagemagick`

Thank you very much in advance.

I look forward to your feedback.

**Comment by gasman** [comment]
Hi @pdiede - thanks for the report. It looks like this error is occurring when trying to output the error message `"This file has too many pixels (%%s). Maximum pixels %s."` On further investigation, it looks like a few of our translations haven't correctly preserved the `%%s` placeholder, for example:

https://github.com/wagtail/wagtail/blob/c400d4b4efe0d336841c75fa817ac0f579b98fd7/wagtail/images/locale/sv/LC_MESSAGES/django.po#L56-L58

I'll fix these now.

**Comment by pdiede** [comment]
I found the problem: WAGTAILIMAGES_MAX_IMAGE_PIXELS = 128000000.

I had to set the WAGTAILIMAGES_MAX_IMAGE_PIXELS higher than the default. It would be nice if you could give a hint to it in the documentation at animated gifs page.
