### ISSUE TITLE
Registering a rich text feature with description from gettext_lazy throws TypeError in Wagtail 4

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#9121]
### Issue Summary

This is a new error to Wagtail 4. When registering a rich text plugin with description using `gettext_lazy`, an unhandled error occurs when loading any edit page with rich text field/block using this plugin.

### Steps to Reproduce

Using the block style example from the docs, the unedited example loads as expected:

``` python
@hooks.register('register_rich_text_features')
def register_help_text_feature(features):
    """
    Registering the `help-text` feature, which uses the `help-text` Draft.js block type,
    and is stored as HTML with a `<div class="help-text">` tag.
    """
    feature_name = 'help-text'
    type_ = 'help-text'

    control = {
        'type': type_,
        'label': '?',
        'description': 'Help text',
        # Optionally, we can tell Draftail what element to use when displaying those blocks in the editor.
        'element': 'div',
    }

    features.register_editor_plugin(
        'draftail', feature_name, draftail_features.BlockFeature(control, css={'all': ['help-text.css']})
    )

    features.register_converter_rule('contentstate', feature_name, {
        'from_database_format': {'div[class=help-text]': BlockElementHandler(type_)},
        'to_database_format': {'block_map': {type_: {'element': 'div', 'props': {'class': 'help-text'}}}},
    })
```
Now add multi-lingual support using gettext_lazy() for the description:

``` python
from django.utils.translation import gettext_lazy as _

@hooks.register('register_rich_text_features')
def register_help_text_feature(features):
    """
    Registering the `help-text` feature, which uses the `help-text` Draft.js block type,
    and is stored as HTML with a `<div class="help-text">` tag.
    """
    feature_name = 'help-text'
    type_ = 'help-text'

    control = {
        'type': type_,
        'label': '?',
        'description': _('Help text'),
        # Optionally, we can tell Draftail what element to use when displaying those blocks in the editor.
        'element': 'div',
    }

    features.register_editor_plugin(
        'draftail', feature_name, draftail_features.BlockFeature(control, css={'all': ['help-text.css']})
    )

    features.register_converter_rule('contentstate', feature_name, {
        'from_database_format': {'div[class=help-text]': BlockElementHandler(type_)},
        'to_database_format': {'block_map': {type_: {'element': 'div', 'props': {'class': 'help-text'}}}},
    })
```
When loading an editor with this feature, the following error is thrown:

<details>
<summary>Traceback</summary>

```
TypeError at /admin/pages/3/edit/
Object of type __proxy__ is not JSON serializable

Error during template rendering
In template c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\templates\wagtailadmin\panels\object_list.html, error at line 6

Object of type __proxy__ is not JSON serializable


1	{% load wagtailadmin_tags %}
2	
3	<div class="w-form-width">
4	    {% for child, identifier in self.visible_children_with_identifiers %}
5	        {% panel id_prefix=self.prefix id=identifier classname=child.classes|join:' ' heading=child.heading heading_size="label" icon=child.icon id_for_label=child.id_for_label is_required=child.is_required %}
6	            {% component child %}
7	        {% endpanel %}
8	    {% endfor %}
9	</div>

Traceback (most recent call last):
  File "c:\Django\testdev\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "c:\Django\testdev\.venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    current = current()
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\panels.py", line 392, in render_form_content
    return mark_safe(self.render_html() + self.render_missing_fields())
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\ui\components.py", line 20, in render_html
    return template.render(context_data)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 914, in _resolve_lookup
    current = current()
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\ui\components.py", line 20, in render_html
    return template.render(context_data)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\templatetags\wagtailadmin_tags.py", line 948, in render
    children = self.nodelist.render(context) if self.nodelist else ""
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "c:\Django\testdev\.venv\lib\site-packages\django\template\library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\templatetags\wagtailadmin_tags.py", line 876, in component
    return obj.render_html(context)
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\ui\components.py", line 15, in render_html
    context_data = self.get_context_data(parent_context)
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\panels.py", line 814, in get_context_data
    rendered_field = self.bound_field.as_widget(attrs=widget_attrs)
  File "c:\Django\testdev\.venv\lib\site-packages\django\forms\boundfield.py", line 99, in as_widget
    return widget.render(
  File "c:\Django\testdev\.venv\lib\site-packages\django\forms\widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
  File "c:\Django\testdev\.venv\lib\site-packages\wagtail\admin\rich_text\editors\draftail\__init__.py", line 68, in get_context
    context["widget"]["options_json"] = json.dumps(self.options)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: TypeError at /admin/pages/3/edit/
Exception Value: Object of type __proxy__ is not JSON serializable
```

</details>

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

`gettext_lazy` could be used for the description pre-Wagtail 4.0

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes

### Technical details

Django Version: 4.1
Python Version: 3.10.6
Wagtail: 4.0
Browser: Chrome/Mozilla/Edge current versions

**Comment by gasman** [comment]
Hi @enzedonline - thanks for the report.
I can confirm I'm seeing the same error, but as far as I can see the same thing happens as far back as Wagtail 2.12.6 and possibly further - can you confirm which Wagtail version you previously had this working on?

**Comment by enzedonline** [comment]
I have it running on 3.0.1. Looking through my history, the gettlazy_text was added post 3.x upgrade.

**Comment by laymonage** [comment]
It seems the crashing was fixed in #11620 (v6.1) as it added a custom encoder that supports lazy strings when serializing the rich text options. The `LazyStringEncoder` was then removed in favour of the built-in `DjangoJSONEncoder` in #11907 (v6.2).

I can confirm that the code example crashes on v6.0.x, but not on v6.1.x and latest `main`.

Although, if the description needs to be interpolated, looks like it might not be possible right now as described in #11075.
