### ISSUE TITLE
Postgres search test failures against Django 4.2a0

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9364]
Various Postgres search backend tests are [currently failing](https://github.com/wagtail/wagtail/actions/runs/3250398796/jobs/5334055999) against the Django main branch, with variants of this error:

```
ERROR: test_search_on_individual_field (wagtail.search.tests.test_postgres_backend.TestPostgresSearchBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "_vector_" does not exist
LINE 1: ...s'')')) ORDER BY (ts_rank('{0.025,0.05,0.2,1.0}', "_vector_"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/wagtail/wagtail/wagtail/search/tests/test_backends.py", line 166, in test_search_on_individual_field
    self.assertUnsortedListEqual([r.title for r in results], ["The Hobbit"])
  File "/home/runner/work/wagtail/wagtail/wagtail/search/backends/base.py", line 302, in __iter__
    return iter(self.results())
  File "/home/runner/work/wagtail/wagtail/wagtail/search/backends/base.py", line 268, in results
    self._results_cache = list(self._do_search())
  File "/home/runner/work/wagtail/wagtail/wagtail/search/backends/database/postgres/postgres.py", line 663, in _do_search
    return list(self.get_queryset())
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/models/query.py", line 394, in __iter__
    self._fetch_all()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/models/query.py", line 1894, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1529, in execute_sql
    cursor.execute(sql, params)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "_vector_" does not exist
LINE 1: ...s'')')) ORDER BY (ts_rank('{0.025,0.05,0.2,1.0}', "_vector_"...
```
`git bisect` shows that this started in https://github.com/django/django/commit/04518e310d4552ff7595a34f5a7f93487d78a406. If I tweak `PostgresSearchResults._do_search` to output the query SQL before running it...

```
    def _do_search(self):
        qs = self.get_queryset()
        print(qs.query)
        return list(qs)
```

then the before/after looks like this (not sure why it's not outputting valid code inside the COALESCE clause, but it's enough to get the gist):

Before (working):

    SELECT
        "searchtests_book"."id", "searchtests_book"."title", "searchtests_book"."publication_date", "searchtests_book"."number_of_pages",
        to_tsvector(COALESCE("searchtests_book"."title", )) AS "_vector_"
    FROM "searchtests_book"
    WHERE to_tsvector(COALESCE("searchtests_book"."title", )) @@ (to_tsquery(('Hobbit' | 'Westeros')))
    ORDER BY (ts_rank({0.025,0.05,0.2,1.0}, to_tsvector(COALESCE("searchtests_book"."title", )), to_tsquery(('Hobbit' | 'Westeros'))) * 2.0) DESC, "searchtests_book"."id" DESC

After (broken):

    SELECT
        "searchtests_book"."id", "searchtests_book"."title", "searchtests_book"."publication_date", "searchtests_book"."number_of_pages",
        to_tsvector(COALESCE("searchtests_book"."title", )) AS "_vector_"
    FROM "searchtests_book"
    WHERE to_tsvector(COALESCE("searchtests_book"."title", )) @@ (to_tsquery(('Hobbit' | 'Westeros')))
    ORDER BY (ts_rank({0.025,0.05,0.2,1.0}, "_vector_", to_tsquery(('Hobbit' | 'Westeros'))) * 2.0) DESC, "searchtests_book"."id" DESC

Evidently Postgres doesn't like using the computed `_vector_` column in the ORDER BY clause. It feels like it ought to be possible to reduce this to a test case that's not tied to the Postgres search extension, which will hopefully tell us whether this is a regression in Django, or Wagtail is doing something out-of-spec.

**Comment by gasman** [comment]
A reduced test case that doesn't depend on anything Wagtail-specific:

```
from bakerydemo.base.models import People
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

vector = SearchVector("first_name")
queryset = People.objects.annotate(vec=vector).order_by(SearchRank(vector, "ava"))
print(queryset.query)
list(queryset)
```

On https://github.com/django/django/commit/c58a8acd413ccc992dd30afd98ed900897e1f719 or earlier, this succeeds:

```
>>> print(queryset.query)
SELECT "base_people"."id", "base_people"."first_name", "base_people"."last_name", "base_people"."job_title", "base_people"."image_id", to_tsvector(COALESCE("base_people"."first_name", )) AS "vec" FROM "base_people" ORDER BY ts_rank(to_tsvector(COALESCE("base_people"."first_name", )), plainto_tsquery(ava)) ASC
>>> list(queryset)
[<People: Roberta Johnson>, <People: Olivia Ava>, <People: Lightnin' Hopkins>, <People: Muddy Waters>]
```

On https://github.com/django/django/commit/04518e310d4552ff7595a34f5a7f93487d78a406 or later, it fails:

```
>>> print(queryset.query)
SELECT "base_people"."id", "base_people"."first_name", "base_people"."last_name", "base_people"."job_title", "base_people"."image_id", to_tsvector(COALESCE("base_people"."first_name", )) AS "vec" FROM "base_people" ORDER BY ts_rank("vec", plainto_tsquery(ava)) ASC
>>> list(queryset)
Traceback (most recent call last):
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "vec" does not exist
LINE 1: ...'')) AS "vec" FROM "base_people" ORDER BY ts_rank("vec", pla...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/models/query.py", line 1894, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/models/sql/compiler.py", line 1520, in execute_sql
    cursor.execute(sql, params)
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/matthew/Development/tbx/wagtail/devscript/libs/django/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "vec" does not exist
LINE 1: ...'')) AS "vec" FROM "base_people" ORDER BY ts_rank("vec", pla...
                                                             ^
```

So far I haven't been able to replicate this independently of Postgres search, but it feels like it shouldn't be dependent on that - the root cause seems to be Django reusing an alias from the SELECT clause inside the ORDER BY clause in a way that Postgres doesn't like, rather than anything specific to the search functions. Either way, that's probably enough to open a bug against Django...

**Comment by gasman** [comment]
Bug opened on Django: https://code.djangoproject.com/ticket/34105

**Comment by gasman** [comment]
Fixed in Django.
