### ISSUE TITLE
Update Dash / Zeal offline docs for Wagtail 4.1

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#9420]
> **⚠️ Important:** Please do not attempt to pick this up until we are at least on Wagtail 4.1 RC 2 or the final release has gone out, so that any docs fixes can be included.

### Summary

Dash & Zeal docs apps are offline documentation tools that are really helpful for locally searching documentation and also for working offline. 

We have historically added Wagtail's documentation to their 'user contributed docs' and it would be good to do an update with the latest 4.1 RC (Release Candidate) documentation.

### Details

- The most recent documentation in that project is v4.0
- https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Wagtail/versions
- This is not an automated process but keeping this up to date every few releases is good for the community and helps those that may use these tools for projects like Django or even the Python docs as a quick reference
- You can read about how to do this on the project readme - https://github.com/Kapeli/Dash-User-Contributions
- For info about these tools see https://kapeli.com/dash & https://zealdocs.org/
- When a PR is up on the external repo - add a link to it here and we can close this issue once merged into that project

#### Previous updates for reference

- https://github.com/Kapeli/Dash-User-Contributions/pull/1802
- https://github.com/Kapeli/Dash-User-Contributions/pull/2758
- https://github.com/Kapeli/Dash-User-Contributions/pull/3944
- https://github.com/Kapeli/Dash-User-Contributions/pull/3943
- https://github.com/wagtail/wagtail/issues/9370 (previous issue to do the last round of updates)

**Comment by benitaanawonah** [comment]
Alright, i am working on this

**Comment by lb-** [comment]
@benitaanawonah please read the important note at the top of the description. We should wait a bit until the 4.1 code is confirmed to be ready for release. This way we can avoid any typos or docs issues from ending up in Dash incorrectly.

**Comment by activus-d** [comment]
Wagtail version 2.13

https://github.com/Kapeli/Dash-User-Contributions/pull/3932#event-7609509180

**Comment by Dev-Liz** [comment]
I'm interested in this too @lb-

**Comment by lb-** [comment]
@Dev-Liz  - only one person will need to do this change on the external repo, thanks though.

**Comment by Dev-Liz** [comment]
Oh, alright @lb-. Is there anyone I could work on please?? Looks like every issue has been taken.

**Comment by lb-** [comment]
@Dev-Liz this is good to go know if you are still keen as 4.1 is out.

**Comment by lb-** [comment]
Or @benitaanawonah if you wanted to pick this up

**Comment by Dev-Liz** [comment]
Yes, I am please @lb-. Will work on it today.

**Comment by lb-** [comment]
Thanks @Dev-Liz go for it. Reach out if you need a hand.

**Comment by Dev-Liz** [comment]
Alright, thanks @lb-

**Comment by Dev-Liz** [comment]
Hello @lb- I'm currently at the second step of the wagtail docset Readme.md instruction:

**- Install the package (in a virtualenv) and install the testing and docs requirements.**


Trying to install the testing and docs requirements using the command `pip install -e '.[testing,docs]' -U`

But I keep getting this error:

`pip install -e '.[testing,docs]' -U                                               
Obtaining file:///C:/Users/pc/Desktop/Outreachy/wagtail-4.1
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\pc\Desktop\Outreachy\wagtail-4.1\setup.py", line 3, in <module>
          from wagtail import __version__
        File "C:\Users\pc\Desktop\Outreachy\wagtail-4.1\wagtail\__init__.py", line 5, in <module>
          from wagtail.utils.version import get_semver_version, get_version
      ModuleNotFoundError: No module named 'wagtail.utils'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed`

Any help on how to resolve this would be appreciated.

**Comment by Dev-Liz** [comment]
### Wagtail version 4.1 docset

[Kapeli/Dash-User-Contributions#3984](https://github.com/Kapeli/Dash-User-Contributions/pull/3984)

**Comment by lb-** [comment]
@Dev-Liz  looks like you got it sorted - well done!

**Comment by Dev-Liz** [comment]
Thank you! @lb I got some help from @activus-d

**Comment by lb-** [comment]
This has been merged into the Dash project. 
@Dev-Liz can you do a new PR to this Wagtail project with a changelog entry?

**Comment by Dev-Liz** [comment]
Sure! @lb- how do I go about that, please??

**Comment by lb-** [comment]
@Dev-Liz  just do a PR similar to this one, in fact, update that same line with the version list updated and your name added.
https://github.com/wagtail/wagtail/pull/9460/files

You will need to make a new branch off wagtail/main and prepare a normal PR

https://github.com/wagtail/wagtail/blob/1af0815af0baaca801e2a09169d461a259f731ea/docs/releases/4.2.md?plain=1#L18

**Comment by Dev-Liz** [comment]
Alright, noted!

**Comment by Dev-Liz** [comment]
Done! @lb- 

[wagtail-4.1 documentation entry](https://github.com/wagtail/wagtail/pull/9681)

**Comment by lb-** [comment]
Merged in via a8abb58ccf69581c0a69091d37eba609bfcbdf48 & #9681
