### ISSUE TITLE
rebuild_references_index > (1048, "Column 'to_content_type_id' cannot be null")

### ISSUE THREAD

**Issue by mghiglieri** [wagtail/wagtail#9615]
Hi,

when trying to upgrade to wagtail 4.1 the rebuild_references_index command does not work correctly.
It seems that the method cannot detect the correct to_content_type value. Does anybody know, how to fix it?
Everything worked smoothly until 4.0x.

<details>
<summary>Traceback</summary>

```
<class 'oscar.apps.catalogue.models.ProductAttributeValue'>
Traceback (most recent call last):
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 320, in _query
    self._do_get_result(db)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 145, in _do_get_result
    self._result = result = self._get_result()
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/MySQLdb/cursors.py", line 352, in _get_result
    return self._get_db().store_result()
MySQLdb._exceptions.OperationalError: (1048, "Column 'to_content_type_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/wagtail/management/commands/rebuild_references_index.py", line 41, in handle
    ReferenceIndex.create_or_update_for_object(instance)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/wagtail/models/reference_index.py", line 388, in create_or_update_for_object
    cls.objects.bulk_create(
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/query.py", line 579, in bulk_create
    returned_columns = self._batched_insert(
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/query.py", line 1458, in _batched_insert
    self._insert(
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/envs/test.sicher3.de/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'to_content_type_id' cannot be null")
```
</details>

Thanks,
Marco

**Comment by gasman** [comment]
Haven't seen anything like that before. Please could you try running the following within `./manage.py shell`, and let us know the output:

    from oscar.apps.catalogue.models import ProductAttributeValue
    from wagtail.models import ReferenceIndex
    for obj in ProductAttributeValue.objects.all():
        refs = list(ReferenceIndex._extract_references_from_object(obj))
        if any(ref[0] is None for ref in refs):
            print(obj.pk, obj, refs)

**Comment by mghiglieri** [comment]
@gasman Thanks for helping.

`# python test.py
/var/envs/xy.de/lib/python3.8/site-packages/django/db/models/base.py:369: RemovedInWagtail50Warning: StreamField must explicitly set use_json_field argument to True/False instead of None.
  value.contribute_to_class(cls, name)
1 PDF1: images/products/2021/07/fsdgfdgdf.pdf [(79, '1', 'attribute', 'attribute'), (78, '35', 'product', 'product'), (None, 'None', 'value_entity', 'value_entity')]
2 PDF2: images/products/2021/07/zztrztr.pdf [(79, '2', 'attribute', 'attribute'), (78, '35', 'product', 'product'), (None, 'None', 'value_entity', 'value_entity')]
3 PDF3: images/products/2021/07/ztrzrzr.pdf [(79, '3', 'attribute', 'attribute'), (78, '35', 'product', 'product'), (None, 'None', 'value_entity', 'value_entity')]
`
Seems that it has a problem with value_entity since both values are None.

**Comment by gasman** [comment]
Thanks! I see from the django-oscar code that [`value_entity` is a generic foreign key](https://github.com/django-oscar/django-oscar/blob/a253f65ab67343c68921f56981f49839d2e2fe1b/src/oscar/apps/catalogue/abstract_models.py#L1064-L1065), and the references index code [has a special case for those](https://github.com/wagtail/wagtail/blob/main/wagtail/models/reference_index.py#L264-L271) but doesn't account for the possibility of them being null - that should give me enough to implement an independent test case and a fix.
