### ISSUE TITLE
get_site_for_hostname doesn't support ipv6 [::1]

### ISSUE THREAD

**Issue by yakovyarmo** [wagtail/wagtail#9621]
when the host header is [::1] and there is no port I get the following:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/wagtail/api/v2/router.py", line 68, in wrapped
    return func(request, *args, **kwargs)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/wagtail/api/v2/views.py", line 132, in handle_exception
    return super().handle_exception(exc)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/tutorela-serverside/tutorela/blog/api/views.py", line 46, in slug_detail_view
    instance = self.get_object()
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/wagtail/api/v2/views.py", line 553, in get_object
    base = super().get_object()
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/rest_framework/generics.py", line 83, in get_object
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/ubuntu/tutorela-serverside/tutorela/course/api/views.py", line 32, in get_queryset
    queryset = super().get_queryset()
  File "/home/ubuntu/tutorela-serverside/tutorela/blog/api/views.py", line 37, in get_queryset
    return self.model.objects.filter(id__in=self.get_base_queryset().values_list('id', flat=True))
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/wagtail/api/v2/views.py", line 512, in get_base_queryset
    site = Site.find_for_request(self.request)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/wagtail/models/sites.py", line 150, in find_for_request
    site = Site._find_for_request(request)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/wagtail/models/sites.py", line 160, in _find_for_request
    site = get_site_for_hostname(hostname, port)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/wagtail/models/sites.py", line 24, in get_site_for_hostname
    Site.objects.annotate(
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1225, in annotate
    return self._annotate(args, kwargs, select=True)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1273, in _annotate
    clone.query.add_annotation(
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1105, in add_annotation
    annotation = annotation.resolve_expression(
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/expressions.py", line 1179, in resolve_expression
    c.cases[pos] = case.resolve_expression(
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/expressions.py", line 1105, in resolve_expression
    c.condition = c.condition.resolve_expression(
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/query_utils.py", line 84, in resolve_expression
    clause, joins = query._add_q(
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1448, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1273, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1990, in get_prep_value
    raise e.__class__(
ValueError: Field 'port' expected a number but got ''.
Internal Server Error: /api/v1/course/slug/estimacion/
Traceback (most recent call last):
  File "/home/ubuntu/tutorela-serverside/.venv/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1988, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
```

it happens since `request.get_port()` return an empty string in this situation which later through an exception

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: yes 

### Technical details

-   Python version: Python 3.8.10.
-   Django version: 4.0.7.
-   Wagtail version: 3.0.1.
-   Browser version: Chrome 107.

**Comment by gasman** [comment]
@yakovyarmo Please can you provide specific steps to reproduce this on a fresh Wagtail project? (In particular, we need to know where you're setting the hostname/port, and what action you're performing to trigger the error.)

**Comment by yakovyarmo** [comment]
I'm using a gunicorn over linux socket file.
Does it help?

**Comment by yakovyarmo** [comment]
I'm using nuxt 2 with axios as the client side, and axios is setting the host.
How can I upload the steps to reproduce?
It happens with every call when the http header is [::1]

**Comment by gasman** [comment]
You don't need to upload anything. Please describe, in words, the things that you did, starting with a new installation, to make this error happen. For example:

* install Wagtail with `pip install wagtail`
* Run `wagtail start myproject`
* From the root of the project, run `./manage.py migrate`
* Install gunicorn with `pip install gunicorn`
* Run `gunicorn myproject.wsgi`
* Visit `http://[::1]:8000/` in the browser
* Receive the error

**Comment by yakovyarmo** [comment]
- install Wagtail with pip install wagtail
- Run wagtail start myproject
- From the root of the project, run ./manage.py migrate
- Install gunicorn with pip install gunicorn
- Run --bind unix:gunicorn.sock gunicorn myproject.wsgi
- I start nuxt server and nuxt server take care of proxying the request to the linux socket file

**Comment by gasman** [comment]
`--bind unix:gunicorn.sock gunicorn myproject.wsgi` is not a valid command, and if nuxt server is required to reproduce the bug, then the steps need to include setting up nuxt server too.

Closing as invalid.

**Comment by fivehanz** [comment]
i am facing similar error while using sockets.

META

```
HTTP_X_FORWARDED_PORT 	'443'
HTTP_X_FORWARDED_PROTO 	'https'
PATH_INFO 	'/'
QUERY_STRING 	''
REQUEST_METHOD 	'GET'
SCRIPT_NAME 	''
SERVER_NAME 	'/var/run/wagtail/wagtail.sock'
SERVER_PORT 	'None'
```

the error itself, traceback.

```
Environment:


Request Method: GET
Request URL: https://hanz.jsmx.org/

Django Version: 5.2.13
Python Version: 3.11.15
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail',
 'wagtail.contrib.routable_page',
 'wagtail.contrib.settings',
 'wagtail.contrib.search_promotions',
 'taggit',
 'modelcluster',
 'wagtailseo',
 'wagtailcache',
 'wagtail_flexible_forms',
 'django_vite',
 'turbo_helper',
 'apps.core',
 'apps.pages',
 'apps.blocks',
 'apps.navigation.apps.NavigationConfig',
 'apps.settings',
 'apps.search',
 'apps.forms',
 'apps.snippets']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'turbo_helper.middleware.TurboMiddleware']



Traceback (most recent call last):
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^

The above exception (invalid literal for int() with base 10: 'None') was the direct cause of the following exception:
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/wagtail/views.py", line 17, in serve
    route_result = Page.route_for_request(request, path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/wagtail/models/pages.py", line 491, in route_for_request
    if site := Site.find_for_request(request):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/wagtail/models/sites.py", line 157, in find_for_request
    site = Site._find_for_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/wagtail/models/sites.py", line 168, in _find_for_request
    site = get_site_for_hostname(hostname, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/wagtail/models/sites.py", line 24, in get_site_for_hostname
    Site.objects.annotate(
    ^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1654, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/query.py", line 1706, in _annotate
    clone.query.add_annotation(
    ^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1220, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/expressions.py", line 298, in resolve_expression
    source_expressions = [
                         
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/expressions.py", line 300, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize, for_save)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/expressions.py", line 1611, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize, for_save)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/expressions.py", line 298, in resolve_expression
    source_expressions = [
                         
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/expressions.py", line 300, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize, for_save)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/query_utils.py", line 95, in resolve_expression
    clause, joins = query._add_q(
                    
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1680, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1590, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1417, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/lookups.py", line 410, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/lookups.py", line 96, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/www/wagtail/.venv/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2130, in get_prep_value
    raise e.__class__(
    ^^^^^^^^

Exception Type: ValueError at /
Exception Value: Field 'port' expected a number but got 'None'.
```

checks:
- [x] - correct hostname
- [x] - all migrations done
- [x] - tried different header configurations

it is behind nginx proxy using unix sockets.

```
"$VENV/bin/python" -m uvicorn config.asgi:application \
    --uds "$SOCK" \
    --workers 1 \
    --loop uvloop \
    --http h11\
    --limit-concurrency 64 \
    --timeout-keep-alive 16 \
    --backlog 512 \
    --log-level info 
```

true as of this commit.

https://github.com/fivehanz/hanz.jsmx.org/commit/334a34f9cde6e497169ca21ef62597f93a96e9c3

i will try few more method + switch to tcp/http stack instead of sockets and will report back.

**Comment by fivehanz** [comment]
fixed with two lines.

```
proxy_set_header X-Forwarded-Port $server_port;
USE_X_FORWARDED_PORT = True
```

with these two lines; first one on nginx config, second on django settings file.
