### ISSUE TITLE
Error migrating from Wagtail version 4.0.4 to 4.1

### ISSUE THREAD

**Issue by OBKF** [wagtail/wagtail#9630]
### Issue Summary
I tried to update my project from Wagtail version 4.0.4 to 4.1, but I got an error.

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django_filters/utils.py", line 174, in get_field_parts
    opts = field.remote_field.model._meta
AttributeError: 'str' object has no attribute '_meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/Projects/Web/AsusAlgerie_Store/Website/home/models.py", line 20, in <module>
    from store.models import ProductPage
  File "/home/user/Projects/Web/AsusAlgerie_Store/Website/store/models.py", line 23, in <module>
    class ProductCategory(index.Indexed, models.Model):
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/wagtail/snippets/models.py", line 47, in register_snippet
    from wagtail.snippets.views.snippets import SnippetViewSet
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/wagtail/snippets/views/snippets.py", line 628, in <module>
    class SnippetHistoryReportFilterSet(WagtailFilterSet):
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django_filters/filterset.py", line 62, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django_filters/filterset.py", line 325, in get_filters
    field = get_model_field(cls._meta.model, field_name)
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django_filters/utils.py", line 144, in get_model_field
    fields = get_field_parts(model, field_name)
  File "/home/user/.local/share/virtualenvs/Website-iY00WjmF/lib/python3.10/site-packages/django_filters/utils.py", line 179, in get_field_parts
    raise RuntimeError(
RuntimeError: Unable to resolve relationship `user` for `wagtailcore.ModelLogEntry`. Django is most likely not initialized, and its apps registry not populated. Ensure Django has finished setup before loading `FilterSet`s.
```

I have a custom user model (I followed the Wagtail documentation)
```
# users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    phone = models.CharField(max_length=32, blank=False, null=True)
    address = models.TextField(blank=False, null=True)
```
```
# core/settings/base.py
AUTH_USER_MODEL = 'users.User'
```

### Technical details

-   Python version: `3.10`.
-   Django version: `4.1.3`.
-   Wagtail version: `4.0.4`.

**Comment by gasman** [comment]
Thanks for the report @OBKF! This has been reported previously at #9586, and a fix will be part of the 4.1.1 release (hopefully within the next week).
