### ISSUE TITLE
Reference indexing fails when a ParentalKey relation is masked by a property of the same name

### ISSUE THREAD

**Issue by gasman** [wagtail/wagtail#9708]
Developers will often set ParentalKey to point to the base `Page` model rather than the specific page type it relates to, meaning that the relation is defined on all page types, even if it's not used as such:

    class FooPage(Page):
        # ...

    class FooStatistics(Orderable):
        page = ParentalKey(Page, related_name="statistics")  # should really be FooPage
        # ...

The `ReferenceIndex. _extract_references_from_object` method will thus follow this relation for all page types. If some other page then re-uses that name for some other property - which would normally be harmless since we don't care about the relation becoming inaccessible on that page type:

    class BarPage(Page):
        @property
        def statistics(self):
            return BarStatistics.objects.first()

the reference index will fail at the point of calling `child_objects = getattr(object, relation_name).all()`, because `getattr(object, relation_name)` does not return the expected RelatedManager / QuerySet.

```
<class 'myapp.models.BarPage'>
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.8/site-packages/wagtail/management/commands/rebuild_references_index.py", line 52, in handle
    ReferenceIndex.create_or_update_for_object(instance)
  File "/venv/lib/python3.8/site-packages/wagtail/models/reference_index.py", line 364, in create_or_update_for_object
    references = set(cls._extract_references_from_object(object))
  File "/venv/lib/python3.8/site-packages/wagtail/models/reference_index.py", line 313, in _extract_references_from_object
    child_objects = getattr(object, relation_name).all()
AttributeError: 'BarStatistics' object has no attribute 'all'
```

Ideally we would be able to follow the relation without going through `getattr(object, relation_name)` - hopefully there's some method for doing this based on the `child_relation` object that we obtained `relation_name` from. (This would also allow it to work for `related_name="+"` relations - how do we handle those currently?)

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

**Comment by gasman** [comment]
> (This would also allow it to work for related_name="+" relations - how do we handle those currently?)

We are only concerned with ParentalKeys here, so the answer is... we don't.

https://github.com/wagtail/django-modelcluster/blob/be42bbe179f92a383b21b52b94d5be47fda46cc4/modelcluster/fields.py#L269-L277

**Comment by gasman** [comment]
On further investigation, masking ParentalKey relations in this way failed even before the reference index was added - `ClusterableModel.save` runs `getattr(self, relation).commit()`, and has done so since the start of Wagtail - therefore we can reasonably declare this setup unsupported.
