### ISSUE TITLE
Reference index `remove_reference_index_on_delete` handler is too broad

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#9832]
[`remove_reference_index_on_delete`](https://github.com/wagtail/wagtail/blob/71c94153278a75b8464c35ca33b05e46494f759a/wagtail/signal_handlers.py#L95-L100) is potentially overreaching and conflicts with a 3rd party package (`mozilla_django_oidc`) which does `auth.login()` which ends up clearing all `Session` objects for the user, which then results with a `relation "wagtailcore_referenceindex" does not exist`

Some possible cross-over with #9731

Ref: https://wagtailcms.slack.com/archives/C81FGJR2S/p1672240958154629 

<details>
<summary>Traceback</summary>

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/oidccallback/?state=REDACTE&session_state=REDACTED

Django Version: 3.2.11
Python Version: 3.10.7
Installed Applications:
['search',
 'demonstration',
 'staffpage',
 'basicpage',
 'orders',
 'tools',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.core',
 'wagtail.contrib.settings',
 'modelcluster',
 'taggit',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'ipa_auth',
 'wagtail.contrib.modeladmin',
 'wagtailmenus',
 'wagtailerrorpages',
 'widget_tweaks',
 'cookie_consent']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'mozilla_django_oidc.middleware.SessionRefresh']



Traceback (most recent call last):
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (relation "wagtailcore_referenceindex" does not exist
LINE 1: ...tailcore_referenceindex"."content_path_hash" FROM "wagtailco...
                                                             ^
) was the direct cause of the following exception:
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/mozilla_django_oidc/views.py", line 130, in get
    return self.login_success()
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/mozilla_django_oidc/views.py", line 60, in login_success
    auth.login(self.request, self.user)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 111, in login
    request.session.cycle_key()
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/contrib/sessions/backends/base.py", line 347, in cycle_key
    self.delete(key)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/contrib/sessions/backends/db.py", line 103, in delete
    self.model.objects.get(session_key=session_key).delete()
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/base.py", line 967, in delete
    return collector.delete()
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/deletion.py", line 435, in delete
    signals.post_delete.send(
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/wagtail/signal_handlers.py", line 100, in remove_reference_index_on_delete
    ReferenceIndex.remove_for_object(instance)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/wagtail/models/reference_index.py", line 453, in remove_for_object
    ).delete()
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 745, in delete
    collector.collect(del_query)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/deletion.py", line 243, in collect
    new_objs = self.add(objs, source, nullable,
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/deletion.py", line 107, in add
    if not objs:
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 284, in __bool__
    self._fetch_all()
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/aq229/.pyenv/versions/3.10.7/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /oidccallback/
Exception Value: relation "wagtailcore_referenceindex" does not exist
LINE 1: ...tailcore_referenceindex"."content_path_hash" FROM "wagtailco...
                                                          ^
```
</details>

**Comment by zerolab** [comment]
The problem, in the end, was a possibly faked `0078_referenceindex` (so actual missing table)
Will close as a prematurely filed bug
